/* Generated by klt-techmap (issue #874) */

module adder4 (a, b, cin, sum, cout);
  input [3:0] a;
  input [3:0] b;
  input cin;
  output [3:0] sum;
  output cout;
  wire n16;
  wire n17;
  wire n18;
  wire n19;
  wire n20;
  wire n21;
  wire n22;
  wire n23;
  wire n24;
  wire n25;
  wire n26;
  wire n27;
  wire n28;
  wire n29;
  wire n30;
  wire n31;
  wire n32;
  wire n33;

  sky130_fd_sc_hd__and2_0 _g0_ (
    .A(a[0]),
    .B(b[0]),
    .X(n16)
  );
  sky130_fd_sc_hd__and2_0 _g1_ (
    .A(a[1]),
    .B(b[1]),
    .X(n17)
  );
  sky130_fd_sc_hd__and2_0 _g2_ (
    .A(a[2]),
    .B(b[2]),
    .X(n18)
  );
  sky130_fd_sc_hd__and2_0 _g3_ (
    .A(a[3]),
    .B(b[3]),
    .X(n19)
  );
  sky130_fd_sc_hd__xor2_1 _g4_ (
    .A(a[0]),
    .B(b[0]),
    .X(n20)
  );
  sky130_fd_sc_hd__xor2_1 _g5_ (
    .A(a[1]),
    .B(b[1]),
    .X(n21)
  );
  sky130_fd_sc_hd__xor2_1 _g6_ (
    .A(a[2]),
    .B(b[2]),
    .X(n22)
  );
  sky130_fd_sc_hd__xor2_1 _g7_ (
    .A(a[3]),
    .B(b[3]),
    .X(n23)
  );
  sky130_fd_sc_hd__or2_0 _g8_ (
    .A(n18),
    .B(n24),
    .X(n25)
  );
  sky130_fd_sc_hd__and2_0 _g9_ (
    .A(n22),
    .B(n26),
    .X(n24)
  );
  sky130_fd_sc_hd__or2_0 _g10_ (
    .A(n27),
    .B(n28),
    .X(cout)
  );
  sky130_fd_sc_hd__and2_0 _g11_ (
    .A(n29),
    .B(n26),
    .X(n28)
  );
  sky130_fd_sc_hd__and2_0 _g12_ (
    .A(n23),
    .B(n22),
    .X(n29)
  );
  sky130_fd_sc_hd__or2_0 _g13_ (
    .A(n19),
    .B(n30),
    .X(n27)
  );
  sky130_fd_sc_hd__and2_0 _g14_ (
    .A(n23),
    .B(n18),
    .X(n30)
  );
  sky130_fd_sc_hd__or2_0 _g15_ (
    .A(n17),
    .B(n31),
    .X(n26)
  );
  sky130_fd_sc_hd__and2_0 _g16_ (
    .A(n21),
    .B(n32),
    .X(n31)
  );
  sky130_fd_sc_hd__or2_0 _g17_ (
    .A(n16),
    .B(n33),
    .X(n32)
  );
  sky130_fd_sc_hd__and2_0 _g18_ (
    .A(n20),
    .B(cin),
    .X(n33)
  );
  sky130_fd_sc_hd__xor2_1 _g19_ (
    .A(n20),
    .B(cin),
    .X(sum[0])
  );
  sky130_fd_sc_hd__xor2_1 _g20_ (
    .A(n21),
    .B(n32),
    .X(sum[1])
  );
  sky130_fd_sc_hd__xor2_1 _g21_ (
    .A(n22),
    .B(n26),
    .X(sum[2])
  );
  sky130_fd_sc_hd__xor2_1 _g22_ (
    .A(n23),
    .B(n25),
    .X(sum[3])
  );
endmodule
