/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module gcd(clk, rst_n, start, a_in, b_in, done, result);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  wire _284_;
  wire _285_;
  wire _286_;
  wire _287_;
  wire _288_;
  wire _289_;
  wire _290_;
  wire _291_;
  wire _292_;
  wire _293_;
  wire _294_;
  wire _295_;
  wire _296_;
  wire _297_;
  wire _298_;
  wire _299_;
  wire _300_;
  wire _301_;
  wire _302_;
  wire [15:0] a;
  input [15:0] a_in;
  wire [15:0] a_in;
  wire [15:0] b;
  input [15:0] b_in;
  wire [15:0] b_in;
  wire busy;
  input clk;
  wire clk;
  output done;
  wire done;
  output [15:0] result;
  wire [15:0] result;
  input rst_n;
  wire rst_n;
  input start;
  wire start;
  sky130_fd_sc_hd__clkinv_1 _303_ (
    .A(b[2]),
    .Y(_050_)
  );
  sky130_fd_sc_hd__clkinv_1 _304_ (
    .A(a[2]),
    .Y(_051_)
  );
  sky130_fd_sc_hd__clkinv_1 _305_ (
    .A(b[3]),
    .Y(_052_)
  );
  sky130_fd_sc_hd__clkinv_1 _306_ (
    .A(a[3]),
    .Y(_053_)
  );
  sky130_fd_sc_hd__clkinv_1 _307_ (
    .A(a[5]),
    .Y(_054_)
  );
  sky130_fd_sc_hd__clkinv_1 _308_ (
    .A(a[6]),
    .Y(_055_)
  );
  sky130_fd_sc_hd__clkinv_1 _309_ (
    .A(b[9]),
    .Y(_056_)
  );
  sky130_fd_sc_hd__clkinv_1 _310_ (
    .A(a[9]),
    .Y(_057_)
  );
  sky130_fd_sc_hd__clkinv_1 _311_ (
    .A(b[10]),
    .Y(_058_)
  );
  sky130_fd_sc_hd__clkinv_1 _312_ (
    .A(a[10]),
    .Y(_059_)
  );
  sky130_fd_sc_hd__clkinv_1 _313_ (
    .A(b[12]),
    .Y(_060_)
  );
  sky130_fd_sc_hd__clkinv_1 _314_ (
    .A(a[12]),
    .Y(_061_)
  );
  sky130_fd_sc_hd__clkinv_1 _315_ (
    .A(a[14]),
    .Y(_062_)
  );
  sky130_fd_sc_hd__clkinv_1 _316_ (
    .A(b[0]),
    .Y(_063_)
  );
  sky130_fd_sc_hd__clkinv_1 _317_ (
    .A(a[0]),
    .Y(_064_)
  );
  sky130_fd_sc_hd__clkinv_1 _318_ (
    .A(a[15]),
    .Y(_065_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _319_ (
    .A(start),
    .SLEEP(busy),
    .X(_066_)
  );
  sky130_fd_sc_hd__nand2b_1 _320_ (
    .A_N(busy),
    .B(start),
    .Y(_067_)
  );
  sky130_fd_sc_hd__nor4_1 _321_ (
    .A(a[6]),
    .B(a[7]),
    .C(a[8]),
    .D(a[9]),
    .Y(_068_)
  );
  sky130_fd_sc_hd__nor4_1 _322_ (
    .A(a[2]),
    .B(a[3]),
    .C(a[4]),
    .D(a[5]),
    .Y(_069_)
  );
  sky130_fd_sc_hd__nand2_1 _323_ (
    .A(_068_),
    .B(_069_),
    .Y(_070_)
  );
  sky130_fd_sc_hd__nor4_1 _324_ (
    .A(a[14]),
    .B(a[0]),
    .C(a[1]),
    .D(a[15]),
    .Y(_071_)
  );
  sky130_fd_sc_hd__nor4_1 _325_ (
    .A(a[10]),
    .B(a[11]),
    .C(a[12]),
    .D(a[13]),
    .Y(_072_)
  );
  sky130_fd_sc_hd__nand2_1 _326_ (
    .A(_071_),
    .B(_072_),
    .Y(_073_)
  );
  sky130_fd_sc_hd__nor2_1 _327_ (
    .A(_070_),
    .B(_073_),
    .Y(_074_)
  );
  sky130_fd_sc_hd__or4_1 _328_ (
    .A(b[10]),
    .B(b[11]),
    .C(b[1]),
    .D(b[15]),
    .X(_075_)
  );
  sky130_fd_sc_hd__or4_1 _329_ (
    .A(b[6]),
    .B(b[7]),
    .C(b[12]),
    .D(b[13]),
    .X(_076_)
  );
  sky130_fd_sc_hd__nor4_1 _330_ (
    .A(b[14]),
    .B(b[0]),
    .C(_075_),
    .D(_076_),
    .Y(_077_)
  );
  sky130_fd_sc_hd__nor3_1 _331_ (
    .A(b[2]),
    .B(b[8]),
    .C(b[9]),
    .Y(_078_)
  );
  sky130_fd_sc_hd__nor3_1 _332_ (
    .A(b[3]),
    .B(b[4]),
    .C(b[5]),
    .Y(_079_)
  );
  sky130_fd_sc_hd__a31oi_1 _333_ (
    .A1(_077_),
    .A2(_078_),
    .A3(_079_),
    .B1(_074_),
    .Y(_080_)
  );
  sky130_fd_sc_hd__and2_0 _334_ (
    .A(busy),
    .B(_080_),
    .X(_081_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _335_ (
    .A(_066_),
    .SLEEP(_081_),
    .X(_000_)
  );
  sky130_fd_sc_hd__nand2b_1 _336_ (
    .A_N(_080_),
    .B(busy),
    .Y(_082_)
  );
  sky130_fd_sc_hd__clkinv_1 _337_ (
    .A(_082_),
    .Y(_001_)
  );
  sky130_fd_sc_hd__xnor2_1 _338_ (
    .A(b[15]),
    .B(a[15]),
    .Y(_083_)
  );
  sky130_fd_sc_hd__nor2_1 _339_ (
    .A(b[14]),
    .B(_062_),
    .Y(_084_)
  );
  sky130_fd_sc_hd__xnor2_1 _340_ (
    .A(b[14]),
    .B(a[14]),
    .Y(_085_)
  );
  sky130_fd_sc_hd__nand2b_1 _341_ (
    .A_N(a[13]),
    .B(b[13]),
    .Y(_086_)
  );
  sky130_fd_sc_hd__nand2b_1 _342_ (
    .A_N(b[13]),
    .B(a[13]),
    .Y(_087_)
  );
  sky130_fd_sc_hd__nand2_1 _343_ (
    .A(_086_),
    .B(_087_),
    .Y(_088_)
  );
  sky130_fd_sc_hd__nand2_1 _344_ (
    .A(b[12]),
    .B(_061_),
    .Y(_089_)
  );
  sky130_fd_sc_hd__nand2_1 _345_ (
    .A(_060_),
    .B(a[12]),
    .Y(_090_)
  );
  sky130_fd_sc_hd__nand2_1 _346_ (
    .A(_089_),
    .B(_090_),
    .Y(_091_)
  );
  sky130_fd_sc_hd__nand4_1 _347_ (
    .A(_086_),
    .B(_087_),
    .C(_089_),
    .D(_090_),
    .Y(_092_)
  );
  sky130_fd_sc_hd__xnor2_1 _348_ (
    .A(b[10]),
    .B(a[10]),
    .Y(_093_)
  );
  sky130_fd_sc_hd__nand2b_1 _349_ (
    .A_N(a[11]),
    .B(b[11]),
    .Y(_094_)
  );
  sky130_fd_sc_hd__nand2b_1 _350_ (
    .A_N(b[11]),
    .B(a[11]),
    .Y(_095_)
  );
  sky130_fd_sc_hd__and2_0 _351_ (
    .A(_094_),
    .B(_095_),
    .X(_096_)
  );
  sky130_fd_sc_hd__xor2_1 _352_ (
    .A(b[9]),
    .B(a[9]),
    .X(_097_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _353_ (
    .A(b[8]),
    .SLEEP(a[8]),
    .X(_098_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _354_ (
    .A(a[8]),
    .SLEEP(b[8]),
    .X(_099_)
  );
  sky130_fd_sc_hd__nor2_1 _355_ (
    .A(_098_),
    .B(_099_),
    .Y(_100_)
  );
  sky130_fd_sc_hd__nor3_1 _356_ (
    .A(_097_),
    .B(_098_),
    .C(_099_),
    .Y(_101_)
  );
  sky130_fd_sc_hd__and3_1 _357_ (
    .A(_093_),
    .B(_096_),
    .C(_101_),
    .X(_102_)
  );
  sky130_fd_sc_hd__nand2b_1 _358_ (
    .A_N(a[7]),
    .B(b[7]),
    .Y(_103_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _359_ (
    .A(a[7]),
    .SLEEP(b[7]),
    .X(_104_)
  );
  sky130_fd_sc_hd__xnor2_1 _360_ (
    .A(b[7]),
    .B(a[7]),
    .Y(_105_)
  );
  sky130_fd_sc_hd__xor2_1 _361_ (
    .A(b[7]),
    .B(a[7]),
    .X(_106_)
  );
  sky130_fd_sc_hd__nand2_1 _362_ (
    .A(b[6]),
    .B(_055_),
    .Y(_107_)
  );
  sky130_fd_sc_hd__nor2_1 _363_ (
    .A(b[6]),
    .B(_055_),
    .Y(_108_)
  );
  sky130_fd_sc_hd__xnor2_1 _364_ (
    .A(b[6]),
    .B(a[6]),
    .Y(_109_)
  );
  sky130_fd_sc_hd__nand2_1 _365_ (
    .A(_105_),
    .B(_109_),
    .Y(_110_)
  );
  sky130_fd_sc_hd__xor2_1 _366_ (
    .A(b[5]),
    .B(a[5]),
    .X(_111_)
  );
  sky130_fd_sc_hd__nand2b_1 _367_ (
    .A_N(a[4]),
    .B(b[4]),
    .Y(_112_)
  );
  sky130_fd_sc_hd__nand2b_1 _368_ (
    .A_N(b[4]),
    .B(a[4]),
    .Y(_113_)
  );
  sky130_fd_sc_hd__nand2_1 _369_ (
    .A(_112_),
    .B(_113_),
    .Y(_114_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _370_ (
    .A(_111_),
    .SLEEP(_114_),
    .X(_115_)
  );
  sky130_fd_sc_hd__or3_1 _371_ (
    .A(_110_),
    .B(_111_),
    .C(_114_),
    .X(_116_)
  );
  sky130_fd_sc_hd__xor2_1 _372_ (
    .A(b[3]),
    .B(a[3]),
    .X(_117_)
  );
  sky130_fd_sc_hd__xnor2_1 _373_ (
    .A(b[2]),
    .B(a[2]),
    .Y(_118_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _374_ (
    .A(b[1]),
    .SLEEP(a[1]),
    .X(_119_)
  );
  sky130_fd_sc_hd__nand2b_1 _375_ (
    .A_N(b[0]),
    .B(a[0]),
    .Y(_120_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _376_ (
    .A(a[1]),
    .SLEEP(b[1]),
    .X(_121_)
  );
  sky130_fd_sc_hd__xnor2_1 _377_ (
    .A(b[1]),
    .B(a[1]),
    .Y(_122_)
  );
  sky130_fd_sc_hd__a21oi_1 _378_ (
    .A1(_120_),
    .A2(_122_),
    .B1(_119_),
    .Y(_123_)
  );
  sky130_fd_sc_hd__maj3_1 _379_ (
    .A(_050_),
    .B(a[2]),
    .C(_123_),
    .X(_124_)
  );
  sky130_fd_sc_hd__maj3_1 _380_ (
    .A(_052_),
    .B(a[3]),
    .C(_124_),
    .X(_125_)
  );
  sky130_fd_sc_hd__nor2_1 _381_ (
    .A(_111_),
    .B(_112_),
    .Y(_126_)
  );
  sky130_fd_sc_hd__a21oi_1 _382_ (
    .A1(b[5]),
    .A2(_054_),
    .B1(_126_),
    .Y(_127_)
  );
  sky130_fd_sc_hd__o221a_1 _383_ (
    .A1(_106_),
    .A2(_107_),
    .B1(_110_),
    .B2(_127_),
    .C1(_103_),
    .X(_128_)
  );
  sky130_fd_sc_hd__o21ai_0 _384_ (
    .A1(_116_),
    .A2(_125_),
    .B1(_128_),
    .Y(_129_)
  );
  sky130_fd_sc_hd__maj3_1 _385_ (
    .A(b[9]),
    .B(_057_),
    .C(_098_),
    .X(_130_)
  );
  sky130_fd_sc_hd__nand3_1 _386_ (
    .A(_093_),
    .B(_096_),
    .C(_130_),
    .Y(_131_)
  );
  sky130_fd_sc_hd__nand3_1 _387_ (
    .A(b[10]),
    .B(_059_),
    .C(_096_),
    .Y(_132_)
  );
  sky130_fd_sc_hd__nand3_1 _388_ (
    .A(_094_),
    .B(_131_),
    .C(_132_),
    .Y(_133_)
  );
  sky130_fd_sc_hd__a21oi_1 _389_ (
    .A1(_102_),
    .A2(_129_),
    .B1(_133_),
    .Y(_134_)
  );
  sky130_fd_sc_hd__o221ai_1 _390_ (
    .A1(_088_),
    .A2(_089_),
    .B1(_092_),
    .B2(_134_),
    .C1(_086_),
    .Y(_135_)
  );
  sky130_fd_sc_hd__maj3_1 _391_ (
    .A(b[14]),
    .B(_062_),
    .C(_135_),
    .X(_136_)
  );
  sky130_fd_sc_hd__maj3_1 _392_ (
    .A(b[15]),
    .B(_065_),
    .C(_136_),
    .X(_137_)
  );
  sky130_fd_sc_hd__a21oi_1 _393_ (
    .A1(_081_),
    .A2(_137_),
    .B1(_066_),
    .Y(_138_)
  );
  sky130_fd_sc_hd__nand2b_1 _394_ (
    .A_N(a[0]),
    .B(b[0]),
    .Y(_139_)
  );
  sky130_fd_sc_hd__a21oi_1 _395_ (
    .A1(_120_),
    .A2(_139_),
    .B1(_066_),
    .Y(_140_)
  );
  sky130_fd_sc_hd__a21oi_1 _396_ (
    .A1(b_in[0]),
    .A2(_066_),
    .B1(_140_),
    .Y(_141_)
  );
  sky130_fd_sc_hd__mux2i_1 _397_ (
    .A0(_141_),
    .A1(_063_),
    .S(_138_),
    .Y(_002_)
  );
  sky130_fd_sc_hd__a21oi_1 _398_ (
    .A1(_120_),
    .A2(_122_),
    .B1(_066_),
    .Y(_142_)
  );
  sky130_fd_sc_hd__o21ai_0 _399_ (
    .A1(_120_),
    .A2(_122_),
    .B1(_142_),
    .Y(_143_)
  );
  sky130_fd_sc_hd__nand2_1 _400_ (
    .A(b_in[1]),
    .B(_066_),
    .Y(_144_)
  );
  sky130_fd_sc_hd__nand2_1 _401_ (
    .A(_143_),
    .B(_144_),
    .Y(_145_)
  );
  sky130_fd_sc_hd__mux2_1 _402_ (
    .A0(_145_),
    .A1(b[1]),
    .S(_138_),
    .X(_003_)
  );
  sky130_fd_sc_hd__xor2_1 _403_ (
    .A(_118_),
    .B(_123_),
    .X(_146_)
  );
  sky130_fd_sc_hd__nor2_1 _404_ (
    .A(b_in[2]),
    .B(_067_),
    .Y(_147_)
  );
  sky130_fd_sc_hd__a21oi_1 _405_ (
    .A1(_067_),
    .A2(_146_),
    .B1(_147_),
    .Y(_148_)
  );
  sky130_fd_sc_hd__mux2_1 _406_ (
    .A0(_148_),
    .A1(b[2]),
    .S(_138_),
    .X(_004_)
  );
  sky130_fd_sc_hd__xnor2_1 _407_ (
    .A(_117_),
    .B(_124_),
    .Y(_149_)
  );
  sky130_fd_sc_hd__nand2_1 _408_ (
    .A(_067_),
    .B(_149_),
    .Y(_150_)
  );
  sky130_fd_sc_hd__o21ai_0 _409_ (
    .A1(b_in[3]),
    .A2(_067_),
    .B1(_150_),
    .Y(_151_)
  );
  sky130_fd_sc_hd__mux2i_1 _410_ (
    .A0(_151_),
    .A1(_052_),
    .S(_138_),
    .Y(_005_)
  );
  sky130_fd_sc_hd__xnor2_1 _411_ (
    .A(_114_),
    .B(_125_),
    .Y(_152_)
  );
  sky130_fd_sc_hd__nor2_1 _412_ (
    .A(b_in[4]),
    .B(_067_),
    .Y(_153_)
  );
  sky130_fd_sc_hd__a21oi_1 _413_ (
    .A1(_067_),
    .A2(_152_),
    .B1(_153_),
    .Y(_154_)
  );
  sky130_fd_sc_hd__mux2_1 _414_ (
    .A0(_154_),
    .A1(b[4]),
    .S(_138_),
    .X(_006_)
  );
  sky130_fd_sc_hd__o21ai_0 _415_ (
    .A1(_114_),
    .A2(_125_),
    .B1(_112_),
    .Y(_155_)
  );
  sky130_fd_sc_hd__xor2_1 _416_ (
    .A(_111_),
    .B(_155_),
    .X(_156_)
  );
  sky130_fd_sc_hd__nand2_1 _417_ (
    .A(b_in[5]),
    .B(_066_),
    .Y(_157_)
  );
  sky130_fd_sc_hd__o21ai_0 _418_ (
    .A1(_066_),
    .A2(_156_),
    .B1(_157_),
    .Y(_158_)
  );
  sky130_fd_sc_hd__mux2_1 _419_ (
    .A0(_158_),
    .A1(b[5]),
    .S(_138_),
    .X(_007_)
  );
  sky130_fd_sc_hd__nand2_1 _420_ (
    .A(b_in[6]),
    .B(_066_),
    .Y(_159_)
  );
  sky130_fd_sc_hd__o21ai_0 _421_ (
    .A1(_115_),
    .A2(_125_),
    .B1(_127_),
    .Y(_160_)
  );
  sky130_fd_sc_hd__nand2_1 _422_ (
    .A(_109_),
    .B(_160_),
    .Y(_161_)
  );
  sky130_fd_sc_hd__nor2_1 _423_ (
    .A(_109_),
    .B(_160_),
    .Y(_162_)
  );
  sky130_fd_sc_hd__nand2_1 _424_ (
    .A(_067_),
    .B(_161_),
    .Y(_163_)
  );
  sky130_fd_sc_hd__o21ai_0 _425_ (
    .A1(_162_),
    .A2(_163_),
    .B1(_159_),
    .Y(_164_)
  );
  sky130_fd_sc_hd__mux2_1 _426_ (
    .A0(_164_),
    .A1(b[6]),
    .S(_138_),
    .X(_008_)
  );
  sky130_fd_sc_hd__nand2_1 _427_ (
    .A(_107_),
    .B(_161_),
    .Y(_165_)
  );
  sky130_fd_sc_hd__xnor2_1 _428_ (
    .A(_105_),
    .B(_165_),
    .Y(_166_)
  );
  sky130_fd_sc_hd__nand2_1 _429_ (
    .A(b_in[7]),
    .B(_066_),
    .Y(_167_)
  );
  sky130_fd_sc_hd__o21ai_0 _430_ (
    .A1(_066_),
    .A2(_166_),
    .B1(_167_),
    .Y(_168_)
  );
  sky130_fd_sc_hd__mux2_1 _431_ (
    .A0(_168_),
    .A1(b[7]),
    .S(_138_),
    .X(_009_)
  );
  sky130_fd_sc_hd__nand2_1 _432_ (
    .A(b_in[8]),
    .B(_066_),
    .Y(_169_)
  );
  sky130_fd_sc_hd__and2_0 _433_ (
    .A(_100_),
    .B(_129_),
    .X(_170_)
  );
  sky130_fd_sc_hd__o21ai_0 _434_ (
    .A1(_100_),
    .A2(_129_),
    .B1(_067_),
    .Y(_171_)
  );
  sky130_fd_sc_hd__o21ai_0 _435_ (
    .A1(_170_),
    .A2(_171_),
    .B1(_169_),
    .Y(_172_)
  );
  sky130_fd_sc_hd__mux2_1 _436_ (
    .A0(_172_),
    .A1(b[8]),
    .S(_138_),
    .X(_010_)
  );
  sky130_fd_sc_hd__nor2_1 _437_ (
    .A(_098_),
    .B(_170_),
    .Y(_173_)
  );
  sky130_fd_sc_hd__o21ai_0 _438_ (
    .A1(_097_),
    .A2(_173_),
    .B1(_067_),
    .Y(_174_)
  );
  sky130_fd_sc_hd__a21oi_1 _439_ (
    .A1(_097_),
    .A2(_173_),
    .B1(_174_),
    .Y(_175_)
  );
  sky130_fd_sc_hd__a21oi_1 _440_ (
    .A1(b_in[9]),
    .A2(_066_),
    .B1(_175_),
    .Y(_176_)
  );
  sky130_fd_sc_hd__mux2i_1 _441_ (
    .A0(_176_),
    .A1(_056_),
    .S(_138_),
    .Y(_011_)
  );
  sky130_fd_sc_hd__a21o_1 _442_ (
    .A1(_101_),
    .A2(_129_),
    .B1(_130_),
    .X(_177_)
  );
  sky130_fd_sc_hd__nor2_1 _443_ (
    .A(_093_),
    .B(_177_),
    .Y(_178_)
  );
  sky130_fd_sc_hd__nand2_1 _444_ (
    .A(_093_),
    .B(_177_),
    .Y(_179_)
  );
  sky130_fd_sc_hd__nor2_1 _445_ (
    .A(_066_),
    .B(_178_),
    .Y(_180_)
  );
  sky130_fd_sc_hd__a22oi_1 _446_ (
    .A1(b_in[10]),
    .A2(_066_),
    .B1(_179_),
    .B2(_180_),
    .Y(_181_)
  );
  sky130_fd_sc_hd__mux2i_1 _447_ (
    .A0(_181_),
    .A1(_058_),
    .S(_138_),
    .Y(_012_)
  );
  sky130_fd_sc_hd__o21ai_0 _448_ (
    .A1(_058_),
    .A2(a[10]),
    .B1(_179_),
    .Y(_182_)
  );
  sky130_fd_sc_hd__xnor2_1 _449_ (
    .A(_096_),
    .B(_182_),
    .Y(_183_)
  );
  sky130_fd_sc_hd__nand2_1 _450_ (
    .A(b_in[11]),
    .B(_066_),
    .Y(_184_)
  );
  sky130_fd_sc_hd__o21ai_0 _451_ (
    .A1(_066_),
    .A2(_183_),
    .B1(_184_),
    .Y(_185_)
  );
  sky130_fd_sc_hd__mux2_1 _452_ (
    .A0(_185_),
    .A1(b[11]),
    .S(_138_),
    .X(_013_)
  );
  sky130_fd_sc_hd__o21ai_0 _453_ (
    .A1(_091_),
    .A2(_134_),
    .B1(_067_),
    .Y(_186_)
  );
  sky130_fd_sc_hd__a21oi_1 _454_ (
    .A1(_091_),
    .A2(_134_),
    .B1(_186_),
    .Y(_187_)
  );
  sky130_fd_sc_hd__a21oi_1 _455_ (
    .A1(b_in[12]),
    .A2(_066_),
    .B1(_187_),
    .Y(_188_)
  );
  sky130_fd_sc_hd__mux2i_1 _456_ (
    .A0(_188_),
    .A1(_060_),
    .S(_138_),
    .Y(_014_)
  );
  sky130_fd_sc_hd__o21ai_0 _457_ (
    .A1(_091_),
    .A2(_134_),
    .B1(_089_),
    .Y(_189_)
  );
  sky130_fd_sc_hd__xor2_1 _458_ (
    .A(_088_),
    .B(_189_),
    .X(_190_)
  );
  sky130_fd_sc_hd__nand2_1 _459_ (
    .A(b_in[13]),
    .B(_066_),
    .Y(_191_)
  );
  sky130_fd_sc_hd__o21ai_0 _460_ (
    .A1(_066_),
    .A2(_190_),
    .B1(_191_),
    .Y(_192_)
  );
  sky130_fd_sc_hd__mux2_1 _461_ (
    .A0(_192_),
    .A1(b[13]),
    .S(_138_),
    .X(_015_)
  );
  sky130_fd_sc_hd__nand2_1 _462_ (
    .A(b_in[14]),
    .B(_066_),
    .Y(_193_)
  );
  sky130_fd_sc_hd__a21oi_1 _463_ (
    .A1(_085_),
    .A2(_135_),
    .B1(_066_),
    .Y(_194_)
  );
  sky130_fd_sc_hd__o21ai_0 _464_ (
    .A1(_085_),
    .A2(_135_),
    .B1(_194_),
    .Y(_195_)
  );
  sky130_fd_sc_hd__nand2_1 _465_ (
    .A(_193_),
    .B(_195_),
    .Y(_196_)
  );
  sky130_fd_sc_hd__mux2_1 _466_ (
    .A0(_196_),
    .A1(b[14]),
    .S(_138_),
    .X(_016_)
  );
  sky130_fd_sc_hd__nand2_1 _467_ (
    .A(b_in[15]),
    .B(_066_),
    .Y(_197_)
  );
  sky130_fd_sc_hd__nor2_1 _468_ (
    .A(_083_),
    .B(_136_),
    .Y(_198_)
  );
  sky130_fd_sc_hd__a21o_1 _469_ (
    .A1(_083_),
    .A2(_136_),
    .B1(_066_),
    .X(_199_)
  );
  sky130_fd_sc_hd__o21ai_0 _470_ (
    .A1(_198_),
    .A2(_199_),
    .B1(_197_),
    .Y(_200_)
  );
  sky130_fd_sc_hd__mux2_1 _471_ (
    .A0(_200_),
    .A1(b[15]),
    .S(_138_),
    .X(_017_)
  );
  sky130_fd_sc_hd__a21oi_1 _472_ (
    .A1(b[0]),
    .A2(_074_),
    .B1(a[0]),
    .Y(_201_)
  );
  sky130_fd_sc_hd__nand2_1 _473_ (
    .A(result[0]),
    .B(_082_),
    .Y(_202_)
  );
  sky130_fd_sc_hd__o21ai_0 _474_ (
    .A1(_082_),
    .A2(_201_),
    .B1(_202_),
    .Y(_018_)
  );
  sky130_fd_sc_hd__a21oi_1 _475_ (
    .A1(b[1]),
    .A2(_074_),
    .B1(a[1]),
    .Y(_203_)
  );
  sky130_fd_sc_hd__nand2_1 _476_ (
    .A(result[1]),
    .B(_082_),
    .Y(_204_)
  );
  sky130_fd_sc_hd__o21ai_0 _477_ (
    .A1(_082_),
    .A2(_203_),
    .B1(_204_),
    .Y(_019_)
  );
  sky130_fd_sc_hd__a21oi_1 _478_ (
    .A1(b[2]),
    .A2(_074_),
    .B1(a[2]),
    .Y(_205_)
  );
  sky130_fd_sc_hd__nand2_1 _479_ (
    .A(result[2]),
    .B(_082_),
    .Y(_206_)
  );
  sky130_fd_sc_hd__o21ai_0 _480_ (
    .A1(_082_),
    .A2(_205_),
    .B1(_206_),
    .Y(_020_)
  );
  sky130_fd_sc_hd__a21oi_1 _481_ (
    .A1(b[3]),
    .A2(_074_),
    .B1(a[3]),
    .Y(_207_)
  );
  sky130_fd_sc_hd__nand2_1 _482_ (
    .A(result[3]),
    .B(_082_),
    .Y(_208_)
  );
  sky130_fd_sc_hd__o21ai_0 _483_ (
    .A1(_082_),
    .A2(_207_),
    .B1(_208_),
    .Y(_021_)
  );
  sky130_fd_sc_hd__a21oi_1 _484_ (
    .A1(b[4]),
    .A2(_074_),
    .B1(a[4]),
    .Y(_209_)
  );
  sky130_fd_sc_hd__nand2_1 _485_ (
    .A(result[4]),
    .B(_082_),
    .Y(_210_)
  );
  sky130_fd_sc_hd__o21ai_0 _486_ (
    .A1(_082_),
    .A2(_209_),
    .B1(_210_),
    .Y(_022_)
  );
  sky130_fd_sc_hd__a21oi_1 _487_ (
    .A1(b[5]),
    .A2(_074_),
    .B1(a[5]),
    .Y(_211_)
  );
  sky130_fd_sc_hd__nand2_1 _488_ (
    .A(result[5]),
    .B(_082_),
    .Y(_212_)
  );
  sky130_fd_sc_hd__o21ai_0 _489_ (
    .A1(_082_),
    .A2(_211_),
    .B1(_212_),
    .Y(_023_)
  );
  sky130_fd_sc_hd__a21oi_1 _490_ (
    .A1(b[6]),
    .A2(_074_),
    .B1(a[6]),
    .Y(_213_)
  );
  sky130_fd_sc_hd__nand2_1 _491_ (
    .A(result[6]),
    .B(_082_),
    .Y(_214_)
  );
  sky130_fd_sc_hd__o21ai_0 _492_ (
    .A1(_082_),
    .A2(_213_),
    .B1(_214_),
    .Y(_024_)
  );
  sky130_fd_sc_hd__a21oi_1 _493_ (
    .A1(b[7]),
    .A2(_074_),
    .B1(a[7]),
    .Y(_215_)
  );
  sky130_fd_sc_hd__nand2_1 _494_ (
    .A(result[7]),
    .B(_082_),
    .Y(_216_)
  );
  sky130_fd_sc_hd__o21ai_0 _495_ (
    .A1(_082_),
    .A2(_215_),
    .B1(_216_),
    .Y(_025_)
  );
  sky130_fd_sc_hd__a21oi_1 _496_ (
    .A1(b[8]),
    .A2(_074_),
    .B1(a[8]),
    .Y(_217_)
  );
  sky130_fd_sc_hd__nand2_1 _497_ (
    .A(result[8]),
    .B(_082_),
    .Y(_218_)
  );
  sky130_fd_sc_hd__o21ai_0 _498_ (
    .A1(_082_),
    .A2(_217_),
    .B1(_218_),
    .Y(_026_)
  );
  sky130_fd_sc_hd__a21oi_1 _499_ (
    .A1(b[9]),
    .A2(_074_),
    .B1(a[9]),
    .Y(_219_)
  );
  sky130_fd_sc_hd__nand2_1 _500_ (
    .A(result[9]),
    .B(_082_),
    .Y(_220_)
  );
  sky130_fd_sc_hd__o21ai_0 _501_ (
    .A1(_082_),
    .A2(_219_),
    .B1(_220_),
    .Y(_027_)
  );
  sky130_fd_sc_hd__a21oi_1 _502_ (
    .A1(b[10]),
    .A2(_074_),
    .B1(a[10]),
    .Y(_221_)
  );
  sky130_fd_sc_hd__nand2_1 _503_ (
    .A(result[10]),
    .B(_082_),
    .Y(_222_)
  );
  sky130_fd_sc_hd__o21ai_0 _504_ (
    .A1(_082_),
    .A2(_221_),
    .B1(_222_),
    .Y(_028_)
  );
  sky130_fd_sc_hd__a21oi_1 _505_ (
    .A1(b[11]),
    .A2(_074_),
    .B1(a[11]),
    .Y(_223_)
  );
  sky130_fd_sc_hd__nand2_1 _506_ (
    .A(result[11]),
    .B(_082_),
    .Y(_224_)
  );
  sky130_fd_sc_hd__o21ai_0 _507_ (
    .A1(_082_),
    .A2(_223_),
    .B1(_224_),
    .Y(_029_)
  );
  sky130_fd_sc_hd__a21oi_1 _508_ (
    .A1(b[12]),
    .A2(_074_),
    .B1(a[12]),
    .Y(_225_)
  );
  sky130_fd_sc_hd__nand2_1 _509_ (
    .A(result[12]),
    .B(_082_),
    .Y(_226_)
  );
  sky130_fd_sc_hd__o21ai_0 _510_ (
    .A1(_082_),
    .A2(_225_),
    .B1(_226_),
    .Y(_030_)
  );
  sky130_fd_sc_hd__a21oi_1 _511_ (
    .A1(b[13]),
    .A2(_074_),
    .B1(a[13]),
    .Y(_227_)
  );
  sky130_fd_sc_hd__nand2_1 _512_ (
    .A(result[13]),
    .B(_082_),
    .Y(_228_)
  );
  sky130_fd_sc_hd__o21ai_0 _513_ (
    .A1(_082_),
    .A2(_227_),
    .B1(_228_),
    .Y(_031_)
  );
  sky130_fd_sc_hd__a21oi_1 _514_ (
    .A1(b[14]),
    .A2(_074_),
    .B1(a[14]),
    .Y(_229_)
  );
  sky130_fd_sc_hd__nand2_1 _515_ (
    .A(result[14]),
    .B(_082_),
    .Y(_230_)
  );
  sky130_fd_sc_hd__o21ai_0 _516_ (
    .A1(_082_),
    .A2(_229_),
    .B1(_230_),
    .Y(_032_)
  );
  sky130_fd_sc_hd__a21oi_1 _517_ (
    .A1(b[15]),
    .A2(_074_),
    .B1(a[15]),
    .Y(_231_)
  );
  sky130_fd_sc_hd__nand2_1 _518_ (
    .A(result[15]),
    .B(_082_),
    .Y(_232_)
  );
  sky130_fd_sc_hd__o21ai_0 _519_ (
    .A1(_082_),
    .A2(_231_),
    .B1(_232_),
    .Y(_033_)
  );
  sky130_fd_sc_hd__a21boi_0 _520_ (
    .A1(_081_),
    .A2(_137_),
    .B1_N(_000_),
    .Y(_233_)
  );
  sky130_fd_sc_hd__a21oi_1 _521_ (
    .A1(a_in[0]),
    .A2(_066_),
    .B1(_140_),
    .Y(_234_)
  );
  sky130_fd_sc_hd__mux2i_1 _522_ (
    .A0(_064_),
    .A1(_234_),
    .S(_233_),
    .Y(_034_)
  );
  sky130_fd_sc_hd__xnor2_1 _523_ (
    .A(_122_),
    .B(_139_),
    .Y(_235_)
  );
  sky130_fd_sc_hd__nor2_1 _524_ (
    .A(a_in[1]),
    .B(_067_),
    .Y(_236_)
  );
  sky130_fd_sc_hd__a21oi_1 _525_ (
    .A1(_067_),
    .A2(_235_),
    .B1(_236_),
    .Y(_237_)
  );
  sky130_fd_sc_hd__mux2_1 _526_ (
    .A0(a[1]),
    .A1(_237_),
    .S(_233_),
    .X(_035_)
  );
  sky130_fd_sc_hd__a21oi_1 _527_ (
    .A1(_122_),
    .A2(_139_),
    .B1(_121_),
    .Y(_238_)
  );
  sky130_fd_sc_hd__xor2_1 _528_ (
    .A(_118_),
    .B(_238_),
    .X(_239_)
  );
  sky130_fd_sc_hd__nor2_1 _529_ (
    .A(a_in[2]),
    .B(_067_),
    .Y(_240_)
  );
  sky130_fd_sc_hd__a21oi_1 _530_ (
    .A1(_067_),
    .A2(_239_),
    .B1(_240_),
    .Y(_241_)
  );
  sky130_fd_sc_hd__mux2_1 _531_ (
    .A0(a[2]),
    .A1(_241_),
    .S(_233_),
    .X(_036_)
  );
  sky130_fd_sc_hd__maj3_1 _532_ (
    .A(b[2]),
    .B(_051_),
    .C(_238_),
    .X(_242_)
  );
  sky130_fd_sc_hd__xnor2_1 _533_ (
    .A(_117_),
    .B(_242_),
    .Y(_243_)
  );
  sky130_fd_sc_hd__nand2_1 _534_ (
    .A(_067_),
    .B(_243_),
    .Y(_244_)
  );
  sky130_fd_sc_hd__o21ai_0 _535_ (
    .A1(a_in[3]),
    .A2(_067_),
    .B1(_244_),
    .Y(_245_)
  );
  sky130_fd_sc_hd__mux2i_1 _536_ (
    .A0(_053_),
    .A1(_245_),
    .S(_233_),
    .Y(_037_)
  );
  sky130_fd_sc_hd__maj3_1 _537_ (
    .A(b[3]),
    .B(_053_),
    .C(_242_),
    .X(_246_)
  );
  sky130_fd_sc_hd__xnor2_1 _538_ (
    .A(_114_),
    .B(_246_),
    .Y(_247_)
  );
  sky130_fd_sc_hd__nor2_1 _539_ (
    .A(a_in[4]),
    .B(_067_),
    .Y(_248_)
  );
  sky130_fd_sc_hd__a21oi_1 _540_ (
    .A1(_067_),
    .A2(_247_),
    .B1(_248_),
    .Y(_249_)
  );
  sky130_fd_sc_hd__mux2_1 _541_ (
    .A0(a[4]),
    .A1(_249_),
    .S(_233_),
    .X(_038_)
  );
  sky130_fd_sc_hd__o21ai_0 _542_ (
    .A1(_114_),
    .A2(_246_),
    .B1(_113_),
    .Y(_250_)
  );
  sky130_fd_sc_hd__xor2_1 _543_ (
    .A(_111_),
    .B(_250_),
    .X(_251_)
  );
  sky130_fd_sc_hd__nor2_1 _544_ (
    .A(_066_),
    .B(_251_),
    .Y(_252_)
  );
  sky130_fd_sc_hd__a21oi_1 _545_ (
    .A1(a_in[5]),
    .A2(_066_),
    .B1(_252_),
    .Y(_253_)
  );
  sky130_fd_sc_hd__mux2i_1 _546_ (
    .A0(_054_),
    .A1(_253_),
    .S(_233_),
    .Y(_039_)
  );
  sky130_fd_sc_hd__maj3_1 _547_ (
    .A(b[5]),
    .B(_054_),
    .C(_113_),
    .X(_254_)
  );
  sky130_fd_sc_hd__o21ai_0 _548_ (
    .A1(_115_),
    .A2(_246_),
    .B1(_254_),
    .Y(_255_)
  );
  sky130_fd_sc_hd__o21ai_0 _549_ (
    .A1(_109_),
    .A2(_255_),
    .B1(_067_),
    .Y(_256_)
  );
  sky130_fd_sc_hd__a21oi_1 _550_ (
    .A1(_109_),
    .A2(_255_),
    .B1(_256_),
    .Y(_257_)
  );
  sky130_fd_sc_hd__a21oi_1 _551_ (
    .A1(a_in[6]),
    .A2(_066_),
    .B1(_257_),
    .Y(_258_)
  );
  sky130_fd_sc_hd__mux2i_1 _552_ (
    .A0(_055_),
    .A1(_258_),
    .S(_233_),
    .Y(_040_)
  );
  sky130_fd_sc_hd__a21oi_1 _553_ (
    .A1(_109_),
    .A2(_255_),
    .B1(_108_),
    .Y(_259_)
  );
  sky130_fd_sc_hd__xnor2_1 _554_ (
    .A(_106_),
    .B(_259_),
    .Y(_260_)
  );
  sky130_fd_sc_hd__nand2_1 _555_ (
    .A(a_in[7]),
    .B(_066_),
    .Y(_261_)
  );
  sky130_fd_sc_hd__o21ai_0 _556_ (
    .A1(_066_),
    .A2(_260_),
    .B1(_261_),
    .Y(_262_)
  );
  sky130_fd_sc_hd__mux2_1 _557_ (
    .A0(a[7]),
    .A1(_262_),
    .S(_233_),
    .X(_041_)
  );
  sky130_fd_sc_hd__nand2_1 _558_ (
    .A(a_in[8]),
    .B(_066_),
    .Y(_263_)
  );
  sky130_fd_sc_hd__nor2_1 _559_ (
    .A(_110_),
    .B(_254_),
    .Y(_264_)
  );
  sky130_fd_sc_hd__a211oi_1 _560_ (
    .A1(_105_),
    .A2(_108_),
    .B1(_264_),
    .C1(_104_),
    .Y(_265_)
  );
  sky130_fd_sc_hd__o21ai_0 _561_ (
    .A1(_116_),
    .A2(_246_),
    .B1(_265_),
    .Y(_266_)
  );
  sky130_fd_sc_hd__and2_0 _562_ (
    .A(_100_),
    .B(_266_),
    .X(_267_)
  );
  sky130_fd_sc_hd__o21ai_0 _563_ (
    .A1(_100_),
    .A2(_266_),
    .B1(_067_),
    .Y(_268_)
  );
  sky130_fd_sc_hd__o21ai_0 _564_ (
    .A1(_267_),
    .A2(_268_),
    .B1(_263_),
    .Y(_269_)
  );
  sky130_fd_sc_hd__mux2_1 _565_ (
    .A0(a[8]),
    .A1(_269_),
    .S(_233_),
    .X(_042_)
  );
  sky130_fd_sc_hd__nor2_1 _566_ (
    .A(_099_),
    .B(_267_),
    .Y(_270_)
  );
  sky130_fd_sc_hd__o21ai_0 _567_ (
    .A1(_097_),
    .A2(_270_),
    .B1(_067_),
    .Y(_271_)
  );
  sky130_fd_sc_hd__a21oi_1 _568_ (
    .A1(_097_),
    .A2(_270_),
    .B1(_271_),
    .Y(_272_)
  );
  sky130_fd_sc_hd__a21oi_1 _569_ (
    .A1(a_in[9]),
    .A2(_066_),
    .B1(_272_),
    .Y(_273_)
  );
  sky130_fd_sc_hd__mux2i_1 _570_ (
    .A0(_057_),
    .A1(_273_),
    .S(_233_),
    .Y(_043_)
  );
  sky130_fd_sc_hd__maj3_1 _571_ (
    .A(_056_),
    .B(a[9]),
    .C(_099_),
    .X(_274_)
  );
  sky130_fd_sc_hd__a21o_1 _572_ (
    .A1(_101_),
    .A2(_266_),
    .B1(_274_),
    .X(_275_)
  );
  sky130_fd_sc_hd__nor2_1 _573_ (
    .A(_093_),
    .B(_275_),
    .Y(_276_)
  );
  sky130_fd_sc_hd__nand2_1 _574_ (
    .A(_093_),
    .B(_275_),
    .Y(_277_)
  );
  sky130_fd_sc_hd__nor2_1 _575_ (
    .A(_066_),
    .B(_276_),
    .Y(_278_)
  );
  sky130_fd_sc_hd__a22oi_1 _576_ (
    .A1(a_in[10]),
    .A2(_066_),
    .B1(_277_),
    .B2(_278_),
    .Y(_279_)
  );
  sky130_fd_sc_hd__mux2i_1 _577_ (
    .A0(_059_),
    .A1(_279_),
    .S(_233_),
    .Y(_044_)
  );
  sky130_fd_sc_hd__o21ai_0 _578_ (
    .A1(b[10]),
    .A2(_059_),
    .B1(_277_),
    .Y(_280_)
  );
  sky130_fd_sc_hd__xnor2_1 _579_ (
    .A(_096_),
    .B(_280_),
    .Y(_281_)
  );
  sky130_fd_sc_hd__nand2_1 _580_ (
    .A(a_in[11]),
    .B(_066_),
    .Y(_282_)
  );
  sky130_fd_sc_hd__o21ai_0 _581_ (
    .A1(_066_),
    .A2(_281_),
    .B1(_282_),
    .Y(_283_)
  );
  sky130_fd_sc_hd__mux2_1 _582_ (
    .A0(a[11]),
    .A1(_283_),
    .S(_233_),
    .X(_045_)
  );
  sky130_fd_sc_hd__nand3_1 _583_ (
    .A(_093_),
    .B(_096_),
    .C(_274_),
    .Y(_284_)
  );
  sky130_fd_sc_hd__nand3_1 _584_ (
    .A(_058_),
    .B(a[10]),
    .C(_096_),
    .Y(_285_)
  );
  sky130_fd_sc_hd__nand3_1 _585_ (
    .A(_095_),
    .B(_284_),
    .C(_285_),
    .Y(_286_)
  );
  sky130_fd_sc_hd__a21oi_1 _586_ (
    .A1(_102_),
    .A2(_266_),
    .B1(_286_),
    .Y(_287_)
  );
  sky130_fd_sc_hd__o21ai_0 _587_ (
    .A1(_091_),
    .A2(_287_),
    .B1(_067_),
    .Y(_288_)
  );
  sky130_fd_sc_hd__a21oi_1 _588_ (
    .A1(_091_),
    .A2(_287_),
    .B1(_288_),
    .Y(_289_)
  );
  sky130_fd_sc_hd__a21oi_1 _589_ (
    .A1(a_in[12]),
    .A2(_066_),
    .B1(_289_),
    .Y(_290_)
  );
  sky130_fd_sc_hd__mux2i_1 _590_ (
    .A0(_061_),
    .A1(_290_),
    .S(_233_),
    .Y(_046_)
  );
  sky130_fd_sc_hd__o21ai_0 _591_ (
    .A1(_091_),
    .A2(_287_),
    .B1(_090_),
    .Y(_291_)
  );
  sky130_fd_sc_hd__xor2_1 _592_ (
    .A(_088_),
    .B(_291_),
    .X(_292_)
  );
  sky130_fd_sc_hd__nand2_1 _593_ (
    .A(a_in[13]),
    .B(_066_),
    .Y(_293_)
  );
  sky130_fd_sc_hd__o21ai_0 _594_ (
    .A1(_066_),
    .A2(_292_),
    .B1(_293_),
    .Y(_294_)
  );
  sky130_fd_sc_hd__mux2_1 _595_ (
    .A0(a[13]),
    .A1(_294_),
    .S(_233_),
    .X(_047_)
  );
  sky130_fd_sc_hd__o221ai_1 _596_ (
    .A1(_088_),
    .A2(_090_),
    .B1(_092_),
    .B2(_287_),
    .C1(_087_),
    .Y(_295_)
  );
  sky130_fd_sc_hd__o21ai_0 _597_ (
    .A1(_085_),
    .A2(_295_),
    .B1(_067_),
    .Y(_296_)
  );
  sky130_fd_sc_hd__a21oi_1 _598_ (
    .A1(_085_),
    .A2(_295_),
    .B1(_296_),
    .Y(_297_)
  );
  sky130_fd_sc_hd__a21oi_1 _599_ (
    .A1(a_in[14]),
    .A2(_066_),
    .B1(_297_),
    .Y(_298_)
  );
  sky130_fd_sc_hd__mux2i_1 _600_ (
    .A0(_062_),
    .A1(_298_),
    .S(_233_),
    .Y(_048_)
  );
  sky130_fd_sc_hd__a21oi_1 _601_ (
    .A1(_085_),
    .A2(_295_),
    .B1(_084_),
    .Y(_299_)
  );
  sky130_fd_sc_hd__xor2_1 _602_ (
    .A(_083_),
    .B(_299_),
    .X(_300_)
  );
  sky130_fd_sc_hd__nand2_1 _603_ (
    .A(a_in[15]),
    .B(_066_),
    .Y(_301_)
  );
  sky130_fd_sc_hd__o21ai_0 _604_ (
    .A1(_066_),
    .A2(_300_),
    .B1(_301_),
    .Y(_302_)
  );
  sky130_fd_sc_hd__mux2_1 _605_ (
    .A0(a[15]),
    .A1(_302_),
    .S(_233_),
    .X(_049_)
  );
  sky130_fd_sc_hd__dfrtp_1 _606_ (
    .CLK(clk),
    .D(_002_),
    .Q(b[0]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _607_ (
    .CLK(clk),
    .D(_003_),
    .Q(b[1]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _608_ (
    .CLK(clk),
    .D(_004_),
    .Q(b[2]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _609_ (
    .CLK(clk),
    .D(_005_),
    .Q(b[3]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _610_ (
    .CLK(clk),
    .D(_006_),
    .Q(b[4]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _611_ (
    .CLK(clk),
    .D(_007_),
    .Q(b[5]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _612_ (
    .CLK(clk),
    .D(_008_),
    .Q(b[6]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _613_ (
    .CLK(clk),
    .D(_009_),
    .Q(b[7]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _614_ (
    .CLK(clk),
    .D(_010_),
    .Q(b[8]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _615_ (
    .CLK(clk),
    .D(_011_),
    .Q(b[9]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _616_ (
    .CLK(clk),
    .D(_012_),
    .Q(b[10]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _617_ (
    .CLK(clk),
    .D(_013_),
    .Q(b[11]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _618_ (
    .CLK(clk),
    .D(_014_),
    .Q(b[12]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _619_ (
    .CLK(clk),
    .D(_015_),
    .Q(b[13]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _620_ (
    .CLK(clk),
    .D(_016_),
    .Q(b[14]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _621_ (
    .CLK(clk),
    .D(_017_),
    .Q(b[15]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _622_ (
    .CLK(clk),
    .D(_001_),
    .Q(done),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _623_ (
    .CLK(clk),
    .D(_018_),
    .Q(result[0]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _624_ (
    .CLK(clk),
    .D(_019_),
    .Q(result[1]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _625_ (
    .CLK(clk),
    .D(_020_),
    .Q(result[2]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _626_ (
    .CLK(clk),
    .D(_021_),
    .Q(result[3]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _627_ (
    .CLK(clk),
    .D(_022_),
    .Q(result[4]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _628_ (
    .CLK(clk),
    .D(_023_),
    .Q(result[5]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _629_ (
    .CLK(clk),
    .D(_024_),
    .Q(result[6]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _630_ (
    .CLK(clk),
    .D(_025_),
    .Q(result[7]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _631_ (
    .CLK(clk),
    .D(_026_),
    .Q(result[8]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _632_ (
    .CLK(clk),
    .D(_027_),
    .Q(result[9]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _633_ (
    .CLK(clk),
    .D(_028_),
    .Q(result[10]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _634_ (
    .CLK(clk),
    .D(_029_),
    .Q(result[11]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _635_ (
    .CLK(clk),
    .D(_030_),
    .Q(result[12]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _636_ (
    .CLK(clk),
    .D(_031_),
    .Q(result[13]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _637_ (
    .CLK(clk),
    .D(_032_),
    .Q(result[14]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _638_ (
    .CLK(clk),
    .D(_033_),
    .Q(result[15]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _639_ (
    .CLK(clk),
    .D(_034_),
    .Q(a[0]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _640_ (
    .CLK(clk),
    .D(_035_),
    .Q(a[1]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _641_ (
    .CLK(clk),
    .D(_036_),
    .Q(a[2]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _642_ (
    .CLK(clk),
    .D(_037_),
    .Q(a[3]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _643_ (
    .CLK(clk),
    .D(_038_),
    .Q(a[4]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _644_ (
    .CLK(clk),
    .D(_039_),
    .Q(a[5]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _645_ (
    .CLK(clk),
    .D(_040_),
    .Q(a[6]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _646_ (
    .CLK(clk),
    .D(_041_),
    .Q(a[7]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _647_ (
    .CLK(clk),
    .D(_042_),
    .Q(a[8]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _648_ (
    .CLK(clk),
    .D(_043_),
    .Q(a[9]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _649_ (
    .CLK(clk),
    .D(_044_),
    .Q(a[10]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _650_ (
    .CLK(clk),
    .D(_045_),
    .Q(a[11]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _651_ (
    .CLK(clk),
    .D(_046_),
    .Q(a[12]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _652_ (
    .CLK(clk),
    .D(_047_),
    .Q(a[13]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _653_ (
    .CLK(clk),
    .D(_048_),
    .Q(a[14]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _654_ (
    .CLK(clk),
    .D(_049_),
    .Q(a[15]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _655_ (
    .CLK(clk),
    .D(_000_),
    .Q(busy),
    .RESET_B(rst_n)
  );
endmodule
