#!/usr/bin/env python3
"""Generate `examples/drc/example.gds`: a small sky130 layout with two
seeded rule violations plus one clean shape, used as the worked example for
`klt drc` (see `docs/cli/drc.md`).

Run from the repo root:

    uv run python3 examples/drc/generate.py

Regenerates both `examples/drc/example.gds` (byte-reproducibly -- the GDS2
wall-clock write timestamps are suppressed, #320) and its companion
`examples/drc/example.drc.json` (`run_drc`'s report against the curated
sky130 deck, i.e. exactly what `klt drc --deck sky130 --format json` prints
for that file).

The `"provenance"` block is stripped before the JSON is written: its
`klt_version`/`klayout_version` fields are environment-dependent, so they
are not part of the fixture's contract (the block's own shape is exercised
by `tests/test_drc.py::test_json_contract` instead). That is why the JSON
must be regenerated by running *this script*, and never by redirecting
`klt drc --format json` into the fixture -- the redirect keeps `provenance`
and the drift guard `tests/test_drc.py::test_example_gds_matches_committed_json`
then rejects the result. `examples/dogbone-terminal/generate.py` follows the
same convention for its own companion fixtures.
"""

import json
import os

import klayout.db as kdb

from klayout_tools.drc import run_drc

#: The deck the committed report is generated against.
DECK = "sky130"


def build() -> kdb.Layout:
    layout = kdb.Layout()
    top = layout.create_cell("TOP")

    # poly.drawing (66/20): a bar 100 dbu (0.1 um) wide -- narrower than the
    # poly.width.1 threshold of 150 dbu (0.15 um) -> one seeded violation.
    poly = layout.layer(66, 20)
    layout.set_info(poly, kdb.LayerInfo(66, 20, "poly.drawing"))
    top.shapes(poly).insert(kdb.Box(0, 0, 100, 2000))

    # diff.drawing (65/20) enclosing licon1.drawing (66/44) by only 10 dbu
    # on each side -- less than the diff.enclosing.licon.1 threshold of
    # 40 dbu (0.04 um) -> a second seeded violation.
    diff = layout.layer(65, 20)
    layout.set_info(diff, kdb.LayerInfo(65, 20, "diff.drawing"))
    licon = layout.layer(66, 44)
    layout.set_info(licon, kdb.LayerInfo(66, 44, "licon1.drawing"))
    top.shapes(diff).insert(kdb.Box(3000, 0, 3200, 200))
    top.shapes(licon).insert(kdb.Box(3010, 10, 3190, 190))

    # met1.drawing (68/20): a clean, wide bar -- passes every rule.
    met1 = layout.layer(68, 20)
    layout.set_info(met1, kdb.LayerInfo(68, 20, "met1.drawing"))
    top.shapes(met1).insert(kdb.Box(0, 3000, 2000, 3300))

    return layout


def build_example(out_dir: str) -> tuple[str, str]:
    """Write `example.gds` + `example.drc.json` into `out_dir` and return
    their paths."""
    gds_path = os.path.join(out_dir, "example.gds")
    write_options = kdb.SaveLayoutOptions()
    write_options.gds2_write_timestamps = False  # reproducible bytes (#320)
    build().write(gds_path, write_options)

    report = run_drc(os.path.relpath(gds_path), DECK)
    report.pop("provenance", None)  # environment-dependent, stripped (see
    # this module's docstring)

    json_path = os.path.join(out_dir, "example.drc.json")
    with open(json_path, "w") as f:
        json.dump(report, f, indent=2)
        f.write("\n")

    return gds_path, json_path


def main() -> None:
    out_dir = os.path.dirname(os.path.abspath(__file__))
    for path in build_example(out_dir):
        print(f"wrote {path}")


if __name__ == "__main__":
    main()
