"""Cross-validation of `klt mom`'s full-wave S-parameters against an
external FEM solver (issue #895, Phase 2c of the Method-of-Moments epic
#701).

Two solvers, one benchmark geometry -- the canonical two-wire transmission
line `tests/test_mom_fullwave_validation.py` and
`tests/test_mom_ports_validation.py` already validate against closed forms:

- **`klt mom`** (`native/mom/src/fullwave.rs`, via `klayout_tools.mom.run_mom`)
  -- the retarded-kernel thin-wire partial-impedance MoM this repo owns.
- **`scripts/research/mom_external_fem_crossval.py`** -- a 2-D finite-element
  cross-section solve via `scikit-fem`, an independently-developed,
  BSD-licensed FEM library this repo does not author. See that module's
  own docstring for the full method and why it was chosen as the
  "external MoM/FEM solver" the epic's Phase 0 reality-grounding section
  calls for.

Both solvers ultimately reduce the geometry to a uniform-TEM-line
`Z0(omega)`/`gamma(omega)` pair and feed it through the *same* ABCD
(chain-parameter) cascade + de-embedding formalism (`fullwave.rs`'s
`line_abcd`/`abcd_to_s`, ported line-for-line to
`mom_external_fem_crossval.py`'s functions of the same name) -- so what is
actually being cross-checked is each solver's own path to `Z0`/`gamma`:
`klt mom`'s retarded-kernel point-collocation MoM (series impedance) plus
panelized electrostatic BEM (shunt capacitance), vs this module's bilinear-
quad FEM energy-method solve of the conductor cross-section (both `L'` and
`C'` independently, not one inferred from the other via the TEM identity).

**Methodology**: same benchmark geometry given to both solvers (geometry,
frequency, ports, reference impedance -- see the `WIDTH_UM`/etc. constants
below), same
ABCD/de-embedding formalism, agreement measured directly on the reported
complex S-parameters. Tolerances below are generous relative to the
measured agreement (recorded in `docs/design/mom-external-crossval.md`,
regenerated by this file's own printed output under `--capture=tee-sys`) --
loose enough to tolerate the FEM solver's own open-boundary truncation and
`klt mom`'s own MVP approximations (see each module's docs), tight enough
that a genuine regression in either solver's full-wave/port math would
fail one of the assertions below.

Requires both the `klt_mom_native` Rust extension (`--group mom`) and the
`numpy`/`scikit-fem` external-FEM dependencies (`--extra mom-crossval`);
this module skips itself, with a clear reason, when either is absent (the
same graceful-skip discipline `test_mom_ports_validation.py` uses for the
native extension alone).
"""

from __future__ import annotations

import cmath
import json
import math
import sys
from pathlib import Path

import klayout.db as kdb
import pytest

pytest.importorskip(
    "klt_mom_native",
    reason=(
        "klt_mom_native is not built -- run `maturin develop --release` in "
        "native/mom/ (see docs/cli/mom.md#building-the-native-extension)"
    ),
)
pytest.importorskip(
    "skfem",
    reason=(
        "scikit-fem is not installed -- run `uv sync --extra mom-crossval` "
        "(see scripts/research/mom_external_fem_crossval.py's docstring)"
    ),
)

from klayout_tools.mom import run_mom  # noqa: E402

SCRIPTS_DIR = Path(__file__).parent.parent / "scripts" / "research"
sys.path.insert(0, str(SCRIPTS_DIR))

import mom_external_fem_crossval as fem  # noqa: E402

MU0_H_PER_M = 4.0 * math.pi * 1e-7
EPS0_F_PER_M = 8.854_187_812_8e-12
ETA0_OHM = math.sqrt(MU0_H_PER_M / EPS0_F_PER_M)
C0_M_PER_S = 299_792_458.0

# --- the shared benchmark -- same fixture test_mom_fullwave_validation.py's
# characteristic-impedance test and test_mom_ports_validation.py's matched-line
# test already use: 500um two-wire line, 2x2um square bars, 40um separation.
WIDTH_UM = 2.0
HEIGHT_UM = 2.0
SEPARATION_UM = 40.0
FREQUENCY_HZ = 1.0e9
REFERENCE_IMPEDANCE_OHM = 50.0  # standard RF convention; solver-independent


def _dbu(value_um: float) -> int:
    return int(round(value_um / 0.001))


def _write_loop(path, length_um: float) -> None:
    layout = kdb.Layout()
    layout.dbu = 0.001
    top = layout.create_cell("TOP")
    top.shapes(layout.layer(1, 0)).insert(
        kdb.Box.new(0, 0, _dbu(length_um), _dbu(WIDTH_UM))
    )
    top.shapes(layout.layer(2, 0)).insert(
        kdb.Box.new(
            0,
            _dbu(SEPARATION_UM),
            _dbu(length_um),
            _dbu(SEPARATION_UM + WIDTH_UM),
        )
    )
    layout.write(str(path))


def _run_klt_mom(tmp_path_factory, name, *, length_um, ports):
    root = tmp_path_factory.mktemp("mom-external-crossval")
    gds = root / f"{name}.gds"
    _write_loop(gds, length_um)
    spec = root / f"{name}.mom.json"
    spec.write_text(
        json.dumps(
            {
                "background_permittivity": 1.0,
                "panel_size_um": 2.0,
                "frequencies_hz": [FREQUENCY_HZ],
                "segment_size_um": 5.0,
                "ports": ports,
                "stackup": [
                    {
                        "layer": "1/0",
                        "conductor": "go",
                        "z0_um": 0.0,
                        "z1_um": HEIGHT_UM,
                    },
                    {
                        "layer": "2/0",
                        "conductor": "return",
                        "z0_um": 0.0,
                        "z1_um": HEIGHT_UM,
                    },
                ],
            }
        )
    )
    report = run_mom(str(gds), str(spec))
    return report["full_wave_sweep"][0]


def _run_fem(*, axis_hi_um, port_positions_um):
    return fem.s_parameters_two_wire_line(
        width_um=WIDTH_UM,
        height_um=HEIGHT_UM,
        separation_um=SEPARATION_UM,
        axis_lo_um=0.0,
        axis_hi_um=axis_hi_um,
        frequency_hz=FREQUENCY_HZ,
        port_positions_um=port_positions_um,
        reference_impedance_ohm=(REFERENCE_IMPEDANCE_OHM, REFERENCE_IMPEDANCE_OHM),
    )


def _complex(d, prefix):
    return complex(d[f"{prefix}_real"], d[f"{prefix}_imag"])


# --- 1. the FEM solver's own credibility: RLGC vs the two-wire closed form ---


def test_fem_rlgc_matches_two_wire_closed_form():
    """Sanity check on the external solver itself, before using it as an
    oracle: its independently-computed `L'`/`C'` should each land near the
    same closed-form two-wire-line oracle
    `tests/test_mom_fullwave_validation.py` already validates `klt mom`
    against (`Z0 = eta0/pi * acosh(D/(2a))`, `a` the equal-area-circle
    radius -- the shape-substituted oracle; this FEM solver meshes the
    actual square cross-section, so it is *not* itself subject to that
    substitution, hence the residual below is a fair measure of the
    oracle's own shape-substitution error plus this solver's open-boundary
    truncation, not a FEM implementation bug)."""
    c_prime, l_prime, node_count = fem.solve_rlgc_per_length(
        WIDTH_UM, HEIGHT_UM, SEPARATION_UM
    )
    a_eq_m = math.sqrt(WIDTH_UM * HEIGHT_UM * 1e-12 / math.pi)
    sep_m = SEPARATION_UM * 1e-6
    z0_oracle = ETA0_OHM / math.pi * math.acosh(sep_m / (2.0 * a_eq_m))
    l_oracle = MU0_H_PER_M / math.pi * math.acosh(sep_m / (2.0 * a_eq_m))
    c_oracle = 1.0 / (C0_M_PER_S * z0_oracle)

    z0_fem = math.sqrt(l_prime / c_prime)
    lc_product = l_prime * c_prime
    mu0_eps0 = MU0_H_PER_M * EPS0_F_PER_M
    tem_self_consistency_err_pct = (lc_product - mu0_eps0) / mu0_eps0 * 100

    print(
        f"\nFEM cross-section RLGC (nodes={node_count}): "
        f"C'={c_prime * 1e12:.6f} pF/m (oracle {c_oracle * 1e12:.6f}, "
        f"err {(c_prime - c_oracle) / c_oracle * 100:+.3f}%)  "
        f"L'={l_prime * 1e9:.6f} nH/m (oracle {l_oracle * 1e9:.6f}, "
        f"err {(l_prime - l_oracle) / l_oracle * 100:+.3f}%)  "
        f"Z0={z0_fem:.4f} ohm (oracle {z0_oracle:.4f})  "
        f"L'C'={lc_product:.6e} vs mu0*eps0={mu0_eps0:.6e} "
        f"(TEM self-consistency err "
        f"{tem_self_consistency_err_pct:+.3f}%)"
    )

    assert abs(c_prime - c_oracle) / c_oracle < 0.05, (
        "C' should be within 5% of the closed form"
    )
    assert abs(l_prime - l_oracle) / l_oracle < 0.10, (
        "L' should be within 10% of the closed form"
    )
    # Independently-solved L' and C' should still roughly satisfy the exact
    # TEM identity for a lossless vacuum background -- a strong internal
    # consistency check on the FEM solve itself (both solves share the same
    # mesh/domain, so most of the open-boundary truncation error cancels).
    assert abs(lc_product - mu0_eps0) / mu0_eps0 < 0.15


# --- 2. the acceptance criterion: klt mom vs the external FEM solver --------


def test_klt_mom_and_external_fem_solver_agree_on_matched_line_s_parameters(
    tmp_path_factory,
):
    """The core cross-validation: same benchmark, ports at both physical
    ends (the matched-line case `test_mom_ports_validation.py` also
    exercises against the closed form), reference impedance fixed at the
    standard 50 ohm (deliberately *not* tied to either solver's own derived
    Z0, so a Z0 disagreement between solvers shows up as an S11
    disagreement, not just an S21 phase disagreement)."""
    length_um = 500.0
    ports = [
        {"position_um": 0.0, "reference_impedance_ohm": REFERENCE_IMPEDANCE_OHM},
        {"position_um": length_um, "reference_impedance_ohm": REFERENCE_IMPEDANCE_OHM},
    ]
    mom_point = _run_klt_mom(
        tmp_path_factory, "matched", length_um=length_um, ports=ports
    )
    mom_s = mom_point["s_parameters"]
    fem_result = _run_fem(axis_hi_um=length_um, port_positions_um=(0.0, length_um))
    fem_s = fem_result["s_parameters"]

    mom_s11, mom_s21 = _complex(mom_s, "s11"), _complex(mom_s, "s21")
    fem_s11, fem_s21 = _complex(fem_s, "s11"), _complex(fem_s, "s21")

    s21_rel_err = abs(fem_s21 - mom_s21) / abs(mom_s21)
    s11_abs_diff = abs(abs(fem_s11) - abs(mom_s11))
    phase_diff_rad = abs(cmath.phase(fem_s21) - cmath.phase(mom_s21))

    print(
        f"\nmatched line ({length_um}um, {REFERENCE_IMPEDANCE_OHM} ohm ref): "
        f"klt mom S11={mom_s11:.6f} (|S11|={abs(mom_s11):.6f})  "
        f"external FEM S11={fem_s11:.6f} (|S11|={abs(fem_s11):.6f})  "
        f"|S11| diff={s11_abs_diff:.6f}\n"
        f"klt mom S21={mom_s21:.6f} (|S21|={abs(mom_s21):.6f}, "
        f"phase={cmath.phase(mom_s21):.6f} rad)  "
        f"external FEM S21={fem_s21:.6f} (|S21|={abs(fem_s21):.6f}, "
        f"phase={cmath.phase(fem_s21):.6f} rad)  "
        f"S21 rel.err={s21_rel_err * 100:.4f}%  phase diff={phase_diff_rad:.6f} rad\n"
        f"klt mom Z0={mom_point['characteristic_impedance_real_ohm']:.4f} ohm  "
        f"external FEM Z0={fem_result['characteristic_impedance_ohm'].real:.4f} ohm  "
        f"C'={fem_result['c_prime_f_per_m'] * 1e12:.4f} pF/m  "
        f"L'={fem_result['l_prime_h_per_m'] * 1e9:.4f} nH/m  "
        f"nodes={fem_result['node_count']}"
    )

    # Measured agreement (see docs/design/mom-external-crossval.md): S21
    # rel.err ~0.36%, |S11| abs diff ~0.0036, phase diff ~0.0036 rad --
    # tolerances below are ~5-8x that measured margin.
    assert s21_rel_err < 0.05, f"S21 rel.err {s21_rel_err * 100:.4f}% exceeds 5%"
    assert s11_abs_diff < 0.03, f"|S11| diff {s11_abs_diff:.6f} exceeds 0.03"
    assert phase_diff_rad < 0.02, (
        f"S21 phase diff {phase_diff_rad:.6f} rad exceeds 0.02 rad"
    )


def test_klt_mom_and_external_fem_solver_agree_after_de_embedding(tmp_path_factory):
    """Same cross-check, but with feed stubs on both sides and ports placed
    inward -- exercises the de-embedding path (`abcd_dut` cascade) on both
    solvers, not just the ports-at-the-ends identity reduction the test
    above covers. Same fixture `test_mom_ports_validation.py`'s
    `test_de_embedding_matches_the_dut_alone_closed_form` uses."""
    feed1_um, dut_um, feed2_um = 100.0, 500.0, 150.0
    total_um = feed1_um + dut_um + feed2_um
    ports = [
        {"position_um": feed1_um, "reference_impedance_ohm": REFERENCE_IMPEDANCE_OHM},
        {
            "position_um": feed1_um + dut_um,
            "reference_impedance_ohm": REFERENCE_IMPEDANCE_OHM,
        },
    ]
    mom_point = _run_klt_mom(
        tmp_path_factory, "deembed", length_um=total_um, ports=ports
    )
    mom_s = mom_point["s_parameters"]
    fem_result = _run_fem(
        axis_hi_um=total_um, port_positions_um=(feed1_um, feed1_um + dut_um)
    )
    fem_s = fem_result["s_parameters"]

    mom_s11, mom_s21 = _complex(mom_s, "s11"), _complex(mom_s, "s21")
    fem_s11, fem_s21 = _complex(fem_s, "s11"), _complex(fem_s, "s21")

    s21_rel_err = abs(fem_s21 - mom_s21) / abs(mom_s21)
    s11_abs_diff = abs(abs(fem_s11) - abs(mom_s11))

    print(
        f"\nde-embedded line (feed1={feed1_um}um dut={dut_um}um feed2={feed2_um}um): "
        f"klt mom S21={mom_s21:.6f} (|S21|={abs(mom_s21):.6f})  "
        f"external FEM S21={fem_s21:.6f} (|S21|={abs(fem_s21):.6f})  "
        f"S21 rel.err={s21_rel_err * 100:.4f}%  "
        f"|S11| diff={s11_abs_diff:.6f}"
    )

    # Same tolerance budget as the matched-line test above -- de-embedding
    # is closed-form ABCD algebra (identical on both solvers), so agreement
    # should not degrade materially versus the ports-at-the-ends case.
    assert s21_rel_err < 0.05, f"S21 rel.err {s21_rel_err * 100:.4f}% exceeds 5%"
    assert s11_abs_diff < 0.03, f"|S11| diff {s11_abs_diff:.6f} exceeds 0.03"
