import { PatchAntennaGalleryEntry } from "./PatchAntennaGalleryEntry";

/**
 * "Electromagnetics" gallery section (Epic #840 "real E&M results in the
 * browser", Phase 1c, issue #851) — wires Phase 1a's export format (#849)
 * and Phase 1b's `FieldViewer`/`WaveformViewer` integration (#850) into a
 * dedicated section of the landing page, one entry per validated geode-fem
 * benchmark, each carrying its own `ProvenancePanel`.
 *
 * **Benchmark count note (as of this issue, 2026-08-12):** the epic phase
 * description names "2-3 benchmarks (patch antenna, spiral inductor L/Q,
 * Mie sphere)". Only the patch-antenna benchmark has a real, committed
 * geode-fem export today (`examples/em/patch_antenna/patch_antenna.em-export.json`,
 * generated by #849's `examples/em/patch_antenna/generate.py` from an actual
 * solver run). Producing the spiral-inductor or Mie-sphere benchmarks
 * requires a real solve against a local geode-fem checkout (see that
 * script's own docstring and `docs/design/em-field-sim-spike.md`) — new
 * solver-data generation, not site-wiring, and out of scope for this issue
 * per "no illustrative/faked fields" (Acceptance Criteria #3): this section
 * intentionally ships with one real entry rather than synthesizing a second.
 * Adding a benchmark here is additive: give it its own `<Benchmark>Result` +
 * `<Benchmark>GalleryEntry` pair (see `PatchAntennaGalleryEntry`'s doc
 * comment) and list it below.
 */
export function EmGallerySection() {
  return (
    <section aria-label="Electromagnetics" className="mt-14" data-testid="em-gallery-section">
      <h2 className="mb-2 font-mono text-[1.3rem] text-cyan">Electromagnetics</h2>
      <p className="mb-5 max-w-[44rem] leading-[1.7] text-fog-dim">
        Real geode-fem field solves, browsable the same way as the layout gallery
        above. Every mesh, field overlay, and S-parameter curve here traces to a
        committed solver run — see each entry&rsquo;s provenance panel for the exact
        solver version, geometry, and solve parameters behind it.
      </p>

      <div className="flex flex-col gap-6">
        <PatchAntennaGalleryEntry />
      </div>
    </section>
  );
}
