//! `klt wave build` against an FST-format input trace
//! (`tests/fixtures/counter.fst`, stamped with a `"Generated by
//! VerilatedFst"` version string to stand in for real Verilator
//! `--trace-fst` output). Confirms the acceptance criterion "an FST-format
//! trace builds directly, with no VCD-parse step": `build_fst.rs` is the
//! only ingestion frontend exercised here (`build_vcd`/`parser` are never
//! invoked by this crate for a `trace.format: "fst"` request -- true by
//! construction, per `build.rs`'s own format dispatch), and this fixture
//! additionally has top-level/sub-scope signal aliasing (`tb.clk` /
//! `tb.dut.clk` share one underlying FST handle), exercising the same
//! alias path `build_vcd_test.rs`'s VCD fixture cannot (VCD aliasing is a
//! duplicate-`$var`-id declaration; this fixture's aliasing is FST-native).

use std::fs;
use std::path::PathBuf;

use klt_wave_native::build;

fn fixture_path(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("fixtures")
        .join(name)
}

fn write_request(dir: &std::path::Path, body: &str) -> PathBuf {
    let request_path = dir.join("request.json");
    fs::write(&request_path, body).unwrap();
    request_path
}

#[test]
fn build_from_fst_with_clock_and_reset() {
    let tmp = tempfile::tempdir().unwrap();
    let trace_path = fixture_path("counter.fst");
    let request = format!(
        r#"{{
            "schema": "klt.wave_build.request/1",
            "trace": {{ "path": {trace_path:?}, "format": "fst" }},
            "clock": {{ "signal": "tb.clk", "edge": "rising" }},
            "reset": {{ "signal": "tb.rst_n", "active": "low" }},
            "signals": null,
            "store": {{ "path": ".klt/wave/counter_from_fst.klwave" }}
        }}"#,
    );
    let request_path = write_request(tmp.path(), &request);

    let response = build::run(&request_path).expect("build should succeed");

    assert_eq!(response.trace.format, "fst");
    assert_eq!(
        response.trace.size_bytes,
        fs::metadata(&trace_path).unwrap().len()
    );

    // Every declared FST signal is indexed, aliases deduplicated to their
    // underlying handle -- 3 distinct signals (clk, rst_n, count), not 6
    // (the fixture declares each one twice: once at `tb.*`, once aliased
    // at `tb.dut.*`).
    assert_eq!(response.signal_count, 3);
    assert!(response.value_change_count > 0);

    let clock = response.clock.expect("clock block should be present");
    assert_eq!(clock.period_ns, Some(0.01));

    let reset = response.reset.expect("reset block should be present");
    let release = reset.release.expect("reset release should be resolved");
    assert_eq!(release.cycle, Some(0));

    assert!(response.store.size_bytes > 0);
    assert!(response.store.content_hash.starts_with("sha256:"));

    // The store round-trips through fst-reader independently.
    let store_path = tmp.path().join(".klt/wave/counter_from_fst.klwave");
    assert_eq!(
        fs::metadata(&store_path).unwrap().len(),
        response.store.size_bytes
    );
}

#[test]
fn build_from_fst_narrows_to_signals_allow_list() {
    let tmp = tempfile::tempdir().unwrap();
    let trace_path = fixture_path("counter.fst");
    let request = format!(
        r#"{{
            "trace": {{ "path": {trace_path:?}, "format": "fst" }},
            "signals": ["tb.clk"],
            "store": {{ "path": ".klt/wave/counter_from_fst_narrow.klwave" }}
        }}"#,
    );
    let request_path = write_request(tmp.path(), &request);
    let response = build::run(&request_path).expect("build should succeed");
    assert_eq!(response.signal_count, 1);
}

#[test]
fn build_from_fst_rejects_a_signal_absent_from_the_trace() {
    let tmp = tempfile::tempdir().unwrap();
    let trace_path = fixture_path("counter.fst");
    let request = format!(
        r#"{{
            "trace": {{ "path": {trace_path:?}, "format": "fst" }},
            "clock": {{ "signal": "tb.no_such_clock" }},
            "store": {{ "path": ".klt/wave/counter_from_fst_bad_clock.klwave" }}
        }}"#,
    );
    let request_path = write_request(tmp.path(), &request);
    let err = build::run(&request_path).expect_err("an unresolvable clock.signal must fail");
    assert_eq!(err.0, 1);
    assert!(err.1.contains("tb.no_such_clock"), "message was: {}", err.1);
}
