#!/usr/bin/env python3
"""`klt pex --measure-command` worked example (issue #2478): measure one spec
row that **no single `.meas` card can express**, on both legs of the sky130 5T
OTA composed layout (`06-layout.gds`).

## What `klt pex` runs, and what this script owns

`klt pex` invokes this script **twice** -- once with `07-reference.spice`
(the schematic leg) and once with its own freshly `--parasitics`-extracted
netlist (the extracted leg) -- passing that netlist's path as the final
argument and in `$KLT_PEX_NETLIST`, with `$KLT_PEX_SIDE` naming the leg and
`$KLT_PEX_ARTIFACTS_DIR` a per-leg scratch directory. This script prints a
*measurement document* on stdout; `klt pex` computes the per-corner
schematic-vs-extracted `delta[]` from the two documents itself, and emits the
ordinary `pex` envelope `klt signoff`'s T1 item 7 grades. See
`docs/cli/pex.md`'s "Measuring with a caller-supplied command" section.

## The spec row: `tail_turn_on_v`, a threshold-crossing search

The composed layout's generic `nfet` model is SPICE level=1 with the default
`VTO = 0` and every gate floating, pulled to exactly 0 V by
`.options rshunt=1e12` (`klt gen-compose` never routes a generator's
gate/unconnected source-drain port through `connectivity[]` -- see
`11-pex-mom.testbench.spice` for the full derivation). Two of the five
composed devices have their *source* on the tail net, so biasing that net
**negative** gives them `Vgs = 0 - V(tail) > VTO` and completes a real
external-source-to-external-source DC loop through the tail net's own star-arm
resistors -- the same current-carrying bias network Epic #709 Phase 3b's own
canary uses, and the reason this row is sensitive to the extraction at all.

`tail_turn_on_v` is the tail bias at which that loop's current magnitude first
reaches `_THRESHOLD_A`, located by:

1. sweeping the tail bias over `_BIAS_GRID_V` at each temperature corner
   (one `klt sim` run per leg, `.meas`-ing only the raw branch current);
2. walking the grid from the least-negative bias **in sweep order** and
   taking the **first adjacent pair that brackets** the threshold (not the
   closest point, not the last crossing);
3. linearly interpolating the crossing bias between that pair;
4. reporting `null` -- "unresolved" -- when the grid brackets no crossing at
   all, which `klt pex` renders as an `"error"` delta row rather than a
   fabricated pass.

Steps 2-4 are the part `.meas` cannot do. `.meas ... WHEN` searches *within
one run's own sweep vector*; this crossing lives **across separate simulation
runs at different parameter values**, and the "first bracketing pair, else
unresolved" rule is a caller-side decision about which crossing counts. That
is exactly the friction issue #2478 reported: the post-layout *work* was
always doable, but before `--measure-command` there was no way to turn it into
an envelope item 7 accepts.
"""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2] / "src"))

from klayout_tools.sim import run_sim  # noqa: E402

#: Tail-bias sweep grid, volts -- least-negative first, so "first bracketing
#: pair in sweep order" is a well-defined rule and not an artifact of dict
#: ordering. Chosen to straddle the crossing on both legs at every
#: temperature (see the README's own table of measured values).
_BIAS_GRID_V = (-0.05, -0.10, -0.15, -0.20, -0.25, -0.30, -0.35)

#: Tail-branch current magnitude whose first crossing defines this spec row.
_THRESHOLD_A = 2.0e-5

#: Temperature corners, matching `10-pex.request.json`'s own set.
_TEMPERATURES_C = (-40, 27, 125)

#: The spec row's own limits, applied by this script (a `--measure-command`
#: harness owns its own pass/fail, exactly as a `klt sim` request's
#: `measurements[].limits` does): the turn-on bias must land inside the swept
#: grid with margin, i.e. the search must have genuinely resolved.
_LIMITS_V = (-0.34, -0.06)

_TESTBENCH = """\
* Generated by 12-pex-external.probe.py for the {side} leg -- see that file.
.model nfet nmos level=1
.options rshunt=1e12
.param vtail=-0.15

Vvsubs vsubs     0 DC 0
Vn1    n1_node   0 DC 1.0
Vtail  tail_node 0 DC {{vtail}}
Vvout  vout_node 0 DC 1.0
Xota n1_node tail_node vout_node vsubs ota_5t_layout_0

* --- {side}-leg DUT, inlined verbatim from {netlist} (see _sweep) ---
{dut}
"""


def _sweep(netlist: str, side: str, work_dir: Path) -> list[dict]:
    """Run the raw bias sweep for one leg and return `klt sim`'s `corners[]`.

    Only `.meas`-expressible quantities are asked for here (one branch
    current per bias point); everything this example is actually about
    happens in :func:`_crossing_v` below, on the numbers this returns.

    The DUT is **inlined verbatim** into the generated deck rather than
    `.include`d. A `--measure-command` harness builds each leg's deck itself
    (that is exactly the contract `docs/cli/pex.md` describes), and a
    self-contained deck is the simplest portable way to do it -- it needs
    nothing from the transport at all. Since issue #2485 an `.include` would
    also work: `klt sim`'s off-host backends (`remote`/`batch`, where a
    multi-unit request like this 21-point grid routes by default on any host
    that sets `$KLT_SIM_BACKEND`) stage the netlist's whole include closure
    and rewrite each directive to its staged, job-relative name. Both
    netlists this is handed (`07-reference.spice` and `klt pex`'s own
    extracted output) are themselves `.include`-free, so one substitution is
    the whole DUT either way.
    """
    work_dir.mkdir(parents=True, exist_ok=True)
    testbench = work_dir / "tail-sweep.testbench.spice"
    testbench.write_text(
        _TESTBENCH.format(
            side=side,
            netlist=Path(netlist).name,
            dut=Path(netlist).read_text().rstrip("\n"),
        )
    )

    request = work_dir / "tail-sweep.request.json"
    request.write_text(
        json.dumps(
            {
                "netlist": str(testbench),
                "engine": "ngspice",
                "corners": {
                    "supply_v": {"vtail": list(_BIAS_GRID_V)},
                    "temperature_c": list(_TEMPERATURES_C),
                },
                "analysis": {"kind": "tran", "args": "1n 1n"},
                "measurements": [
                    {
                        "name": "itail",
                        "spice": ".meas tran itail find i(vtail) at=1n",
                        "unit": "A",
                    }
                ],
                "options": {"timeout_s": 60, "keep_artifacts": False},
            },
            indent=2,
        )
    )
    return run_sim(str(request), artifacts_dir=str(work_dir / "sim"))["corners"]


def _crossing_v(points: list[tuple[float, float]]) -> float | None:
    """The first tail bias at which `|i_tail|` crosses :data:`_THRESHOLD_A`,
    linearly interpolated -- or ``None`` ("unresolved") when the grid brackets
    no crossing.

    ``points`` is ``[(bias_v, i_tail_a), ...]`` **in sweep order** (least
    negative first). The rule is deliberately "the first adjacent pair that
    brackets", not "the point nearest the threshold": a sweep that re-crosses
    (a fold-back, a numerical wobble at a hot corner) must resolve to the
    *turn-on* crossing, which is the one the spec row names.
    """
    for (bias_a, current_a), (bias_b, current_b) in zip(
        points, points[1:], strict=False
    ):
        low, high = abs(current_a), abs(current_b)
        if low < _THRESHOLD_A <= high:
            span = high - low
            if span == 0:  # degenerate; no interpolation is meaningful
                return bias_b
            return bias_a + (bias_b - bias_a) * (_THRESHOLD_A - low) / span
    return None


def main() -> int:
    netlist = sys.argv[-1]
    side = os.environ["KLT_PEX_SIDE"]
    work_dir = Path(os.environ["KLT_PEX_ARTIFACTS_DIR"])

    by_temperature: dict[float, list[tuple[float, float]]] = {}
    for corner in _sweep(netlist, side, work_dir):
        measured = corner["measurements"][0]["value"]
        if measured is None:
            continue  # a corner that did not converge contributes no point
        by_temperature.setdefault(corner["temperature_c"], []).append(
            (corner["supply_v"]["vtail"], measured)
        )

    corners = []
    for temperature_c in _TEMPERATURES_C:
        points = sorted(
            by_temperature.get(temperature_c, []), key=lambda point: -point[0]
        )
        crossing = _crossing_v(points)
        resolved = crossing is not None and _LIMITS_V[0] <= crossing <= _LIMITS_V[1]
        corners.append(
            {
                "corner_id": f"default/{temperature_c}C",
                "measurements": [
                    {
                        "name": "tail_turn_on_v",
                        "value": None if crossing is None else round(crossing, 6),
                        "unit": "V",
                        # "unresolved" is a first-class outcome: `null` +
                        # "error" here, never a fabricated pass.
                        "status": "pass"
                        if resolved
                        else ("fail" if crossing is not None else "error"),
                    }
                ],
            }
        )

    json.dump({"corners": corners}, sys.stdout, indent=2)
    sys.stdout.write("\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
