#!/usr/bin/env python3
"""Generate `examples/dogbone-terminal/example_<family>.gds`: a hand-drawn
"dog-bone" narrow-`W` unit MOS device, composed in the same cell as an
ordinary-width `klt gen mos_array` device -- the documented recipe issue
#1574 asks for as a fallback to a full generator-level `dogbone_terminals`
parameter (see `docs/cli/gen.md`, "Below `UNIT_MIN_W_UM`: dog-bone
terminals drawn by hand").

`mos_array`/`diff_pair` reject any `w_um` below `UNIT_MIN_W_UM` (0.42um --
the width below which a unit device's own source/drain contact can no
longer be legally enclosed by a uniform-width diffusion strip) outright,
with no override (see `gen.py`'s `_mos_array_validate`/
`_diff_pair_validate`). A real full-custom device below that floor -- e.g.
a narrow-and-long always-on weak pull-up (`W` far below 0.42um, `L` tens of
um, kept narrow deliberately for its channel resistance, not as a matched-
array element) -- still needs to be drawn, just not through `mos_array`/
`diff_pair` directly.

This script draws that one device by hand with `klayout.db`, using a
standard "dog-bone" terminal: only the two source/drain pads are widened
(to `CONTACT_SIZE_UM + 2 * ENCLOSURE_MARGIN_UM` -- exactly the pad size
`mos_array`'s own unit devices size their contact regions to), with an
unwidened "shoulder" of diffusion kept between each pad and the gate edge
so the width step lands well clear of it, while the gate-crossing diffusion
segment (the electrical channel a downstream `klt extract` reads `W` from)
is drawn at the requested narrow width, unmodified. The device is drawn on
the exact same role layers (`active`/`poly`/`contact`/`metal`) `mos_array`'s
own unit devices use (`klayout_tools.gen._PDK_ROLE_LAYERS`), then placed in
the same cell as an ordinary-width unit device generated by a real `klt gen
mos_array` request -- demonstrating the two compose cleanly side by side.

Run from the repo root:

    uv run python3 examples/dogbone-terminal/generate.py

Regenerates `examples/dogbone-terminal/example_sky130.gds`/
`example_gf180mcu.gds` deterministically, plus their companion
`example_<family>.drc.json` (`run_drc`'s report against the matching
curated deck, both `"status": "clean"` -- verified by this script itself
before it writes them; the `"provenance"` block is stripped before writing,
matching `examples/drc/example.drc.json`'s own convention, since its
`klt_version`/`klayout_version` fields are environment-dependent, not part
of the fixture's contract).
"""

import json
import os
import tempfile

import klayout.db as kdb

from klayout_tools.drc import run_drc
from klayout_tools.gen import (
    CONTACT_SIZE_UM,
    ENCLOSURE_MARGIN_UM,
    UNIT_MIN_W_UM,
    generate,
)

# --------------------------------------------------------------------------- #
# The narrow device this recipe demonstrates: `W` well under `UNIT_MIN_W_UM`
# (0.42um) -- the generator's own contact-fit floor -- but still >= the
# *real* PDK's own diffusion-width minimum (sky130 `diff.width.1`: 0.15um;
# gf180mcu `comp.width.1`: 0.22um), and a long `L`: exactly the "narrow-and-
# long always-on weak pull-up" issue #1574 describes.
# --------------------------------------------------------------------------- #
W_CHANNEL_UM = 0.30
L_UM = 10.0

assert W_CHANNEL_UM < UNIT_MIN_W_UM, "W_CHANNEL_UM must be below the generator floor"

#: Same pad size `mos_array`'s own unit devices size their source/drain
#: contact regions to (`gen.py`'s `contact_region_um`) -- wide enough to
#: enclose one `CONTACT_SIZE_UM` contact with `ENCLOSURE_MARGIN_UM` margin
#: on every side.
CONTACT_REGION_UM = CONTACT_SIZE_UM + 2 * ENCLOSURE_MARGIN_UM  # 0.42

#: Unwidened diffusion kept between each pad's flared edge and the gate, so
#: the width step lands clear of the gate rather than immediately at its
#: edge -- the same margin this module already sizes its contact-enclosure
#: budget against.
SHOULDER_UM = ENCLOSURE_MARGIN_UM

#: Generous clearance between the dog-bone device and the composed
#: ordinary-width `klt gen mos_array` device -- comfortably above every
#: same-layer spacing rule either curated deck checks (largest is
#: gf180mcu's `metal1.space.1`/`comp.space.1`, both 0.23-0.28um).
DEVICE_SPACING_UM = 2.0

DBU_UM = 0.001

#: `active`/`poly`/`contact`/`metal` role layer/datatype pairs, one set per
#: family -- the exact pairs `klayout_tools.gen._PDK_ROLE_LAYERS` resolves
#: `mos_array`/`diff_pair` to, so this hand-drawn device merges into the
#: same recognised device role a `klt extract` pass already keys off.
_ROLE_LAYERS = {
    "sky130": {
        "active": (65, 20),  # diff.drawing
        "poly": (66, 20),  # poly.drawing
        "contact": (66, 44),  # licon1.drawing
        "metal": (67, 20),  # li1.drawing
    },
    "gf180mcu": {
        "active": (22, 0),  # Comp
        "poly": (30, 0),  # Poly2
        "contact": (33, 0),  # Contact
        "metal": (34, 0),  # Metal1
    },
}

#: A fabricated `open_pdks`-layout install directory name per family -- only
#: the `libs.tech/` probe `find_pdk()` checks for is needed (mirrors
#: `tests/test_gen.py`'s own `_make_install`); `klt gen`'s phase-2
#: generators never read real PDK tech files, only their resolved family
#: name (`klayout_tools.gen._pdk_family`).
_MOS_ARRAY_VARIANT = {"sky130": "sky130A", "gf180mcu": "gf180mcuD"}


def _um_to_dbu(v_um: float) -> int:
    return int(round(v_um / DBU_UM))


def _box(x0_um: float, y0_um: float, x1_um: float, y1_um: float) -> kdb.Box:
    return kdb.Box(
        _um_to_dbu(x0_um), _um_to_dbu(y0_um), _um_to_dbu(x1_um), _um_to_dbu(y1_um)
    )


def _dogbone_boxes_um(
    w_channel_um: float, l_um: float
) -> tuple[dict[str, list[tuple[float, float, float, float]]], float]:
    """Per-role box lists (um) for one dog-bone unit device, plus its total
    footprint length along the source-to-drain axis.

    Layout, left (source) to right (drain), all centred on one shared
    y-centreline (`CONTACT_REGION_UM / 2`):

        |<-pad->|<-shoulder->|<---- gate (l_um) ---->|<-shoulder->|<-pad->|
         CONTACT_REGION_UM    W_CHANNEL_UM tall (the   CONTACT_REGION_UM
         tall                 real, narrow W)          tall

    The source/drain pads are `CONTACT_REGION_UM` square (wide enough to
    enclose a contact); the shoulder and gate-crossing segments are drawn at
    the requested `w_channel_um`, so the electrical channel width a
    downstream `klt extract` reads is exactly `w_channel_um`, never the
    widened pad width. The gate poly spans the full `CONTACT_REGION_UM`
    height (like the pads), so it fully covers the narrower channel
    underneath it with margin on both sides -- the same "poly taller than
    the diffusion it gates" shape `mos_array`'s own unit devices draw for
    their gate landing pads.
    """
    pad_len_um = CONTACT_REGION_UM
    y_mid_um = CONTACT_REGION_UM / 2.0
    y0_pad_um, y1_pad_um = 0.0, CONTACT_REGION_UM
    y0_ch_um = y_mid_um - w_channel_um / 2.0
    y1_ch_um = y_mid_um + w_channel_um / 2.0

    boxes: dict[str, list[tuple[float, float, float, float]]] = {
        "active": [],
        "poly": [],
        "contact": [],
        "metal": [],
    }

    def _sd_pad(x0_um: float) -> None:
        x1_um = x0_um + pad_len_um
        boxes["active"].append((x0_um, y0_pad_um, x1_um, y1_pad_um))
        boxes["metal"].append((x0_um, y0_pad_um, x1_um, y1_pad_um))
        cx_um = (x0_um + x1_um) / 2.0
        c_half_um = CONTACT_SIZE_UM / 2.0
        boxes["contact"].append(
            (
                cx_um - c_half_um,
                y_mid_um - c_half_um,
                cx_um + c_half_um,
                y_mid_um + c_half_um,
            )
        )

    x_um = 0.0
    _sd_pad(x_um)
    x_um += pad_len_um

    # Source-side shoulder + gate-crossing channel + drain-side shoulder --
    # all at the narrow, requested width. Drawn as three abutting boxes
    # (rather than one) so the gate poly's own x-range is explicit and
    # independent of the shoulder length.
    boxes["active"].append((x_um, y0_ch_um, x_um + SHOULDER_UM, y1_ch_um))
    x_um += SHOULDER_UM

    gate_x0_um = x_um
    boxes["active"].append((x_um, y0_ch_um, x_um + l_um, y1_ch_um))
    boxes["poly"].append((gate_x0_um, y0_pad_um, gate_x0_um + l_um, y1_pad_um))
    x_um += l_um

    boxes["active"].append((x_um, y0_ch_um, x_um + SHOULDER_UM, y1_ch_um))
    x_um += SHOULDER_UM

    _sd_pad(x_um)
    x_um += pad_len_um

    return boxes, x_um


def _draw_dogbone(layout: kdb.Layout, cell: kdb.Cell, family: str) -> float:
    """Draw one dog-bone unit device into `cell` and return its footprint
    length (um) along the source-to-drain axis."""
    layers = _ROLE_LAYERS[family]
    boxes, total_len_um = _dogbone_boxes_um(W_CHANNEL_UM, L_UM)
    for role, box_list in boxes.items():
        layer_index = layout.layer(*layers[role])
        for x0_um, y0_um, x1_um, y1_um in box_list:
            cell.shapes(layer_index).insert(_box(x0_um, y0_um, x1_um, y1_um))
    return total_len_um


def _generate_ordinary_unit(family: str, out_path: str) -> dict:
    """Run a real `klt gen mos_array` request for one ordinary-width unit
    device (`w_um` above `UNIT_MIN_W_UM`, `rows`/`cols`/`dummy` all `1`/`1`/
    `0` -- just the one device), against a fabricated PDK install so this
    script needs no real PDK download. Returns the response envelope."""
    variant = _MOS_ARRAY_VARIANT[family]
    with tempfile.TemporaryDirectory() as tmp_root:
        install_dir = os.path.join(tmp_root, variant, "libs.tech")
        os.makedirs(install_dir)
        return generate(
            {
                "generator": "mos_array",
                "pdk": {"variant": variant, "root": tmp_root},
                "params": {"w_um": 0.6, "l_um": 0.5, "rows": 1, "cols": 1, "dummy": 0},
                "options": {"cell_name": "ordinary_unit", "output": out_path},
            }
        )


def build_example(family: str, out_dir: str) -> tuple[str, str]:
    """Build `example_<family>.gds`/`.drc.json` and return their paths."""
    layout = kdb.Layout()
    layout.dbu = DBU_UM
    top = layout.create_cell("TOP")

    dogbone_cell = layout.create_cell("dogbone_weak_pullup")
    dogbone_len_um = _draw_dogbone(layout, dogbone_cell, family)
    top.insert(kdb.CellInstArray(dogbone_cell.cell_index(), kdb.Trans()))

    with tempfile.TemporaryDirectory() as scratch:
        ordinary_gds = os.path.join(scratch, "ordinary_unit.gds")
        response = _generate_ordinary_unit(family, ordinary_gds)
        layout.read(ordinary_gds)

    ordinary_cell = layout.cell(response["cell_name"])
    x_off_um = dogbone_len_um + DEVICE_SPACING_UM
    top.insert(
        kdb.CellInstArray(
            ordinary_cell.cell_index(), kdb.Trans(kdb.Point(_um_to_dbu(x_off_um), 0))
        )
    )

    gds_path = os.path.join(out_dir, f"example_{family}.gds")
    write_options = kdb.SaveLayoutOptions()
    write_options.gds2_write_timestamps = False  # reproducible bytes (#320)
    layout.write(gds_path, write_options)

    gds_rel_path = os.path.relpath(gds_path)
    report = run_drc(gds_rel_path, family)
    report.pop("provenance", None)  # environment-dependent, stripped (see
    # examples/drc/example.drc.json's own convention)
    if report["status"] != "clean":
        raise SystemExit(
            f"generated {gds_rel_path} is not DRC-clean on '{family}': "
            f"{report['violation_count']} violation(s): {report['rule_counts']}"
        )

    json_path = os.path.join(out_dir, f"example_{family}.drc.json")
    with open(json_path, "w") as f:
        json.dump(report, f, indent=2)
        f.write("\n")

    return gds_path, json_path


def main() -> None:
    out_dir = os.path.dirname(os.path.abspath(__file__))
    for family in ("sky130", "gf180mcu"):
        gds_path, json_path = build_example(family, out_dir)
        print(f"wrote {gds_path}")
        print(f"wrote {json_path}")


if __name__ == "__main__":
    main()
