//! Two emitters, one module (both consume the same [`GenericNetlist`]
//! shape, so they stay next to each other rather than splitting into
//! separate files):
//!
//! - [`write`] -- the **mapped** netlist as structural Verilog in
//!   **exactly** the dialect `native/statime/src/netlist.rs` already parses
//!   -- `docs/design/synth-techmap-stage-contract.md` section 4/5: a flat
//!   module, `input`/`output`/`wire` declarations, named-port (`.PIN(net)`)
//!   technology-cell instances only, no `assign`, no concatenation, no
//!   inline constants.
//! - [`write_generic`] -- the **pre-mapping generic netlist** ($2.2's ten
//!   technology-independent primitives) as plain behavioral Verilog
//!   (`assign`/`always @(posedge ...)`), issue #875's own addition: this is
//!   the `gold` side `klt equiv` (`klayout_tools.equiv.run_equiv`) is
//!   handed to prove a mapped netlist faithful to the generic netlist it
//!   was mapped from, mirroring Phase 1b's own `klt synthesize
//!   --verify-equivalence` gate (`src/klayout_tools/synthesize.py`'s
//!   `_verify_synthesis_equivalence`) one stage later in the pipeline. Pure
//!   behavioral RTL, not a library of primitive-cell module definitions
//!   instantiated by name: the ten primitive `type` strings (`$and2`, ...)
//!   are not legal Verilog module-instance identifiers (a bare `$` prefix
//!   is reserved for system tasks/functions), and expressing each cell's
//!   already-known Boolean function directly as `assign`/`always` needs no
//!   such workaround, self-contained (no liberty side file, unlike the
//!   mapped side which references real standard-cell instances that need
//!   one).

use std::collections::HashSet;
use std::fmt;

use crate::genlist::{GenericCell, GenericNetlist, PortDirection};
use crate::map::MappedInstance;

#[derive(Debug)]
pub struct VerilogError(pub String);

impl fmt::Display for VerilogError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.0)
    }
}

/// Render `port.bits` as a Verilog `input`/`output` declaration line.
/// Assumes (per the interim on-ramp converter, `tests/corpus/techmap/`)
/// a dense, zero-indexed bus: `bits.len()` bits numbered `bits.len()-1
/// downto 0` for anything wider than 1 bit -- matching every fixture this
/// crate's own corpus harness produces. A port whose `bits` don't follow
/// that convention still emits (each bit already carries its own literal
/// net name from the generic netlist), just without a compact `[msb:lsb]`
/// declaration -- see the `else` branch below.
///
/// Errors (rather than underflowing `bits.len() - 1`) on an empty `bits`
/// array -- `genlist::parse` doesn't reject one, so a malformed
/// generic-netlist JSON with a zero-width port is reachable here, not just
/// a defensive-coding nicety.
fn port_decl(name: &str, dir: &str, bits: &[String]) -> Result<String, VerilogError> {
    if bits.is_empty() {
        return Err(VerilogError(format!(
            "port '{name}' has an empty 'bits' array -- a port must declare at least one bit"
        )));
    }
    if bits.len() == 1 && bits[0] == name {
        Ok(format!("  {dir} {name};\n"))
    } else {
        let msb = bits.len() - 1;
        Ok(format!("  {dir} [{msb}:0] {name};\n"))
    }
}

pub fn write(
    netlist: &GenericNetlist,
    instances: &[MappedInstance],
) -> Result<String, VerilogError> {
    let mut out = String::new();
    out.push_str("/* Generated by klt-techmap (issue #874) */\n\n");

    let port_names: Vec<&str> = netlist.ports.iter().map(|p| p.name.as_str()).collect();
    out.push_str(&format!(
        "module {} ({});\n",
        netlist.top,
        port_names.join(", ")
    ));

    let mut port_bit_nets: HashSet<String> = HashSet::new();
    for port in &netlist.ports {
        let dir = match port.direction {
            PortDirection::Input => "input",
            PortDirection::Output => "output",
            PortDirection::Inout => "inout",
        };
        out.push_str(&port_decl(&port.name, dir, &port.bits)?);
        for b in &port.bits {
            port_bit_nets.insert(b.clone());
        }
    }

    let referenced = crate::map::referenced_nets(instances);
    let mut internal: Vec<&String> = referenced
        .iter()
        .filter(|n| !port_bit_nets.contains(*n))
        .collect();
    internal.sort();
    for net in &internal {
        out.push_str(&format!("  wire {net};\n"));
    }
    out.push('\n');

    for inst in instances {
        out.push_str(&format!("  {} {} (\n", inst.cell_type, inst.instance_name));
        let mut pins: Vec<&String> = inst.connections.keys().collect();
        pins.sort();
        let lines: Vec<String> = pins
            .iter()
            .map(|pin| format!("    .{pin}({})", inst.connections[*pin]))
            .collect();
        out.push_str(&lines.join(",\n"));
        out.push_str("\n  );\n");
    }

    out.push_str("endmodule\n");
    Ok(out)
}

/// A generic-netlist connection net, rendered for use inside a Verilog
/// expression: the reserved pseudo-net names `"$const0"`/`"$const1"`
/// (`docs/design/synth-techmap-stage-contract.md` section 8 -- the same
/// convention `map.rs::resolve_net` resolves on the mapped side) become the
/// literals `1'b0`/`1'b1` here (bare `$`-prefixed identifiers are not legal
/// Verilog); every other net name passes through unchanged, matching
/// [`write`]'s own net-naming convention.
fn net_expr(net: &str) -> String {
    match net {
        "$const0" => "1'b0".to_string(),
        "$const1" => "1'b1".to_string(),
        other => other.to_string(),
    }
}

/// Fetch a required pin connection off a generic cell, or a
/// [`VerilogError`] naming the missing pin -- mirrors `map.rs`'s own
/// `MapError::MissingConnection`, independently, since this emitter has no
/// dependency on `map.rs` (it runs on the *pre*-mapping netlist).
fn get_pin<'a>(cell: &'a GenericCell, pin: &str) -> Result<&'a String, VerilogError> {
    cell.connections.get(pin).ok_or_else(|| {
        VerilogError(format!(
            "cell '{}' (type '{}') is missing required connection '{pin}'",
            cell.name, cell.cell_type
        ))
    })
}

/// Emit the **pre-mapping** generic netlist (`docs/design/synth-techmap-stage-contract.md`
/// section 2) as self-contained behavioral Verilog -- see this module's own
/// doc comment for why behavioral `assign`/`always`, not cell instances.
///
/// A generic `$dff`'s `Q` output net (and, transitively, any port entirely
/// composed of such nets) is driven by a procedural `always` block, so it
/// is declared `reg`, not `wire` -- every other net (combinational) stays
/// `wire`, exactly the same "reg vs. wire" split any real synthesizable
/// Verilog module needs. A port whose bits are driven by a mix of the two
/// (some combinational, some registered) is an [`VerilogError`] -- not a
/// shape this stage's 10-primitive `v1` vocabulary is expected to produce
/// (a real per-bit register bank wires *every* bit of its own output port
/// through a `$dff`), and mixing `assign`/procedural drivers on one bus
/// declaration is not valid Verilog to begin with.
pub fn write_generic(netlist: &GenericNetlist) -> Result<String, VerilogError> {
    let mut out = String::new();
    out.push_str(
        "/* Generated by klt-techmap (issue #875) -- behavioral Verilog for the \
         pre-mapping generic netlist, used as klt equiv's `gold` side */\n\n",
    );

    let port_names: Vec<&str> = netlist.ports.iter().map(|p| p.name.as_str()).collect();
    out.push_str(&format!(
        "module {} ({});\n",
        netlist.top,
        port_names.join(", ")
    ));

    let mut reg_nets: HashSet<String> = HashSet::new();
    for cell in &netlist.cells {
        if cell.cell_type == "$dff" {
            if let Some(q) = cell.connections.get("Q") {
                reg_nets.insert(q.clone());
            }
        }
    }

    let mut port_bit_nets: HashSet<String> = HashSet::new();
    for port in &netlist.ports {
        let any_reg = port.bits.iter().any(|b| reg_nets.contains(b));
        let all_reg = port.bits.iter().all(|b| reg_nets.contains(b));
        if any_reg && !all_reg {
            return Err(VerilogError(format!(
                "port '{}' mixes $dff-driven and combinational bits -- not \
                 supported by the v1 generic-netlist Verilog emitter",
                port.name
            )));
        }
        let base_dir = match port.direction {
            PortDirection::Input => "input",
            PortDirection::Output => "output",
            PortDirection::Inout => "inout",
        };
        let dir = if all_reg && matches!(port.direction, PortDirection::Output) {
            "output reg"
        } else {
            base_dir
        };
        out.push_str(&port_decl(&port.name, dir, &port.bits)?);
        for b in &port.bits {
            port_bit_nets.insert(b.clone());
        }
    }

    let mut referenced: HashSet<String> = HashSet::new();
    for cell in &netlist.cells {
        for net in cell.connections.values() {
            if net == "$const0" || net == "$const1" {
                continue;
            }
            referenced.insert(net.clone());
        }
    }
    let mut internal: Vec<&String> = referenced
        .iter()
        .filter(|n| !port_bit_nets.contains(*n))
        .collect();
    internal.sort();
    for net in &internal {
        let kind = if reg_nets.contains(*net) {
            "reg"
        } else {
            "wire"
        };
        out.push_str(&format!("  {kind} {net};\n"));
    }
    out.push('\n');

    for cell in &netlist.cells {
        match cell.cell_type.as_str() {
            "$not" => {
                let a = net_expr(get_pin(cell, "A")?);
                let y = get_pin(cell, "Y")?;
                out.push_str(&format!("  assign {y} = !{a};\n"));
            }
            "$buf" => {
                let a = net_expr(get_pin(cell, "A")?);
                let y = get_pin(cell, "Y")?;
                out.push_str(&format!("  assign {y} = {a};\n"));
            }
            "$and2" => {
                let a = net_expr(get_pin(cell, "A")?);
                let b = net_expr(get_pin(cell, "B")?);
                let y = get_pin(cell, "Y")?;
                out.push_str(&format!("  assign {y} = {a} & {b};\n"));
            }
            "$nand2" => {
                let a = net_expr(get_pin(cell, "A")?);
                let b = net_expr(get_pin(cell, "B")?);
                let y = get_pin(cell, "Y")?;
                out.push_str(&format!("  assign {y} = !({a} & {b});\n"));
            }
            "$or2" => {
                let a = net_expr(get_pin(cell, "A")?);
                let b = net_expr(get_pin(cell, "B")?);
                let y = get_pin(cell, "Y")?;
                out.push_str(&format!("  assign {y} = {a} | {b};\n"));
            }
            "$nor2" => {
                let a = net_expr(get_pin(cell, "A")?);
                let b = net_expr(get_pin(cell, "B")?);
                let y = get_pin(cell, "Y")?;
                out.push_str(&format!("  assign {y} = !({a} | {b});\n"));
            }
            "$xor2" => {
                let a = net_expr(get_pin(cell, "A")?);
                let b = net_expr(get_pin(cell, "B")?);
                let y = get_pin(cell, "Y")?;
                out.push_str(&format!("  assign {y} = {a} ^ {b};\n"));
            }
            "$xnor2" => {
                let a = net_expr(get_pin(cell, "A")?);
                let b = net_expr(get_pin(cell, "B")?);
                let y = get_pin(cell, "Y")?;
                out.push_str(&format!("  assign {y} = !({a} ^ {b});\n"));
            }
            "$mux2" => {
                let a = net_expr(get_pin(cell, "A")?);
                let b = net_expr(get_pin(cell, "B")?);
                let s = net_expr(get_pin(cell, "S")?);
                let y = get_pin(cell, "Y")?;
                out.push_str(&format!("  assign {y} = {s} ? {b} : {a};\n"));
            }
            "$dff" => {
                let d = net_expr(get_pin(cell, "D")?);
                let clk = net_expr(get_pin(cell, "CLK")?);
                let q = get_pin(cell, "Q")?;
                let rst = cell.connections.get("RST").map(|n| net_expr(n));
                let en = cell.connections.get("EN").map(|n| net_expr(n));
                out.push_str(&format!("  always @(posedge {clk}) begin\n"));
                match (rst, en) {
                    (Some(r), Some(e)) => {
                        out.push_str(&format!(
                            "    if ({r})\n      {q} <= 1'b0;\n    else if ({e})\n      {q} <= {d};\n"
                        ));
                    }
                    (Some(r), None) => {
                        out.push_str(&format!(
                            "    if ({r})\n      {q} <= 1'b0;\n    else\n      {q} <= {d};\n"
                        ));
                    }
                    (None, Some(e)) => {
                        out.push_str(&format!("    if ({e})\n      {q} <= {d};\n"));
                    }
                    (None, None) => {
                        out.push_str(&format!("    {q} <= {d};\n"));
                    }
                }
                out.push_str("  end\n");
            }
            other => {
                return Err(VerilogError(format!(
                    "cell '{}' has type '{other}' outside the v1 generic vocabulary -- \
                     cannot emit Verilog",
                    cell.name
                )));
            }
        }
    }

    out.push_str("endmodule\n");
    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::genlist::{GenericNetlist, Port};
    use std::collections::HashMap;

    #[test]
    fn emits_parseable_flat_module() {
        let netlist = GenericNetlist {
            schema: "klt.synth.generic-netlist/1".to_string(),
            top: "adder2".to_string(),
            ports: vec![
                Port {
                    name: "a".to_string(),
                    direction: PortDirection::Input,
                    bits: vec!["a[1]".into(), "a[0]".into()],
                },
                Port {
                    name: "y".to_string(),
                    direction: PortDirection::Output,
                    bits: vec!["y".into()],
                },
            ],
            cells: vec![],
        };
        let mut conns = HashMap::new();
        conns.insert("A".to_string(), "a[0]".to_string());
        conns.insert("B".to_string(), "a[1]".to_string());
        conns.insert("X".to_string(), "y".to_string());
        let instances = vec![MappedInstance {
            instance_name: "_g0_".to_string(),
            cell_type: "sky130_fd_sc_hd__and2_1".to_string(),
            connections: conns,
        }];
        let text = write(&netlist, &instances).unwrap();
        assert!(text.contains("module adder2 (a, y);"));
        assert!(text.contains("input [1:0] a;"));
        assert!(text.contains("output y;"));
        assert!(text.contains("sky130_fd_sc_hd__and2_1 _g0_ ("));
        assert!(text.contains(".A(a[0])"));
        assert!(text.contains("endmodule"));

        // This is a structural spot-check only (dialect shape, not a real
        // parse) -- this crate intentionally does not depend on
        // `native/statime` as a library (two independent spike crates, per
        // this repo's `native/<engine>/` convention), so it cannot invoke
        // that crate's actual parser from a unit test. The real end-to-end
        // check -- native/statime's `klt-statime` binary parsing this
        // crate's own generated mapped netlist unmodified -- runs in
        // `tests/corpus/techmap/compare.py` (contract section 5's
        // acceptance check, run for real against the corpus fixtures).
        let looks_like_the_shared_dialect = dialect_shape_check(&text, "adder2");
        assert!(looks_like_the_shared_dialect);
    }

    #[test]
    fn empty_bits_port_errs_instead_of_underflowing() {
        // A malformed generic-netlist JSON can declare a port with an
        // empty `bits` array (`genlist::parse` doesn't reject it) --
        // `port_decl` must return an `Err`, not underflow `bits.len() - 1`
        // (a `usize` panic in debug, a garbage `[huge:0]` decl in release).
        let netlist = GenericNetlist {
            schema: "klt.synth.generic-netlist/1".to_string(),
            top: "bad".to_string(),
            ports: vec![Port {
                name: "z".to_string(),
                direction: PortDirection::Input,
                bits: vec![],
            }],
            cells: vec![],
        };
        let result = write(&netlist, &[]);
        assert!(result.is_err());
    }

    /// Checks the structural properties `native/statime/src/netlist.rs`'s
    /// own doc comment requires of its input (`module NAME(...);`,
    /// `input`/`output`/`wire` decls, named-port instances, `endmodule`,
    /// no `assign`) -- a shape spot-check, not a substitute for the real
    /// parser run in `tests/corpus/techmap/compare.py`.
    fn dialect_shape_check(text: &str, top: &str) -> bool {
        text.contains(&format!("module {top} ("))
            && text.contains("endmodule")
            && text.contains(".A(")
            && !text.contains("assign ")
    }

    fn cell(name: &str, ty: &str, conns: &[(&str, &str)]) -> GenericCell {
        GenericCell {
            name: name.to_string(),
            cell_type: ty.to_string(),
            connections: conns
                .iter()
                .map(|(k, v)| (k.to_string(), v.to_string()))
                .collect(),
        }
    }

    #[test]
    fn write_generic_emits_behavioral_verilog_for_every_combinational_primitive() {
        let netlist = GenericNetlist {
            schema: "klt.synth.generic-netlist/1".to_string(),
            top: "prims".to_string(),
            ports: vec![
                Port {
                    name: "a".to_string(),
                    direction: PortDirection::Input,
                    bits: vec!["a".into()],
                },
                Port {
                    name: "b".to_string(),
                    direction: PortDirection::Input,
                    bits: vec!["b".into()],
                },
                Port {
                    name: "s".to_string(),
                    direction: PortDirection::Input,
                    bits: vec!["s".into()],
                },
                Port {
                    name: "y".to_string(),
                    direction: PortDirection::Output,
                    bits: vec!["y".into()],
                },
            ],
            cells: vec![
                cell("g0", "$and2", &[("A", "a"), ("B", "b"), ("Y", "n1")]),
                cell("g1", "$or2", &[("A", "a"), ("B", "b"), ("Y", "n2")]),
                cell("g2", "$not", &[("A", "n1"), ("Y", "n3")]),
                cell(
                    "g3",
                    "$mux2",
                    &[("A", "n2"), ("B", "n3"), ("S", "s"), ("Y", "y")],
                ),
            ],
        };
        let text = write_generic(&netlist).unwrap();
        assert!(text.contains("module prims (a, b, s, y);"));
        assert!(text.contains("input a;"));
        assert!(text.contains("output y;"));
        assert!(text.contains("wire n1;"));
        assert!(text.contains("assign n1 = a & b;"));
        assert!(text.contains("assign n2 = a | b;"));
        assert!(text.contains("assign n3 = !n1;"));
        assert!(text.contains("assign y = s ? n3 : n2;"));
        assert!(text.contains("endmodule"));
        // Purely behavioral -- no cell instances, unlike `write`'s own
        // dialect (which is the point: this is klt equiv's `gold` side,
        // read as plain RTL, no liberty needed).
        assert!(!text.contains("sky130"));
    }

    #[test]
    fn write_generic_resolves_const_nets_to_verilog_literals() {
        let netlist = GenericNetlist {
            schema: "klt.synth.generic-netlist/1".to_string(),
            top: "tie".to_string(),
            ports: vec![
                Port {
                    name: "a".to_string(),
                    direction: PortDirection::Input,
                    bits: vec!["a".into()],
                },
                Port {
                    name: "y".to_string(),
                    direction: PortDirection::Output,
                    bits: vec!["y".into()],
                },
            ],
            cells: vec![cell(
                "g0",
                "$and2",
                &[("A", "a"), ("B", "$const1"), ("Y", "y")],
            )],
        };
        let text = write_generic(&netlist).unwrap();
        assert!(text.contains("assign y = a & 1'b1;"));
        // The reserved pseudo-net must never leak into a `wire` decl.
        assert!(!text.contains("$const1"));
    }

    #[test]
    fn write_generic_emits_a_reg_dff_with_reset_and_enable() {
        let netlist = GenericNetlist {
            schema: "klt.synth.generic-netlist/1".to_string(),
            top: "reg1".to_string(),
            ports: vec![
                Port {
                    name: "d".to_string(),
                    direction: PortDirection::Input,
                    bits: vec!["d".into()],
                },
                Port {
                    name: "clk".to_string(),
                    direction: PortDirection::Input,
                    bits: vec!["clk".into()],
                },
                Port {
                    name: "rst".to_string(),
                    direction: PortDirection::Input,
                    bits: vec!["rst".into()],
                },
                Port {
                    name: "en".to_string(),
                    direction: PortDirection::Input,
                    bits: vec!["en".into()],
                },
                Port {
                    name: "q".to_string(),
                    direction: PortDirection::Output,
                    bits: vec!["q".into()],
                },
            ],
            cells: vec![cell(
                "r0",
                "$dff",
                &[
                    ("D", "d"),
                    ("CLK", "clk"),
                    ("Q", "q"),
                    ("RST", "rst"),
                    ("EN", "en"),
                ],
            )],
        };
        let text = write_generic(&netlist).unwrap();
        assert!(text.contains("output reg q;"));
        assert!(text.contains("always @(posedge clk) begin"));
        assert!(text.contains("if (rst)"));
        assert!(text.contains("q <= 1'b0;"));
        assert!(text.contains("else if (en)"));
        assert!(text.contains("q <= d;"));
        assert!(text.contains("end"));
    }

    #[test]
    fn write_generic_rejects_a_port_mixing_reg_and_wire_bits() {
        let netlist = GenericNetlist {
            schema: "klt.synth.generic-netlist/1".to_string(),
            top: "mixed".to_string(),
            ports: vec![
                Port {
                    name: "clk".to_string(),
                    direction: PortDirection::Input,
                    bits: vec!["clk".into()],
                },
                Port {
                    name: "d".to_string(),
                    direction: PortDirection::Input,
                    bits: vec!["d".into()],
                },
                Port {
                    name: "y".to_string(),
                    direction: PortDirection::Output,
                    bits: vec!["y[1]".into(), "y[0]".into()],
                },
            ],
            cells: vec![
                cell("g0", "$buf", &[("A", "d"), ("Y", "y[0]")]),
                cell("r0", "$dff", &[("D", "d"), ("CLK", "clk"), ("Q", "y[1]")]),
            ],
        };
        let err = write_generic(&netlist).unwrap_err();
        assert!(err.0.contains("mixes $dff-driven and combinational bits"));
    }

    #[test]
    fn write_generic_rejects_a_type_outside_the_v1_vocabulary() {
        let netlist = GenericNetlist {
            schema: "klt.synth.generic-netlist/1".to_string(),
            top: "bad".to_string(),
            ports: vec![],
            cells: vec![cell("g0", "$notreal", &[("A", "a"), ("Y", "y")])],
        };
        let err = write_generic(&netlist).unwrap_err();
        assert!(err.0.contains("outside the v1 generic vocabulary"));
    }
}
