//! Emits the mapped netlist as structural Verilog in **exactly** the
//! dialect `native/statime/src/netlist.rs` already parses --
//! `docs/design/synth-techmap-stage-contract.md` section 4/5: a flat
//! module, `input`/`output`/`wire` declarations, named-port (`.PIN(net)`)
//! technology-cell instances only, no `assign`, no concatenation, no
//! inline constants.

use std::collections::HashSet;
use std::fmt;

use crate::genlist::{GenericNetlist, PortDirection};
use crate::map::MappedInstance;

#[derive(Debug)]
pub struct VerilogError(pub String);

impl fmt::Display for VerilogError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.0)
    }
}

/// Render `port.bits` as a Verilog `input`/`output` declaration line.
/// Assumes (per the interim on-ramp converter, `tests/corpus/techmap/`)
/// a dense, zero-indexed bus: `bits.len()` bits numbered `bits.len()-1
/// downto 0` for anything wider than 1 bit -- matching every fixture this
/// crate's own corpus harness produces. A port whose `bits` don't follow
/// that convention still emits (each bit already carries its own literal
/// net name from the generic netlist), just without a compact `[msb:lsb]`
/// declaration -- see the `else` branch below.
///
/// Errors (rather than underflowing `bits.len() - 1`) on an empty `bits`
/// array -- `genlist::parse` doesn't reject one, so a malformed
/// generic-netlist JSON with a zero-width port is reachable here, not just
/// a defensive-coding nicety.
fn port_decl(name: &str, dir: &str, bits: &[String]) -> Result<String, VerilogError> {
    if bits.is_empty() {
        return Err(VerilogError(format!(
            "port '{name}' has an empty 'bits' array -- a port must declare at least one bit"
        )));
    }
    if bits.len() == 1 && bits[0] == name {
        Ok(format!("  {dir} {name};\n"))
    } else {
        let msb = bits.len() - 1;
        Ok(format!("  {dir} [{msb}:0] {name};\n"))
    }
}

pub fn write(
    netlist: &GenericNetlist,
    instances: &[MappedInstance],
) -> Result<String, VerilogError> {
    let mut out = String::new();
    out.push_str("/* Generated by klt-techmap (issue #874) */\n\n");

    let port_names: Vec<&str> = netlist.ports.iter().map(|p| p.name.as_str()).collect();
    out.push_str(&format!(
        "module {} ({});\n",
        netlist.top,
        port_names.join(", ")
    ));

    let mut port_bit_nets: HashSet<String> = HashSet::new();
    for port in &netlist.ports {
        let dir = match port.direction {
            PortDirection::Input => "input",
            PortDirection::Output => "output",
            PortDirection::Inout => "inout",
        };
        out.push_str(&port_decl(&port.name, dir, &port.bits)?);
        for b in &port.bits {
            port_bit_nets.insert(b.clone());
        }
    }

    let referenced = crate::map::referenced_nets(instances);
    let mut internal: Vec<&String> = referenced
        .iter()
        .filter(|n| !port_bit_nets.contains(*n))
        .collect();
    internal.sort();
    for net in &internal {
        out.push_str(&format!("  wire {net};\n"));
    }
    out.push('\n');

    for inst in instances {
        out.push_str(&format!("  {} {} (\n", inst.cell_type, inst.instance_name));
        let mut pins: Vec<&String> = inst.connections.keys().collect();
        pins.sort();
        let lines: Vec<String> = pins
            .iter()
            .map(|pin| format!("    .{pin}({})", inst.connections[*pin]))
            .collect();
        out.push_str(&lines.join(",\n"));
        out.push_str("\n  );\n");
    }

    out.push_str("endmodule\n");
    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::genlist::{GenericNetlist, Port};
    use std::collections::HashMap;

    #[test]
    fn emits_parseable_flat_module() {
        let netlist = GenericNetlist {
            schema: "klt.synth.generic-netlist/1".to_string(),
            top: "adder2".to_string(),
            ports: vec![
                Port {
                    name: "a".to_string(),
                    direction: PortDirection::Input,
                    bits: vec!["a[1]".into(), "a[0]".into()],
                },
                Port {
                    name: "y".to_string(),
                    direction: PortDirection::Output,
                    bits: vec!["y".into()],
                },
            ],
            cells: vec![],
        };
        let mut conns = HashMap::new();
        conns.insert("A".to_string(), "a[0]".to_string());
        conns.insert("B".to_string(), "a[1]".to_string());
        conns.insert("X".to_string(), "y".to_string());
        let instances = vec![MappedInstance {
            instance_name: "_g0_".to_string(),
            cell_type: "sky130_fd_sc_hd__and2_1".to_string(),
            connections: conns,
        }];
        let text = write(&netlist, &instances).unwrap();
        assert!(text.contains("module adder2 (a, y);"));
        assert!(text.contains("input [1:0] a;"));
        assert!(text.contains("output y;"));
        assert!(text.contains("sky130_fd_sc_hd__and2_1 _g0_ ("));
        assert!(text.contains(".A(a[0])"));
        assert!(text.contains("endmodule"));

        // This is a structural spot-check only (dialect shape, not a real
        // parse) -- this crate intentionally does not depend on
        // `native/statime` as a library (two independent spike crates, per
        // this repo's `native/<engine>/` convention), so it cannot invoke
        // that crate's actual parser from a unit test. The real end-to-end
        // check -- native/statime's `klt-statime` binary parsing this
        // crate's own generated mapped netlist unmodified -- runs in
        // `tests/corpus/techmap/compare.py` (contract section 5's
        // acceptance check, run for real against the corpus fixtures).
        let looks_like_the_shared_dialect = dialect_shape_check(&text, "adder2");
        assert!(looks_like_the_shared_dialect);
    }

    #[test]
    fn empty_bits_port_errs_instead_of_underflowing() {
        // A malformed generic-netlist JSON can declare a port with an
        // empty `bits` array (`genlist::parse` doesn't reject it) --
        // `port_decl` must return an `Err`, not underflow `bits.len() - 1`
        // (a `usize` panic in debug, a garbage `[huge:0]` decl in release).
        let netlist = GenericNetlist {
            schema: "klt.synth.generic-netlist/1".to_string(),
            top: "bad".to_string(),
            ports: vec![Port {
                name: "z".to_string(),
                direction: PortDirection::Input,
                bits: vec![],
            }],
            cells: vec![],
        };
        let result = write(&netlist, &[]);
        assert!(result.is_err());
    }

    /// Checks the structural properties `native/statime/src/netlist.rs`'s
    /// own doc comment requires of its input (`module NAME(...);`,
    /// `input`/`output`/`wire` decls, named-port instances, `endmodule`,
    /// no `assign`) -- a shape spot-check, not a substitute for the real
    /// parser run in `tests/corpus/techmap/compare.py`.
    fn dialect_shape_check(text: &str, top: &str) -> bool {
        text.contains(&format!("module {top} ("))
            && text.contains("endmodule")
            && text.contains(".A(")
            && !text.contains("assign ")
    }
}
