#!/usr/bin/env python3
"""Cyclomatic-complexity ratchet, not a ceiling (issue #2034, decomposed from
#2011 item 3).

`ruff`'s `C901` (mccabe cyclomatic complexity) rule is deliberately **not**
in `pyproject.toml`'s `[tool.ruff.lint]` `select` list, so plain `ruff check
.` never enforces it. Pinning a bare `max-complexity` to today's worst
offender would let every other function grow unchecked up to that ceiling,
and let every existing offender worsen right up to it -- a ceiling, not a
ratchet. This script is the ratchet:

1. `MAX_COMPLEXITY` (kept in sync with `pyproject.toml`'s own
   `[tool.ruff.lint.mccabe]` `max-complexity` by
   `tests/test_check_complexity_baseline.py`'s drift guard) is the target
   every *new* function must meet.
2. `complexity-baseline.json` (repo root) is the committed set of functions
   that already exceeded the target on the day this ratchet landed, each
   with its measured complexity -- generated by this exact script
   (`--update-baseline`), so local and CI numbers cannot drift apart.
3. Default (check) mode re-measures and fails when (a) a function *not* in
   the baseline exceeds `MAX_COMPLEXITY`, or (b) a baselined function's
   complexity has *increased* past its recorded value. A baselined function
   whose complexity decreases (or that disappears entirely -- renamed,
   refactored, deleted) does not fail: that is improvement, and the baseline
   is not required to be re-tightened on every touch (Builder discretion,
   per the issue).

Matching a violation to a baseline entry is by `(file, function name)`, not
by line number -- unrelated edits elsewhere in a file routinely shift line
numbers, and keying on them would make this ratchet fail on changes that
never touched the flagged function at all. `(file, function name)` is not
unique against nested/duplicate-named functions in the same file (rare and
none exist in this repo today, per this script's own tests); when it
happens, entries sharing a key are paired positionally after sorting both
sides ascending by complexity -- exact and cheap for the common case,
best-effort when a collision occurs.

Usage::

    # check current complexity against the committed baseline (CI's step)
    python scripts/check_complexity_baseline.py

    # regenerate the baseline file after intentionally reducing (or, with
    # reviewer sign-off, accepting a rise in) some function's complexity
    python scripts/check_complexity_baseline.py --update-baseline
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

# Kept in sync with pyproject.toml's [tool.ruff.lint.mccabe] max-complexity
# by tests/test_check_complexity_baseline.py -- see that test's docstring
# for why this is a plain duplicated constant rather than a runtime TOML
# read (tomllib is stdlib only from Python 3.11, and this project's floor is
# 3.10; see tests/test_design_evidence_tiers.py for the same tradeoff made
# elsewhere in this repo).
MAX_COMPLEXITY = 10

DEFAULT_BASELINE_PATH = REPO_ROOT / "complexity-baseline.json"
BASELINE_SCHEMA_VERSION = 1

_MESSAGE_RE = re.compile(
    r"^`(?P<name>.+)` is too complex \((?P<complexity>\d+) > \d+\)$"
)


@dataclass(frozen=True)
class Violation:
    file: str  # POSIX path, relative to REPO_ROOT
    function: str
    complexity: int
    line: int

    @property
    def key(self) -> tuple[str, str]:
        return (self.file, self.function)


def run_ruff_c901(
    *, max_complexity: int = MAX_COMPLEXITY, paths: list[str] | None = None
) -> list[Violation]:
    """Run `ruff check --select C901` over `paths` and parse its findings.

    This is the "exact same tool and config CI will enforce" the issue asks
    for: both `--update-baseline` and the default check call this same
    function, so baseline generation and enforcement can never see a
    different rule set.
    """
    paths = paths if paths is not None else ["."]
    result = subprocess.run(
        [
            "ruff",
            "check",
            "--select",
            "C901",
            "--output-format",
            "json",
            "--config",
            f"lint.mccabe.max-complexity={max_complexity}",
            *paths,
        ],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        check=False,
    )
    # ruff check exits 1 when it finds violations -- that is the expected,
    # successful outcome of this call, not an error. Only a missing binary
    # or a genuinely broken invocation (exit >= 2, or unparseable stdout)
    # should abort here.
    if result.returncode not in (0, 1):
        raise RuntimeError(
            f"ruff check --select C901 exited {result.returncode}\n"
            f"stdout: {result.stdout}\nstderr: {result.stderr}"
        )
    try:
        raw = json.loads(result.stdout)
    except json.JSONDecodeError as exc:
        raise RuntimeError(
            f"could not parse ruff's JSON output: {exc}\nstdout: {result.stdout}"
        ) from exc

    violations = []
    for entry in raw:
        match = _MESSAGE_RE.match(entry["message"])
        if not match:
            raise RuntimeError(
                f"unrecognized C901 message format: {entry['message']!r}"
            )
        file_path = Path(entry["filename"]).resolve().relative_to(REPO_ROOT)
        violations.append(
            Violation(
                file=file_path.as_posix(),
                function=match.group("name"),
                complexity=int(match.group("complexity")),
                line=entry["location"]["row"],
            )
        )
    return sorted(violations, key=lambda v: (v.file, v.line, v.function))


def _group_by_key(violations: list[Violation]) -> dict[tuple[str, str], list[int]]:
    grouped: dict[tuple[str, str], list[int]] = {}
    for v in violations:
        grouped.setdefault(v.key, []).append(v.complexity)
    return grouped


def load_baseline(path: Path) -> dict[tuple[str, str], list[int]]:
    if not path.exists():
        return {}
    data = json.loads(path.read_text(encoding="utf-8"))
    grouped: dict[tuple[str, str], list[int]] = {}
    for entry in data.get("violations", []):
        key = (entry["file"], entry["function"])
        grouped.setdefault(key, []).append(entry["complexity"])
    return grouped


def write_baseline(
    path: Path, violations: list[Violation], *, max_complexity: int = MAX_COMPLEXITY
) -> None:
    ruff_version = subprocess.run(
        ["ruff", "--version"], capture_output=True, text=True, check=True
    ).stdout.strip()
    data = {
        "schema_version": BASELINE_SCHEMA_VERSION,
        "max_complexity": max_complexity,
        "generated_by": (
            f"scripts/check_complexity_baseline.py --update-baseline ({ruff_version})"
        ),
        "violations": [
            {"file": v.file, "function": v.function, "complexity": v.complexity}
            for v in sorted(violations, key=lambda v: (v.file, v.function))
        ],
    }
    path.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")


@dataclass(frozen=True)
class ComparisonResult:
    new_violations: list[tuple[str, str, int]]  # (file, function, complexity)
    regressions: list[tuple[str, str, int, int]]  # (file, function, baseline, current)
    improved_or_removed: (
        int  # count of baselined entries not worse (informational only)
    )

    @property
    def ok(self) -> bool:
        return not self.new_violations and not self.regressions


def compare(
    current: list[Violation], baseline: dict[tuple[str, str], list[int]]
) -> ComparisonResult:
    current_grouped = _group_by_key(current)
    new_violations: list[tuple[str, str, int]] = []
    regressions: list[tuple[str, str, int, int]] = []
    improved_or_removed = 0

    for key, curr_list in current_grouped.items():
        base_list = sorted(baseline.get(key, []))
        curr_sorted = sorted(curr_list)
        for i, curr_complexity in enumerate(curr_sorted):
            if i < len(base_list):
                base_complexity = base_list[i]
                if curr_complexity > base_complexity:
                    regressions.append(
                        (key[0], key[1], base_complexity, curr_complexity)
                    )
            else:
                new_violations.append((key[0], key[1], curr_complexity))

    for key, base_list in baseline.items():
        curr_list = sorted(current_grouped.get(key, []))
        base_sorted = sorted(base_list)
        for i, base_complexity in enumerate(base_sorted):
            if i >= len(curr_list) or curr_list[i] <= base_complexity:
                improved_or_removed += 1

    new_violations.sort()
    regressions.sort()
    return ComparisonResult(
        new_violations=new_violations,
        regressions=regressions,
        improved_or_removed=improved_or_removed,
    )


def _fail(summary: str) -> None:
    print(f"::error::{summary}", file=sys.stderr)
    print(summary, file=sys.stderr)


def _cmd_check(args: argparse.Namespace) -> int:
    current = run_ruff_c901(max_complexity=args.max_complexity, paths=args.paths)
    baseline = load_baseline(args.baseline)
    result = compare(current, baseline)

    if result.new_violations:
        _fail(
            f"{len(result.new_violations)} function(s) exceed max-complexity="
            f"{args.max_complexity} and are not in {args.baseline.name}:"
        )
        for file, function, complexity in result.new_violations:
            print(
                f"  {file}: `{function}` is too complex "
                f"({complexity} > {args.max_complexity})"
            )
        print(
            "\nIf this is new code, reduce its complexity. If accepting it is "
            "the right call for now, add it to the baseline with:\n"
            "  python scripts/check_complexity_baseline.py --update-baseline",
            file=sys.stderr,
        )

    if result.regressions:
        _fail(f"{len(result.regressions)} baselined function(s) got MORE complex:")
        for file, function, base, curr in result.regressions:
            print(f"  {file}: `{function}` complexity rose from {base} to {curr}")
        print(
            "\nReduce the complexity back to (or below) the baselined value, "
            "or -- with reviewer sign-off -- update the baseline:\n"
            "  python scripts/check_complexity_baseline.py --update-baseline",
            file=sys.stderr,
        )

    if not result.ok:
        return 1

    entry_word = "entry is" if result.improved_or_removed == 1 else "entries are"
    print(
        f"OK: no function exceeds max-complexity={args.max_complexity} outside "
        f"the {len(baseline)} entries baselined in {args.baseline.name} "
        f"({result.improved_or_removed} baselined {entry_word} at or below "
        "their recorded value)."
    )
    return 0


def _cmd_update_baseline(args: argparse.Namespace) -> int:
    current = run_ruff_c901(max_complexity=args.max_complexity, paths=args.paths)
    write_baseline(args.baseline, current, max_complexity=args.max_complexity)
    print(
        f"Wrote {len(current)} violation(s) to {args.baseline} "
        f"(max-complexity={args.max_complexity})."
    )
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "paths",
        nargs="*",
        default=["."],
        help="paths to scan, relative to the repo root (default: '.', the whole repo)",
    )
    default_baseline_display = DEFAULT_BASELINE_PATH.relative_to(REPO_ROOT)
    parser.add_argument(
        "--baseline",
        type=Path,
        default=DEFAULT_BASELINE_PATH,
        help=f"baseline JSON file path (default: {default_baseline_display})",
    )
    parser.add_argument(
        "--max-complexity",
        type=int,
        default=MAX_COMPLEXITY,
        help=f"target max-complexity threshold (default: {MAX_COMPLEXITY})",
    )
    parser.add_argument(
        "--update-baseline",
        action="store_true",
        help=(
            "regenerate the baseline file from the current measured "
            "complexity, instead of checking it"
        ),
    )
    args = parser.parse_args(argv)

    if args.update_baseline:
        return _cmd_update_baseline(args)
    return _cmd_check(args)


if __name__ == "__main__":
    raise SystemExit(main())
