#!/usr/bin/env python3
"""Feasibility harness for Icarus `$sdf_annotate` against this repo's own
gate-level cocotb testbench convention (issue #962, Epic #700 Phase 3,
`docs/design/post-route-sta-survey.md` §4.3).

This is the *measurement* half of the spike whose written finding lives in
[`docs/design/sdf-annotate-feasibility-spike.md`](../../docs/design/sdf-annotate-feasibility-spike.md).
It exists so the Go verdict recorded there is reproducible rather than
recalled: run this script and you get the same table the doc quotes.

What it does, for one design, with **one testbench module held fixed**:

1. Runs the cocotb regression against the original RTL (the baseline every
   `examples/functional-verification/` request already exercises).
2. Runs the *same* regression against that design's synthesized gate-level
   netlist plus the PDK's own Verilog cell models -- zero-delay, i.e.
   exactly what `klt functional-verification` produces today when `sources`
   points at `klt synthesize`'s `netlist_path`
   (`docs/cli/functional-verification.md:175`).
3. Runs the same regression again, gate-level, with a **synthetic** SDF
   back-annotated through Icarus's `$sdf_annotate`, once per requested
   per-stage delay -- the `write_sdf` half of §4.3 is deliberately *not*
   exercised here (that is the follow-on this spike's result gates), so the
   SDF is generated by :func:`generate_sdf` below rather than by OpenSTA.

The point of step 3's delay sweep is the coverage metric §4.3 actually
names: *does the testbench's own pass/fail outcome change once real delay
is present?* A per-stage delay small enough to fit the testbench's clock
period must leave every verdict unchanged; one large enough to bust it must
flip passing tests to failing. A harness that only ever shows "still
passes" cannot distinguish a working annotation from a silently-skipped
one -- which is the specific trap Icarus sets here (see
``--fail-on-sdf-diagnostics`` below).

Requirements on the host (none of them CI-provisioned -- this is a
deliberate operator-run study, the same posture as
`tests/corpus/statime/regenerate.sh`):

- `iverilog`/`vvp` on `$PATH` (Icarus Verilog; verified against 13.0).
- cocotb installed in the running interpreter
  (`uv sync --extra functional-verification`, or `pip install cocotb`).
- A real PDK install carrying the cell library's **Verilog** models
  (`libs.ref/<library>/verilog/`) -- e.g. a volare-fetched `sky130A`.
  Resolved through `klayout_tools.pdk.find_pdk`, the same discovery order
  `klt synthesize` uses.

Usage (from the repo root)::

    PDK=sky130A uv run --python 3.12 --extra functional-verification python \\
        scripts/research/sdf_annotate_spike.py --format text \\
        --fail-on-sdf-diagnostics

    # or point it at another design/testbench triple:
    PDK=sky130A uv run --python 3.12 --extra functional-verification python \\
        scripts/research/sdf_annotate_spike.py \\
        --rtl examples/functional-verification/modexp.v \\
        --netlist tests/corpus/statime/modexp_netlist.v \\
        --hdl-toplevel modexp --testbench-module test_modexp \\
        --testbench-dir examples/functional-verification

``--python 3.12`` is not incidental: `pyproject.toml`'s
``functional-verification`` extra marks cocotb ``python_version < "3.14"``
(cocotb 2.0.1 caps at Python 3.13), so resolving under a 3.14 default
interpreter silently omits cocotb and this script exits with a clear
"cocotb is not installed" error.

`--format json` emits the whole result set as one JSON document, in the
same shape the spike doc's own tables were built from.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
import xml.etree.ElementTree as ElementTree
from typing import Any

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

#: Output pin names across the sky130/gf180 standard-cell conventions. Any
#: instance pin *not* in this set is treated as an input when
#: :func:`generate_sdf` synthesizes IOPATH entries. This is a property of
#: the cell libraries this repo already targets, not a general Verilog
#: fact -- a library with different pin conventions needs this extended.
OUTPUT_PINS = frozenset(
    {"X", "Y", "Q", "Q_N", "COUT", "COUT_N", "SUM", "HI", "LO", "Z", "ZN"}
)

#: Sequential-cell arc sources, mapped to the edge that qualifies them.
#:
#: A cell carrying any of these pins is sequential, and the *only* IOPATHs
#: its ``specify`` block declares are these edge-qualified ones -- sky130's
#: ``dfrtp_1``, for instance, declares exactly ``(posedge CLK => Q)`` and
#: ``(negedge RESET_B => Q)``. Its ``D`` pin reaches ``Q`` through
#: ``$setuphold`` timing checks, never through a delay path, so synthesizing
#: a ``D -> Q`` IOPATH for it produces a run-time ``SDF ERROR: Unable to
#: match ModPath`` per flop -- the annotation for that cell is then dropped
#: while the run still reports PASS. (Observed live before this map existed:
#: 50 such errors on `gcd`'s 50 flops.)
EDGE_ARC_PINS = {
    "CLK": "posedge",
    "GATE": "posedge",
    "GCLK": "posedge",
    "CLK_N": "negedge",
    "GATE_N": "negedge",
    "RESET_B": "negedge",
    "SET_B": "negedge",
}

#: Cell-instance matcher for a Yosys `write_verilog` netlist: a cell type,
#: an instance name, and a parenthesised connection list.
_INSTANCE_RE = re.compile(
    r"^\s*([A-Za-z_]\w*)\s+(\\?\S+)\s*\(([^;]*?)\)\s*;", re.M | re.S
)
_PIN_RE = re.compile(r"\.(\w+)\s*\(")

#: Icarus reports every SDF problem it hits (unopenable file, unmatched
#: instance, unmatched path, ignored `$sdf_annotate` argument) on its own
#: transcript with one of these prefixes -- and then **carries on and exits
#: 0**. Scanning for them is therefore not a nicety: it is the only thing
#: standing between "the SDF was applied" and "the SDF was silently
#: skipped and the run reported PASS at zero delay."
SDF_DIAGNOSTIC_MARKERS = ("SDF WARNING", "SDF ERROR")

#: The `iverilog` flags SDF back-annotation actually requires. Without
#: `-gspecify`, Icarus omits every specify block *and* `$sdf_annotate`
#: itself (it says so, on stderr, and then runs zero-delay). Without
#: `-ginterconnect`, an SDF carrying INTERCONNECT entries -- which OpenSTA's
#: own `write_sdf` emits -- fails per-entry at run time with `SDF ERROR:
#: Could not find intermodpath!`.
SDF_BUILD_FLAGS = ("-gspecify", "-ginterconnect")


class SpikeError(Exception):
    """Anything that stops the harness producing a trustworthy comparison."""


# ---------------------------------------------------------------------------
# synthetic SDF generation (stands in for OpenSTA's `write_sdf`, out of scope)
# ---------------------------------------------------------------------------


def parse_instances(netlist_path: str, cell_prefix: str) -> list[dict[str, Any]]:
    """Extract ``[{celltype, instance, inputs, outputs}]`` from a Yosys
    ``write_verilog`` gate-level netlist.

    ``cell_prefix`` filters to the standard-cell library of interest
    (e.g. ``sky130_fd_sc_hd__``) so the netlist's own module header and any
    non-library instances are skipped.
    """
    try:
        with open(netlist_path, encoding="utf-8") as handle:
            text = handle.read()
    except OSError as exc:
        raise SpikeError(f"could not read netlist '{netlist_path}': {exc}") from exc

    cells: list[dict[str, Any]] = []
    for celltype, instance, body in _INSTANCE_RE.findall(text):
        if not celltype.startswith(cell_prefix):
            continue
        pins = _PIN_RE.findall(body)
        if not pins:
            continue
        cells.append(
            {
                "celltype": celltype,
                "instance": instance,
                "inputs": [pin for pin in pins if pin not in OUTPUT_PINS],
                "outputs": [pin for pin in pins if pin in OUTPUT_PINS],
            }
        )
    if not cells:
        raise SpikeError(
            f"no '{cell_prefix}*' instances found in '{netlist_path}' -- is this "
            "a gate-level netlist mapped to that cell library?"
        )
    return cells


def generate_sdf(cells: list[dict[str, Any]], *, design: str, delay_ns: float) -> str:
    """A synthetic IEEE-1497 SDF assigning the *same* ``delay_ns`` to every
    cell arc in ``cells``.

    Deliberately uniform: this spike is testing whether Icarus *applies* an
    SDF against this repo's testbench convention, not whether any particular
    delay model is accurate. Producing a physically meaningful SDF is
    `write_sdf`'s job (survey §4.3, explicitly out of scope here), and a
    uniform per-stage delay makes the sweep's threshold interpretable as
    "logic depth x delay vs. clock period" rather than an opaque number.
    """
    triplet = f"({delay_ns:.3f}:{delay_ns:.3f}:{delay_ns:.3f})"
    lines = [
        "(DELAYFILE",
        '  (SDFVERSION "3.0")',
        f'  (DESIGN "{design}")',
        '  (VENDOR "klayout-tools sdf_annotate spike (issue #962)")',
        '  (PROGRAM "scripts/research/sdf_annotate_spike.py")',
        '  (VERSION "1.0")',
        "  (DIVIDER .)",
        "  (TIMESCALE 1ns)",
    ]
    for cell in cells:
        sequential_sources = [pin for pin in cell["inputs"] if pin in EDGE_ARC_PINS]
        paths = []
        for out_pin in cell["outputs"]:
            if sequential_sources:
                sources = [
                    f"({EDGE_ARC_PINS[pin]} {pin})" for pin in sequential_sources
                ]
            else:
                sources = list(cell["inputs"])
            for source in sources:
                paths.append(f"      (IOPATH {source} {out_pin} {triplet} {triplet})")
        if not paths:
            continue
        lines += [
            "  (CELL",
            f'    (CELLTYPE "{cell["celltype"]}")',
            f"    (INSTANCE {cell['instance']})",
            "    (DELAY (ABSOLUTE",
            *paths,
            "    ))",
            "  )",
        ]
    lines.append(")")
    return "\n".join(lines) + "\n"


def write_annotate_shim(path: str, *, sdf_path: str, hdl_toplevel: str) -> None:
    """Write the extra *root* module that carries the ``$sdf_annotate`` call.

    This is the load-bearing trick the spike establishes. A cocotb
    regression has no Verilog testbench module -- ``hdl_toplevel`` *is* the
    DUT, driven from Python -- so there is nowhere in the existing
    convention to put an ``initial $sdf_annotate(...)``. Elaborating a
    second, otherwise-empty root module alongside the DUT (``iverilog -s
    <toplevel> -s <shim>``) supplies one without touching the netlist, the
    testbench, or the DUT's own hierarchy, so ``dut.<port>`` handles in the
    Python testbench keep resolving exactly as before.

    cocotb itself already uses this exact shape for waveform dumping (its
    generated ``cocotb_iverilog_dump`` module, added with a second ``-s``),
    so this is the simulator-runner's own idiom rather than a new one.
    """
    with open(path, "w", encoding="utf-8") as handle:
        handle.write(
            "// Generated by scripts/research/sdf_annotate_spike.py -- do not edit.\n"
            "// Extra elaboration root carrying the $sdf_annotate call, since a\n"
            "// cocotb regression's hdl_toplevel is the DUT itself.\n"
            "module klt_sdf_annotate();\n"
            f'  initial $sdf_annotate("{sdf_path}", {hdl_toplevel});\n'
            "endmodule\n"
        )


# ---------------------------------------------------------------------------
# one regression run
# ---------------------------------------------------------------------------


def run_regression(
    *,
    label: str,
    sources: list[str],
    build_args: list[str],
    hdl_toplevel: str,
    testbench_module: str,
    testbench_dir: str,
    work_dir: str,
    timescale: tuple[str, str],
    random_seed: int | None,
) -> dict[str, Any]:
    """Drive one cocotb regression and return its per-test verdicts.

    Deliberately mirrors ``klayout_tools.functional_verification``'s own
    invocation shape -- cocotb's first-party ``Runner`` API, ``always=True``,
    ``timescale`` passed to *both* ``build()`` and ``test()``, the verdict
    read from the parsed ``results.xml`` and never from an exit code -- so a
    finding here transfers to that module without a translation step. The
    one thing it adds is ``build_args``, which that module does not expose
    today (see the spike doc's "What the wiring needs" section).
    """
    try:
        from cocotb_tools.runner import get_runner
    except ImportError as exc:  # pragma: no cover - operator-run script
        raise SpikeError(
            f"cocotb is not installed (import failed: {exc}) -- run this under "
            "`uv run --extra functional-verification`"
        ) from exc

    build_dir = os.path.join(work_dir, f"build_{label}")
    results_xml = os.path.join(work_dir, f"results_{label}.xml")
    build_log = os.path.join(work_dir, f"build_{label}.log")
    test_log = os.path.join(work_dir, f"test_{label}.log")

    runner = get_runner("icarus")
    runner.build(
        sources=sources,
        hdl_toplevel=hdl_toplevel,
        build_dir=build_dir,
        build_args=build_args,
        always=True,
        timescale=timescale,
        log_file=build_log,
    )

    inserted = testbench_dir not in sys.path
    if inserted:
        sys.path.insert(0, testbench_dir)
    try:
        runner.test(
            test_module=testbench_module,
            hdl_toplevel=hdl_toplevel,
            hdl_toplevel_lang="verilog",
            seed=random_seed,
            build_dir=build_dir,
            test_dir=work_dir,
            results_xml=results_xml,
            timescale=timescale,
            log_file=test_log,
        )
    except (SystemExit, subprocess.CalledProcessError):
        # Expected on a failing regression -- results.xml is the truth.
        pass
    finally:
        if inserted:
            sys.path.remove(testbench_dir)

    return {
        "label": label,
        "build_args": list(build_args),
        "tests": _parse_results(results_xml),
        "sdf_diagnostics": _scan_sdf_diagnostics(build_log)
        + _scan_sdf_diagnostics(test_log),
        "timing_check_warnings": _count_timing_check_warnings(build_log),
        "results_xml": results_xml,
    }


def _parse_results(results_xml: str) -> list[dict[str, Any]]:
    if not os.path.isfile(results_xml):
        raise SpikeError(
            f"run produced no '{results_xml}' -- the regression did not complete"
        )
    tests = []
    for testcase in ElementTree.parse(results_xml).iter("testcase"):
        failure = testcase.find("failure")
        skipped = testcase.find("skipped")
        status = (
            "failed"
            if failure is not None
            else ("skipped" if skipped is not None else "passed")
        )
        tests.append(
            {
                "name": testcase.get("name"),
                "status": status,
                "sim_time_ns": testcase.get("sim_time_ns"),
            }
        )
    if not tests:
        raise SpikeError(f"'{results_xml}' registered no tests -- nothing was verified")
    return tests


def _scan_sdf_diagnostics(log_path: str) -> list[str]:
    """Every ``SDF WARNING``/``SDF ERROR`` line Icarus emitted. Non-empty
    means the annotation did not fully apply, regardless of the run's own
    pass/fail verdict."""
    try:
        with open(log_path, encoding="utf-8", errors="replace") as handle:
            return [
                line.strip()
                for line in handle
                if any(marker in line for marker in SDF_DIAGNOSTIC_MARKERS)
            ]
    except OSError:
        return []


def _count_timing_check_warnings(log_path: str) -> int:
    """How many ``$setup``/``$hold``/``$width`` timing checks Icarus declined
    to implement in this elaboration -- the headline *limitation* of this
    path, quantified rather than asserted."""
    try:
        with open(log_path, encoding="utf-8", errors="replace") as handle:
            return sum(
                1 for line in handle if "Timing checks are not supported" in line
            )
    except OSError:
        return 0


# ---------------------------------------------------------------------------
# entry point
# ---------------------------------------------------------------------------


def resolve_cell_verilog(
    *, cell_library: str, pdk_variant: str | None, pdk_root: str | None
) -> list[str]:
    """The PDK's own Verilog simulation models for ``cell_library``, in
    compile order (primitives first).

    These carry the ``specify`` blocks whose all-zero placeholder delays
    (``(A =>  X) = (0:0:0, 0:0:0);``) SDF back-annotation overwrites -- the
    reason a gate-level sim can be zero-delay and SDF-annotated from the
    *same* model files.
    """
    from klayout_tools.pdk import PdkNotFoundError, find_pdk

    try:
        payload = find_pdk(pdk_variant, pdk_root)
    except PdkNotFoundError as exc:
        raise SpikeError(str(exc)) from exc

    libs_ref = payload["assets"].get("libs_ref")
    if not libs_ref:
        raise SpikeError(
            f"PDK '{payload['variant']}' at {payload['root']} ships no libs.ref/ "
            "-- no Verilog cell models to simulate against"
        )
    verilog_dir = os.path.join(libs_ref, cell_library, "verilog")
    models = [
        os.path.join(verilog_dir, "primitives.v"),
        os.path.join(verilog_dir, f"{cell_library}.v"),
    ]
    missing = [path for path in models if not os.path.isfile(path)]
    if missing:
        raise SpikeError(
            "PDK install is missing the cell-library Verilog models this spike "
            f"needs: {', '.join(missing)}"
        )
    return models


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--rtl",
        default=os.path.join(REPO_ROOT, "examples/functional-verification/gcd.v"),
        help="original RTL source (the baseline run)",
    )
    parser.add_argument(
        "--netlist",
        default=os.path.join(REPO_ROOT, "tests/corpus/statime/gcd_netlist.v"),
        help="gate-level netlist (klt synthesize's netlist_path convention)",
    )
    parser.add_argument("--hdl-toplevel", default="gcd")
    parser.add_argument("--testbench-module", default="test_gcd")
    parser.add_argument(
        "--testbench-dir",
        default=os.path.join(REPO_ROOT, "examples/functional-verification"),
        help="directory containing <testbench-module>.py",
    )
    parser.add_argument("--cell-library", default="sky130_fd_sc_hd")
    parser.add_argument("--cell-prefix", default=None, help="default: <cell-library>__")
    parser.add_argument("--pdk", default=os.environ.get("PDK", "sky130A"))
    parser.add_argument("--pdk-root", default=None)
    parser.add_argument(
        "--delay-ns",
        type=float,
        nargs="+",
        default=[0.1, 0.5, 0.7, 0.9, 2.0],
        help="per-stage SDF delays to sweep (one annotated run each)",
    )
    parser.add_argument("--random-seed", type=int, default=1)
    parser.add_argument(
        "--work-dir", default=None, help="default: a fresh temporary directory"
    )
    parser.add_argument(
        "--fail-on-sdf-diagnostics",
        action="store_true",
        help=(
            "exit nonzero if any annotated run emitted an SDF WARNING/ERROR "
            "(recommended: Icarus keeps going and exits 0 after skipping an "
            "annotation, so a clean-looking PASS can mean nothing was applied)"
        ),
    )
    parser.add_argument("--format", choices=("text", "json"), default="text")
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)

    if shutil.which("iverilog") is None:
        print("ERROR: iverilog not found on $PATH", file=sys.stderr)
        return 1

    cell_prefix = args.cell_prefix or f"{args.cell_library}__"
    work_dir = args.work_dir or tempfile.mkdtemp(prefix="klt-sdf-spike-")
    os.makedirs(work_dir, exist_ok=True)

    try:
        models = resolve_cell_verilog(
            cell_library=args.cell_library, pdk_variant=args.pdk, pdk_root=args.pdk_root
        )
        cells = parse_instances(args.netlist, cell_prefix)

        common = {
            "hdl_toplevel": args.hdl_toplevel,
            "testbench_module": args.testbench_module,
            "testbench_dir": os.path.abspath(args.testbench_dir),
            "work_dir": work_dir,
            "timescale": ("1ns", "1ps"),
            "random_seed": args.random_seed,
        }

        runs = [
            run_regression(label="rtl", sources=[args.rtl], build_args=[], **common),
            run_regression(
                label="gate-level",
                sources=[args.netlist, *models],
                build_args=[],
                **common,
            ),
            # Control isolating the build flags from the annotation itself:
            # the PDK's own specify blocks carry all-zero placeholder delays,
            # so enabling them without an SDF must leave every verdict
            # identical to the zero-delay run. Any change here would mean the
            # sweep below is measuring `-gspecify`, not `$sdf_annotate`.
            run_regression(
                label="gl+specify",
                sources=[args.netlist, *models],
                build_args=list(SDF_BUILD_FLAGS),
                **common,
            ),
        ]
        for delay_ns in args.delay_ns:
            tag = f"{delay_ns:.3f}".replace(".", "p")
            sdf_path = os.path.join(work_dir, f"annotate_{tag}.sdf")
            shim_path = os.path.join(work_dir, f"shim_{tag}.v")
            with open(sdf_path, "w", encoding="utf-8") as handle:
                handle.write(
                    generate_sdf(cells, design=args.hdl_toplevel, delay_ns=delay_ns)
                )
            write_annotate_shim(
                shim_path, sdf_path=sdf_path, hdl_toplevel=args.hdl_toplevel
            )
            runs.append(
                run_regression(
                    label=f"sdf-{tag}",
                    sources=[args.netlist, shim_path, *models],
                    build_args=[*SDF_BUILD_FLAGS, "-s", "klt_sdf_annotate"],
                    **common,
                )
            )

        payload = {
            "design": args.hdl_toplevel,
            "netlist": os.path.abspath(args.netlist),
            "cell_library": args.cell_library,
            "cell_instances": len(cells),
            "iverilog_version": _iverilog_version(),
            "work_dir": work_dir,
            "runs": runs,
        }
    except SpikeError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1

    if args.format == "json":
        print(json.dumps(payload, indent=2))
    else:
        _print_text(payload)

    if args.fail_on_sdf_diagnostics:
        noisy = [
            run
            for run in runs
            if run["label"].startswith("sdf-") and run["sdf_diagnostics"]
        ]
        if noisy:
            for run in noisy:
                for line in run["sdf_diagnostics"]:
                    print(f"SDF diagnostic in {run['label']}: {line}", file=sys.stderr)
            return 1
    return 0


def _iverilog_version() -> str | None:
    try:
        completed = subprocess.run(["iverilog", "-V"], capture_output=True, text=True)
    except OSError:
        return None
    match = re.search(
        r"Icarus Verilog version (\S+)", completed.stdout + completed.stderr
    )
    return match.group(1) if match else None


def _print_text(payload: dict[str, Any]) -> None:
    print(
        f"design={payload['design']} netlist={payload['netlist']} "
        f"cells={payload['cell_instances']} iverilog={payload['iverilog_version']}"
    )
    print(f"artifacts: {payload['work_dir']}")
    names = [test["name"] for test in payload["runs"][0]["tests"]]
    width = max(len(name) for name in names)
    header = "run".ljust(14) + "  " + "  ".join(name.ljust(width) for name in names)
    print()
    print(header + "  sdf-diags  no-timing-check")
    print("-" * len(header) + "  ---------  ---------------")
    for run in payload["runs"]:
        verdicts = {test["name"]: test["status"] for test in run["tests"]}
        row = (
            run["label"].ljust(14)
            + "  "
            + "  ".join(verdicts.get(name, "-").ljust(width) for name in names)
        )
        diags = len(run["sdf_diagnostics"])
        print(f"{row}  {diags:>9}  {run['timing_check_warnings']:>15}")


if __name__ == "__main__":  # pragma: no cover - operator-run script
    raise SystemExit(main())
