"""Resolve klt's built-in DRC/LVS rule decks by content hash or by
``(name, version)`` against a release-time-generated history table
(issue #623).

A repo verifying committed DRC evidence sometimes needs to reproduce a
report against a *specific past revision* of a built-in rule deck --
``provenance.deck.content_hash`` (``docs/json-contract.md``) pins exactly
which bytes produced a "clean" verdict, but on its own there was previously
no tool-level way to turn that hash back into "what do I `pip install` (or
`git checkout` + build) to reproduce it" other than hand-bisecting this
repo's own git history. This module is the pure-lookup half of that fix
(``cli/deck_cmd.py`` wires it to ``klt deck resolve``); the actual
regeneration of the table lives in ``scripts/generate_deck_history.py`` at
the repo root -- see that script's docstring for how/when it runs.

This is deliberately **resolve-only**: it never fetches, checks out, or
builds a historical revision in-process (see issue #623's "Suggested
capability" -- that would need a git-clone-and-checkout-on-demand mechanism
with no precedent in this codebase, and re-introduces exactly the
"needs the invoking environment to already have the full git history"
friction the issue exists to eliminate). The caller still runs
``pip install klayout-tools==X.Y.Z`` (or checks out the reported tag and
builds it) themselves.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:  # pragma: no cover - typing only
    from .rules import DrcRule

#: Generated by ``scripts/generate_deck_history.py`` -- see that script's
#: module docstring. Never hand-edited.
_HISTORY_PATH = Path(__file__).resolve().parent / "_history.json"


class DeckHistoryError(Exception):
    """Raised by :func:`resolve_deck` for an invalid query (neither
    ``content_hash`` nor a complete ``deck``+``version`` pair given) or a
    query that matches no entry in the generated history table.

    ``cli/deck_cmd.py`` turns this into the documented error envelope
    (``docs/json-contract.md``) -- a clean message and exit code 1, never a
    traceback.
    """


def _load_history() -> dict[str, Any]:
    try:
        raw = _HISTORY_PATH.read_text()
    except OSError as exc:
        raise DeckHistoryError(
            f"deck history table not found or unreadable: {_HISTORY_PATH} ({exc})"
        ) from exc
    try:
        data = json.loads(raw)
    except json.JSONDecodeError as exc:
        raise DeckHistoryError(
            f"deck history table is not valid JSON: {_HISTORY_PATH} ({exc})"
        ) from exc
    if not isinstance(data, dict) or not isinstance(data.get("entries"), list):
        raise DeckHistoryError(
            f"deck history table is malformed (missing 'entries' list): {_HISTORY_PATH}"
        )
    return data


def known_deck_names() -> list[str]:
    """Every deck name the history table has at least one entry for,
    sorted -- used to build a helpful "not found" message."""
    entries = _load_history()["entries"]
    return sorted({str(entry.get("deck")) for entry in entries})


def resolve_deck(
    *,
    content_hash: str | None = None,
    deck: str | None = None,
    version: str | None = None,
) -> dict[str, Any]:
    """Resolve a deck query against the generated history table.

    Two mutually available query shapes (issue #623's acceptance criteria):

    - ``content_hash`` (a ``sha256:<hex>`` string, matching
      ``provenance.deck.content_hash``'s shape) alone, optionally narrowed
      by ``deck``. When more than one release shipped byte-identical deck
      content (the deck simply didn't change between releases), the *newest*
      matching release is returned -- so resolving the currently-installed
      build's own deck hash against its own from-source history always
      reports back that same currently-running version, never a stale
      earlier one that happened to ship the same bytes first.
    - ``deck`` and ``version`` together, an exact ``(name, package_version)``
      lookup.

    Raises :class:`DeckHistoryError` for an incomplete/invalid query, or one
    that matches no entry (a hash that predates the table's start, was never
    released, or a ``deck``/``version`` combination that never shipped) --
    never returns a null/empty match silently.
    """
    if content_hash is None and (deck is None or version is None):
        raise DeckHistoryError(
            "klt deck resolve requires either --content-hash, or both "
            "--deck and --version"
        )

    entries = _load_history()["entries"]

    if content_hash is not None:
        candidates = [e for e in entries if e.get("content_hash") == content_hash]
        if deck is not None:
            candidates = [e for e in candidates if e.get("deck") == deck]
        if not candidates:
            raise DeckHistoryError(
                _not_found_message(content_hash=content_hash, deck=deck)
            )
        # Newest release last (the table is generated in ascending git-tag
        # order -- see generate_deck_history.py); picking the last match
        # reports the currently-running version when the deck hasn't
        # changed since an earlier release also shipped this exact hash.
        match = candidates[-1]
    else:
        candidates = [
            e
            for e in entries
            if e.get("deck") == deck and e.get("package_version") == version
        ]
        if not candidates:
            raise DeckHistoryError(_not_found_message(deck=deck, version=version))
        match = candidates[-1]

    return {
        "schema_version": 1,
        "query": {"content_hash": content_hash, "deck": deck, "version": version},
        "deck": match["deck"],
        "content_hash": match["content_hash"],
        "git_tag": match["git_tag"],
        "git_commit": match["git_commit"],
        "package_version": match["package_version"],
    }


def is_deck_hash_released(deck: str | None, content_hash: str | None) -> bool | None:
    """Whether ``content_hash`` (optionally narrowed to ``deck``) appears in
    the generated deck history table -- the release-tracking half of the
    ``provenance.deck.released`` signal (issue #1193).

    A "clean" report against a deck content hash with no released
    counterpart is unreproducible evidence the moment it's committed, but
    nothing said so at generation time -- this turns that into a checkable
    fact alongside ``provenance.deck.content_hash`` itself, without making a
    generation-time run *fail* over it (the deck still ran; a dev checkout,
    an uncommitted deck edit, or a deck added after the last tag are all
    ordinary, not errors).

    Returns:
        ``True`` -- ``content_hash`` matches at least one history entry
            (narrowed to ``deck`` when given).
        ``False`` -- the history table loaded fine but no entry matches; the
            hash is confirmed *not* released (predates the table, an
            unreleased/dev build, or a deck added after the last tag).
        ``None`` -- the answer can't be determined: ``content_hash`` is
            falsy (nothing to look up), or the history table itself is
            missing, unreadable, or malformed. Deliberately distinct from
            ``False`` -- callers must never turn "couldn't check" into a
            "confirmed unresolvable" claim (see this function's docstring
            and issue #1193's edge-case requirement that a missing/broken
            history table degrade gracefully rather than fabricate a
            warning).
    """
    if not content_hash:
        return None
    try:
        entries = _load_history()["entries"]
    except DeckHistoryError:
        return None
    candidates = [e for e in entries if e.get("content_hash") == content_hash]
    if deck is not None:
        candidates = [e for e in candidates if e.get("deck") == deck]
    return bool(candidates)


def deck_info(name: str | None = None) -> dict[str, Any]:
    """The *currently installed* build's own deck content hash, structural
    device-class coverage, and release status -- without running a live
    extraction against any input layout (issue #1209).

    ``klt deck resolve``/``provenance.deck.content_hash`` (issue #1193's
    ``released`` flag) both require a caller to already *have* a content
    hash in hand -- normally obtained by running ``klt extract``/``drc``/
    ``lvs`` against some input layout and reading it out of the buried
    ``provenance`` block of the JSON report. That is exactly the gap that
    let PyPI's ``klayout-tools==0.2.0`` ship a ``gf180mcu`` deck predating
    diode-device recognition silently: two installs reporting the identical
    ``klt --version`` string had different device coverage, and nothing
    short of a live extraction diff (or hand-inspecting ``provenance``) could
    tell them apart. ``klt deck info`` answers "what does *this* install's
    deck actually recognise, and is it even a released build" directly,
    with no input layout needed.

    ``name`` narrows to one deck (:class:`UnknownExtractionDeckError`,
    surfaced as :class:`DeckHistoryError`, for an unregistered name); omitted
    (the default) reports every registered deck
    (:func:`klayout_tools.decks.known_extraction_deck_names`).

    Returns a ``{"schema_version": 1, "decks": [...]}`` envelope; each entry
    is:

    - ``deck`` -- the deck name.
    - ``content_hash`` -- this install's ``sha256:``-prefixed deck module
      hash (the same computation and shape as
      ``provenance.deck.content_hash``), or ``None`` if the deck's source
      file can't be hashed.
    - ``device_classes`` -- the device-class roles this deck is structurally
      capable of recognising (``ExtractionDeck.device_classes``), e.g.
      whether ``diode_nd2ps_06v0``/``diode_pd2nw_06v0`` are wired up at all --
      independent of whether any given layout actually contains one.
    - ``released`` -- the same tri-state signal as
      ``provenance.deck.released`` (:func:`is_deck_hash_released`): ``True``
      when this exact content hash shipped in a tagged release, ``False``
      when the history table confirms it did not (an unreleased/dev
      checkout, or an uncommitted local deck edit), ``None`` when the answer
      can't be determined (hash or history table unavailable).
    - ``release`` -- when ``released`` is ``True``, the
      ``{git_tag, git_commit, package_version}`` of the (newest) matching
      release, the same information :func:`resolve_deck` would return for
      this hash; ``None`` otherwise.
    """
    # Imported lazily, not at module scope: `_provenance` itself imports
    # `is_deck_hash_released` from this module, so a module-level import here
    # would be a circular import (this module would be mid-initialization the
    # first time anything imports `_provenance` first).
    from .._provenance import sha256_file
    from . import (
        UnknownExtractionDeckError,
        deck_source_path,
        get_extraction_deck,
        known_extraction_deck_names,
    )

    names = [name] if name is not None else list(known_extraction_deck_names())

    decks: list[dict[str, Any]] = []
    for deck_name in names:
        try:
            deck = get_extraction_deck(deck_name)
        except UnknownExtractionDeckError as exc:
            raise DeckHistoryError(str(exc)) from exc

        digest = sha256_file(deck_source_path(deck_name))
        content_hash = f"sha256:{digest}" if digest is not None else None
        released = is_deck_hash_released(deck_name, content_hash)

        release: dict[str, Any] | None = None
        if released:
            try:
                match = resolve_deck(content_hash=content_hash, deck=deck_name)
            except DeckHistoryError:
                release = None
            else:
                release = {
                    "git_tag": match["git_tag"],
                    "git_commit": match["git_commit"],
                    "package_version": match["package_version"],
                }

        decks.append(
            {
                "deck": deck_name,
                "content_hash": content_hash,
                "device_classes": list(deck.device_classes),
                "released": released,
                "release": release,
            }
        )

    return {"schema_version": 1, "decks": decks}


#: Check kinds whose threshold is *not* ``DrcRule.threshold_dbu`` -- see
#: :class:`~klayout_tools.decks.rules.DrcRule`'s own field notes. Rules of
#: these kinds author ``threshold_dbu=0`` as an unused placeholder, so
#: :func:`deck_rules` must report ``value_um: null`` for them rather than a
#: fabricated ``0.0`` (issue #2308).
_NON_DISTANCE_CHECKS = frozenset({"area", "density", "antenna"})


def deck_rules(name: str, rule_id: str | None = None) -> dict[str, Any]:
    """The *numbers* a built-in DRC deck enforces, as structured data --
    without running a check against any layout (issue #2308).

    ``klt deck info`` reports a deck's identity (content hash) and structural
    device-class coverage; ``klt drc`` reports *violations* of a deck's rules
    and therefore needs a stream. Neither exposes the rule table itself, so
    pre-layout arithmetic (area budgeting, device pitch, "is this
    segmentation even drawable") had no way to ask "what is this deck's
    minimum poly width" other than transcribing a constant out of a deck
    comment by hand -- a copy that silently stops tracking the deck the
    moment the deck moves.

    ``name`` selects the deck (:class:`~klayout_tools.decks.UnknownDeckError`,
    surfaced as :class:`DeckHistoryError`, for an unregistered name).
    ``rule_id`` narrows to a single rule by exact :attr:`DrcRule.id` -- an id
    no rule in the deck carries is a :class:`DeckHistoryError`, never an
    empty list (a silent empty result reads as "this deck has no such
    constraint", which is a materially different claim from "you asked for a
    rule that does not exist").

    Returns a flat envelope:

    - ``deck`` -- the deck name, as given.
    - ``content_hash`` -- this install's ``sha256:``-prefixed deck module
      hash, the same value :func:`deck_info`/``provenance.deck.content_hash``
      report, so a consumer can pin the exact deck revision a constant was
      read from and detect drift on the next PDK bump. ``None`` when the
      deck's source file cannot be hashed.
    - ``nominal_dbu_um`` -- the deck's ``NOMINAL_DBU_UM``
      (:func:`~klayout_tools.decks.get_nominal_dbu`), the factor
      ``value_dbu`` was converted by.
    - ``rules`` -- one entry per rule, in the deck's own declaration order
      (a stable order, not sorted: it groups rules by layer the way the deck
      module itself reads).

    Each rule entry carries:

    - ``id`` -- this deck's own rule id, exactly as :attr:`DrcRule.id`
      spells it (``"poly.width.1"``), **not** the upstream PDK's rule
      numbering -- that lives in ``provenance.rule_id``.
    - ``description`` / ``check`` / ``layers`` / ``scope`` -- the rule's
      prose description, its check primitive, the drawn layer name(s) it
      reads (``"poly.drawing"``; ``"<layer>/<datatype>"`` when the deck
      publishes no name for the pair), and its DRM scope (``None`` when
      unscoped).
    - ``value_um`` / ``value_dbu`` -- the rule's distance threshold in
      micrometres and in the deck's nominal dbu. Both are ``None`` for the
      check kinds that do not use ``threshold_dbu`` (``area``, ``density``,
      ``antenna``) rather than reporting the unused ``0`` those rules author
      as a placeholder.
    - ``limits`` -- the kind-specific numerics for exactly those kinds
      (``area_min_um2``/``area_max_um2``, ``density_window_um``/
      ``density_min``/``density_max``, ``antenna_ratio_max``). Always
      present; empty (``{}``) for a plain distance check, whose number is
      ``value_um``.
    - ``provenance`` -- the rule's structured upstream citation
      (:class:`~klayout_tools.decks.rules.RuleProvenance` as a dict), or
      ``None`` when the rule carries no structured provenance yet (its
      inline comment remains the only record).
    """
    # Imported lazily for the same circular-import reason `deck_info` is --
    # see its own note.
    from .._provenance import sha256_file
    from . import (
        UnknownDeckError,
        deck_source_path,
        get_deck,
        get_layer_names,
        get_nominal_dbu,
    )

    try:
        rules = get_deck(name)
        nominal_dbu = get_nominal_dbu(name)
    except UnknownDeckError as exc:
        raise DeckHistoryError(str(exc)) from exc

    if rule_id is not None:
        selected = [rule for rule in rules if rule.id == rule_id]
        if not selected:
            raise DeckHistoryError(
                f"deck {name!r} has no rule with id {rule_id!r} "
                f"({len(rules)} rules registered; run "
                f"`klt deck rules --deck {name}` to list them)"
            )
        rules = selected

    layer_names = get_layer_names(name)
    digest = sha256_file(deck_source_path(name))

    return {
        "schema_version": 1,
        "deck": name,
        "content_hash": f"sha256:{digest}" if digest is not None else None,
        "nominal_dbu_um": nominal_dbu,
        "rules": [_project_rule(rule, nominal_dbu, layer_names) for rule in rules],
    }


def deck_devices(name: str, device_class: str | None = None) -> dict[str, Any]:
    """The *drawn-layer predicate set* every device class an extraction deck
    declares is recognised by -- its device-recognition marker layer plus the
    per-terminal ``requires``/``excludes`` narrowing -- as structured data,
    without reading the deck module's Python source (issue #2365).

    ``klt deck info``'s ``device_classes`` answers "can this deck recognise a
    ``diode_pd2nw_06v0`` at all"; it does **not** say what has to be *drawn*
    for one to be recognised. That gap is expensive: most of a deck's device
    families (MOS, and every markerless class) are driven off drawn geometry
    alone, but a minority are gated on a dedicated device-recognition marker
    layer *and* on per-terminal implant predicates -- e.g. gf180mcu's
    ``diode_pd2nw_06v0`` needs ``diode_mk`` (115/5) over the junction **and**
    ``Pplus`` (31/0) + ``Dualgate`` (55/0) over its anode. A layout missing
    any single member of that set extracts as ``device_count: 0``, which
    reads exactly like "this layout legitimately contains no diodes", so the
    only way to find out which member was missing used to be reading
    ``decks/gf180mcu.py`` field by field. This answers it in one query.

    ``name`` selects the extraction deck
    (:class:`~klayout_tools.decks.UnknownExtractionDeckError`, surfaced as
    :class:`DeckHistoryError`, for an unregistered name). ``device_class``
    narrows to a single entry by exact ``name`` -- a class the deck does not
    declare is a :class:`DeckHistoryError`, never an empty list (a silent
    empty result reads as "that class has no drawn-layer requirements",
    which is a materially different claim from "you asked for a class that
    does not exist"), mirroring :func:`deck_rules`' ``rule_id`` contract.

    Returns a flat envelope:

    - ``deck`` / ``content_hash`` -- the deck name as given, and this
      install's ``sha256:``-prefixed deck module hash (the same value
      :func:`deck_info`/``provenance.deck.content_hash`` report), so a
      transcribed layer number stays re-checkable against the installed deck
      on the next PDK bump.
    - ``device_classes`` -- one entry per declared device class, in the
      deck's own declaration order: the two MOS classes first (they are
      declared by every deck), then bipolars, MiM capacitors, MoM
      capacitors, drawn resistors and junction diodes -- the same order
      :attr:`~klayout_tools.decks.ExtractionDeck.device_classes` lists.

    Each entry carries:

    - ``name`` -- the ``devices[].class`` label this class extracts as.
    - ``kind`` -- the recognition family (``"mos"``, ``"bipolar"``,
      ``"capacitor"``, ``"mom_capacitor"``, ``"resistor"``, ``"diode"``).
    - ``marker`` -- the class's device-recognition marker layer, or ``None``
      for a markerless (geometry-driven) class.
    - ``marker_gated`` / ``predicate_gated`` -- booleans, so "which classes
      need something beyond their own conductor/diffusion geometry" is
      answerable by filtering rather than by prose. ``marker_gated`` is
      ``marker is not None``; ``predicate_gated`` is ``True`` when any
      terminal declares a non-empty ``requires``.
    - ``terminals`` -- one entry per recognised terminal, each
      ``{name, layer, requires, excludes}``. ``layer`` is ``None`` for a
      terminal formed by the substrate rather than by a drawn mask (e.g.
      ``diode_nd2ps_06v0``'s anode).
    - ``required_layers`` / ``excluded_layers`` -- the flattened union, in
      first-mention order: every layer that must be drawn over the geometry
      for this class to be recognised, and every layer whose presence
      disqualifies it. ``required_layers`` is the "what am I missing?" list
      the near-miss diagnostic in ``klt extract``'s ``warnings[]`` names
      entries from.
    - ``provenance`` -- the entry's structured upstream PDK-LVS citation
      (:class:`~klayout_tools.decks.rules.RuleProvenance` as a dict), or
      ``None`` when it carries none yet.

    Every layer is reported as ``{"layer": <int>, "datatype": <int>,
    "name": <str|null>}`` -- the raw GDS numbering a layout is drawn in,
    plus the deck's published name for the pair when it publishes one
    (``null`` rather than a fabricated name when it does not).
    """
    # Imported lazily for the same circular-import reason `deck_info` is --
    # see its own note.
    from .._provenance import sha256_file
    from . import (
        UnknownExtractionDeckError,
        deck_source_path,
        get_extraction_deck,
        get_layer_names,
    )

    try:
        deck = get_extraction_deck(name)
    except UnknownExtractionDeckError as exc:
        raise DeckHistoryError(str(exc)) from exc

    layer_names = get_layer_names(name)
    entries = _project_device_classes(deck, layer_names)

    if device_class is not None:
        selected = [entry for entry in entries if entry["name"] == device_class]
        if not selected:
            declared = ", ".join(entry["name"] for entry in entries)
            raise DeckHistoryError(
                f"deck {name!r} declares no device class named "
                f"{device_class!r} (declared: {declared}; run "
                f"`klt deck devices --deck {name}` to list them)"
            )
        entries = selected

    digest = sha256_file(deck_source_path(name))

    return {
        "schema_version": 1,
        "deck": name,
        "content_hash": f"sha256:{digest}" if digest is not None else None,
        "device_classes": entries,
    }


def _layer_entry(
    pair: tuple[int, int] | None, layer_names: dict[tuple[int, int], str]
) -> dict[str, Any] | None:
    """One ``(layer, datatype)`` pair as :func:`deck_devices`' layer object.

    ``None`` in, ``None`` out -- a terminal a PDK draws no mask for (the
    substrate side of a junction diode) reports a ``null`` layer rather than
    a fabricated pair.
    """
    if pair is None:
        return None
    return {
        "layer": pair[0],
        "datatype": pair[1],
        "name": layer_names.get(pair),
    }


def _terminal_entry(
    name: str,
    layer: tuple[int, int] | None,
    requires: tuple[tuple[int, int], ...],
    excludes: tuple[tuple[int, int], ...],
    layer_names: dict[tuple[int, int], str],
) -> dict[str, Any]:
    """One terminal of a device class, in :func:`deck_devices`' shape."""
    return {
        "name": name,
        "layer": _layer_entry(layer, layer_names),
        "requires": [_layer_entry(pair, layer_names) for pair in requires],
        "excludes": [_layer_entry(pair, layer_names) for pair in excludes],
    }


def _device_class_entry(
    *,
    name: str,
    kind: str,
    marker: tuple[int, int] | None,
    terminals: list[dict[str, Any]],
    layer_names: dict[tuple[int, int], str],
    provenance: Any = None,
    extra: dict[str, Any] | None = None,
) -> dict[str, Any]:
    """Assemble one :func:`deck_devices` ``device_classes[]`` entry, deriving
    the flattened ``required_layers``/``excluded_layers`` union (and the two
    gating booleans) from ``marker`` + ``terminals`` so the summary can never
    drift from the per-terminal detail it summarises."""
    required: list[dict[str, Any]] = []
    excluded: list[dict[str, Any]] = []

    def add(bucket: list[dict[str, Any]], entry: dict[str, Any] | None) -> None:
        if entry is None:
            return
        pair = (entry["layer"], entry["datatype"])
        if any((e["layer"], e["datatype"]) == pair for e in bucket):
            return
        bucket.append(entry)

    marker_entry = _layer_entry(marker, layer_names)
    add(required, marker_entry)
    predicate_gated = False
    for terminal in terminals:
        add(required, terminal["layer"])
        for entry in terminal["requires"]:
            predicate_gated = True
            add(required, entry)
        for entry in terminal["excludes"]:
            add(excluded, entry)

    return {
        "name": name,
        "kind": kind,
        "marker": marker_entry,
        "marker_gated": marker_entry is not None,
        "predicate_gated": predicate_gated,
        "terminals": terminals,
        "required_layers": required,
        "excluded_layers": excluded,
        **(extra or {}),
        "provenance": _provenance_entry(provenance),
    }


def _provenance_entry(provenance: Any) -> dict[str, Any] | None:
    """A :class:`RuleProvenance` as a plain dict, matching
    :func:`_project_rule`'s own projection; ``None`` passes through."""
    if provenance is None:
        return None
    return {
        "source_repo": provenance.source_repo,
        "source_path": provenance.source_path,
        "rule_id": provenance.rule_id,
        "commit": provenance.commit,
    }


def _project_device_classes(
    deck: Any, layer_names: dict[tuple[int, int], str]
) -> list[dict[str, Any]]:
    """Every device class ``deck`` declares, projected into
    :func:`deck_devices`' ``device_classes[]`` shape.

    Ordered exactly as :attr:`ExtractionDeck.device_classes` orders its own
    role tokens (MOS, bipolars, capacitors, MoM capacitors, resistors,
    diodes) so the two lists read against each other without re-sorting.
    """
    entries: list[dict[str, Any]] = []

    # MOS. Markerless by construction: recognition is the deck's own
    # active/poly/nwell stack, split by which side of the well the active
    # island sits on (see `ExtractionDeck`'s docstring). Reported anyway --
    # "this class needs no marker" is exactly the fact a caller comparing
    # against a marker-gated class needs to see, and the `nwell`
    # require/exclude asymmetry is what tells NMOS from PMOS (so `pfet`
    # reports `predicate_gated: true` on `nwell`, which is the literal
    # truth: a PMOS is not recognised outside the well).
    for class_name, in_well in ((deck.nfet_class, False), (deck.pfet_class, True)):
        entries.append(
            _device_class_entry(
                name=class_name,
                kind="mos",
                marker=None,
                terminals=[
                    _terminal_entry(
                        "source_drain",
                        deck.active,
                        (deck.nwell,) if in_well else (),
                        () if in_well else (deck.nwell,),
                        layer_names,
                    ),
                    _terminal_entry(
                        "gate",
                        deck.poly,
                        (deck.nwell,) if in_well else (),
                        () if in_well else (deck.nwell,),
                        layer_names,
                    ),
                ],
                layer_names=layer_names,
                provenance=(deck.pfet_provenance if in_well else deck.nfet_provenance),
                extra={
                    "flavours": [
                        {
                            "flavour": flavour.flavour,
                            "description": flavour.description or None,
                            "marker": _layer_entry(flavour.marker, layer_names),
                        }
                        for flavour in deck.mos_flavours
                    ]
                },
            )
        )

    for bipolar in deck.bipolars:
        entries.append(
            _device_class_entry(
                name=bipolar.class_name,
                kind="bipolar",
                marker=bipolar.marker,
                terminals=[
                    _terminal_entry("base", bipolar.base, (), (), layer_names),
                    _terminal_entry(
                        "emitter",
                        bipolar.emitter,
                        bipolar.emitter_requires,
                        bipolar.emitter_excludes,
                        layer_names,
                    ),
                    _terminal_entry(
                        "collector", bipolar.collector, (), (), layer_names
                    ),
                ],
                layer_names=layer_names,
                provenance=bipolar.provenance,
            )
        )

    for capacitor in deck.capacitors:
        entries.append(
            _device_class_entry(
                name=capacitor.name,
                kind="capacitor",
                marker=None,
                terminals=[
                    _terminal_entry(
                        "top_plate",
                        capacitor.top_plate,
                        capacitor.top_plate_requires,
                        capacitor.top_plate_excludes,
                        layer_names,
                    ),
                    _terminal_entry(
                        "bottom_plate",
                        capacitor.bottom_plate,
                        capacitor.bottom_plate_requires,
                        capacitor.bottom_plate_excludes,
                        layer_names,
                    ),
                ],
                layer_names=layer_names,
                provenance=capacitor.provenance,
            )
        )

    for mom in deck.mom_capacitors:
        entries.append(
            _device_class_entry(
                name=mom.name,
                kind="mom_capacitor",
                marker=mom.marker,
                terminals=[
                    _terminal_entry(f"pin{index}", pin, (), (), layer_names)
                    for index, pin in enumerate(mom.metal_pins)
                    if pin is not None
                ],
                layer_names=layer_names,
                provenance=mom.provenance,
            )
        )

    for resistor in deck.resistors:
        entries.append(
            _device_class_entry(
                name=resistor.name,
                kind="resistor",
                marker=resistor.marker,
                terminals=[
                    _terminal_entry(
                        "body",
                        resistor.body,
                        resistor.requires,
                        resistor.excludes,
                        layer_names,
                    ),
                    _terminal_entry("terminal", resistor.terminal, (), (), layer_names),
                ],
                layer_names=layer_names,
                provenance=resistor.provenance,
            )
        )

    for diode in deck.diodes:
        entries.append(
            _device_class_entry(
                name=diode.name,
                kind="diode",
                marker=diode.marker,
                terminals=[
                    _terminal_entry(
                        "anode",
                        diode.anode,
                        diode.anode_requires,
                        diode.anode_excludes,
                        layer_names,
                    ),
                    _terminal_entry(
                        "cathode",
                        diode.cathode,
                        diode.cathode_requires,
                        diode.cathode_excludes,
                        layer_names,
                    ),
                ],
                layer_names=layer_names,
                provenance=diode.provenance,
            )
        )

    return entries


def _project_rule(
    rule: DrcRule,
    nominal_dbu: float,
    layer_names: dict[tuple[int, int], str],
) -> dict[str, Any]:
    """Project one :class:`DrcRule` into :func:`deck_rules`' JSON shape."""
    is_distance = rule.check not in _NON_DISTANCE_CHECKS
    provenance = rule.provenance

    return {
        "id": rule.id,
        "description": rule.description,
        "check": rule.check,
        "layers": _rule_layers(rule, layer_names),
        "scope": rule.scope or None,
        "value_um": _scaled(rule.threshold_dbu, nominal_dbu) if is_distance else None,
        "value_dbu": rule.threshold_dbu if is_distance else None,
        "limits": _rule_limits(rule, nominal_dbu),
        "provenance": (
            None
            if provenance is None
            else {
                "source_repo": provenance.source_repo,
                "source_path": provenance.source_path,
                "rule_id": provenance.rule_id,
                "commit": provenance.commit,
            }
        ),
    }


def _rule_layers(rule: DrcRule, layer_names: dict[tuple[int, int], str]) -> list[str]:
    """The drawn layer name(s) a rule reads, in ``layer``/``other_layer``
    order -- the deck's published name when it has one, else the raw
    ``"<layer>/<datatype>"`` pair so the entry is never empty."""
    pairs = [rule.layer]
    if rule.other_layer is not None:
        pairs.append(rule.other_layer)
    return [layer_names.get(pair) or f"{pair[0]}/{pair[1]}" for pair in pairs]


def _rule_limits(rule: DrcRule, nominal_dbu: float) -> dict[str, Any]:
    """The kind-specific numeric limits of a non-distance check kind.

    Empty for every distance check (``width``/``space``/``separation``/...),
    whose one number is ``value_um``. Areas convert by ``nominal_dbu ** 2``
    -- an area scales with the *square* of a linear rescaling (see
    :class:`~klayout_tools.decks.rules.DrcRule`'s ``area_min_dbu2`` note).
    """
    if rule.check == "area":
        area_factor = nominal_dbu * nominal_dbu
        return {
            "area_min_um2": _scaled(rule.area_min_dbu2, area_factor),
            "area_max_um2": _scaled(rule.area_max_dbu2, area_factor),
        }
    if rule.check == "density":
        return {
            "density_window_um": rule.density_window_um,
            "density_min": rule.density_min,
            "density_max": rule.density_max,
        }
    if rule.check == "antenna":
        return {"antenna_ratio_max": rule.antenna_ratio_max}
    return {}


def _scaled(value: int | None, factor: float) -> float | None:
    """``value * factor``, rounded to sub-femtometre precision so a deck's
    integer dbu threshold reports as the decimal a human would write
    (``150 * 0.001`` is ``0.15``, not ``0.15000000000000002``). ``None`` in,
    ``None`` out -- an unset bound has no converted value."""
    if value is None:
        return None
    return round(value * factor, 9)


def _not_found_message(
    *,
    content_hash: str | None = None,
    deck: str | None = None,
    version: str | None = None,
) -> str:
    entries = _load_history()["entries"]
    tags = sorted({str(e.get("git_tag")) for e in entries})
    known_range = f"{tags[0]}..{tags[-1]}" if tags else "<empty>"

    if content_hash is not None:
        scope = f" for deck '{deck}'" if deck is not None else ""
        return (
            f"no known release{scope} ships deck content hash {content_hash!r} "
            f"(not found in known deck history, which covers {known_range} -- "
            "the hash may predate the table's start, be from an unreleased "
            "build, or never have shipped)"
        )
    return (
        f"no known release ships deck {deck!r} at version {version!r} "
        f"(known deck history covers {known_range}; known decks: "
        f"{', '.join(known_deck_names())})"
    )
