"""Resolve klt's built-in DRC/LVS rule decks by content hash or by
``(name, version)`` against a release-time-generated history table
(issue #623).

A repo verifying committed DRC evidence sometimes needs to reproduce a
report against a *specific past revision* of a built-in rule deck --
``provenance.deck.content_hash`` (``docs/json-contract.md``) pins exactly
which bytes produced a "clean" verdict, but on its own there was previously
no tool-level way to turn that hash back into "what do I `pip install` (or
`git checkout` + build) to reproduce it" other than hand-bisecting this
repo's own git history. This module is the pure-lookup half of that fix
(``cli/deck_cmd.py`` wires it to ``klt deck resolve``); the actual
regeneration of the table lives in ``scripts/generate_deck_history.py`` at
the repo root -- see that script's docstring for how/when it runs.

This is deliberately **resolve-only**: it never fetches, checks out, or
builds a historical revision in-process (see issue #623's "Suggested
capability" -- that would need a git-clone-and-checkout-on-demand mechanism
with no precedent in this codebase, and re-introduces exactly the
"needs the invoking environment to already have the full git history"
friction the issue exists to eliminate). The caller still runs
``pip install klayout-tools==X.Y.Z`` (or checks out the reported tag and
builds it) themselves.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

#: Generated by ``scripts/generate_deck_history.py`` -- see that script's
#: module docstring. Never hand-edited.
_HISTORY_PATH = Path(__file__).resolve().parent / "_history.json"


class DeckHistoryError(Exception):
    """Raised by :func:`resolve_deck` for an invalid query (neither
    ``content_hash`` nor a complete ``deck``+``version`` pair given) or a
    query that matches no entry in the generated history table.

    ``cli/deck_cmd.py`` turns this into the documented error envelope
    (``docs/json-contract.md``) -- a clean message and exit code 1, never a
    traceback.
    """


def _load_history() -> dict[str, Any]:
    try:
        raw = _HISTORY_PATH.read_text()
    except OSError as exc:
        raise DeckHistoryError(
            f"deck history table not found or unreadable: {_HISTORY_PATH} ({exc})"
        ) from exc
    try:
        data = json.loads(raw)
    except json.JSONDecodeError as exc:
        raise DeckHistoryError(
            f"deck history table is not valid JSON: {_HISTORY_PATH} ({exc})"
        ) from exc
    if not isinstance(data, dict) or not isinstance(data.get("entries"), list):
        raise DeckHistoryError(
            f"deck history table is malformed (missing 'entries' list): {_HISTORY_PATH}"
        )
    return data


def known_deck_names() -> list[str]:
    """Every deck name the history table has at least one entry for,
    sorted -- used to build a helpful "not found" message."""
    entries = _load_history()["entries"]
    return sorted({str(entry.get("deck")) for entry in entries})


def resolve_deck(
    *,
    content_hash: str | None = None,
    deck: str | None = None,
    version: str | None = None,
) -> dict[str, Any]:
    """Resolve a deck query against the generated history table.

    Two mutually available query shapes (issue #623's acceptance criteria):

    - ``content_hash`` (a ``sha256:<hex>`` string, matching
      ``provenance.deck.content_hash``'s shape) alone, optionally narrowed
      by ``deck``. When more than one release shipped byte-identical deck
      content (the deck simply didn't change between releases), the *newest*
      matching release is returned -- so resolving the currently-installed
      build's own deck hash against its own from-source history always
      reports back that same currently-running version, never a stale
      earlier one that happened to ship the same bytes first.
    - ``deck`` and ``version`` together, an exact ``(name, package_version)``
      lookup.

    Raises :class:`DeckHistoryError` for an incomplete/invalid query, or one
    that matches no entry (a hash that predates the table's start, was never
    released, or a ``deck``/``version`` combination that never shipped) --
    never returns a null/empty match silently.
    """
    if content_hash is None and (deck is None or version is None):
        raise DeckHistoryError(
            "klt deck resolve requires either --content-hash, or both "
            "--deck and --version"
        )

    entries = _load_history()["entries"]

    if content_hash is not None:
        candidates = [e for e in entries if e.get("content_hash") == content_hash]
        if deck is not None:
            candidates = [e for e in candidates if e.get("deck") == deck]
        if not candidates:
            raise DeckHistoryError(
                _not_found_message(content_hash=content_hash, deck=deck)
            )
        # Newest release last (the table is generated in ascending git-tag
        # order -- see generate_deck_history.py); picking the last match
        # reports the currently-running version when the deck hasn't
        # changed since an earlier release also shipped this exact hash.
        match = candidates[-1]
    else:
        candidates = [
            e
            for e in entries
            if e.get("deck") == deck and e.get("package_version") == version
        ]
        if not candidates:
            raise DeckHistoryError(_not_found_message(deck=deck, version=version))
        match = candidates[-1]

    return {
        "schema_version": 1,
        "query": {"content_hash": content_hash, "deck": deck, "version": version},
        "deck": match["deck"],
        "content_hash": match["content_hash"],
        "git_tag": match["git_tag"],
        "git_commit": match["git_commit"],
        "package_version": match["package_version"],
    }


def is_deck_hash_released(deck: str | None, content_hash: str | None) -> bool | None:
    """Whether ``content_hash`` (optionally narrowed to ``deck``) appears in
    the generated deck history table -- the release-tracking half of the
    ``provenance.deck.released`` signal (issue #1193).

    A "clean" report against a deck content hash with no released
    counterpart is unreproducible evidence the moment it's committed, but
    nothing said so at generation time -- this turns that into a checkable
    fact alongside ``provenance.deck.content_hash`` itself, without making a
    generation-time run *fail* over it (the deck still ran; a dev checkout,
    an uncommitted deck edit, or a deck added after the last tag are all
    ordinary, not errors).

    Returns:
        ``True`` -- ``content_hash`` matches at least one history entry
            (narrowed to ``deck`` when given).
        ``False`` -- the history table loaded fine but no entry matches; the
            hash is confirmed *not* released (predates the table, an
            unreleased/dev build, or a deck added after the last tag).
        ``None`` -- the answer can't be determined: ``content_hash`` is
            falsy (nothing to look up), or the history table itself is
            missing, unreadable, or malformed. Deliberately distinct from
            ``False`` -- callers must never turn "couldn't check" into a
            "confirmed unresolvable" claim (see this function's docstring
            and issue #1193's edge-case requirement that a missing/broken
            history table degrade gracefully rather than fabricate a
            warning).
    """
    if not content_hash:
        return None
    try:
        entries = _load_history()["entries"]
    except DeckHistoryError:
        return None
    candidates = [e for e in entries if e.get("content_hash") == content_hash]
    if deck is not None:
        candidates = [e for e in candidates if e.get("deck") == deck]
    return bool(candidates)


def deck_info(name: str | None = None) -> dict[str, Any]:
    """The *currently installed* build's own deck content hash, structural
    device-class coverage, and release status -- without running a live
    extraction against any input layout (issue #1209).

    ``klt deck resolve``/``provenance.deck.content_hash`` (issue #1193's
    ``released`` flag) both require a caller to already *have* a content
    hash in hand -- normally obtained by running ``klt extract``/``drc``/
    ``lvs`` against some input layout and reading it out of the buried
    ``provenance`` block of the JSON report. That is exactly the gap that
    let PyPI's ``klayout-tools==0.2.0`` ship a ``gf180mcu`` deck predating
    diode-device recognition silently: two installs reporting the identical
    ``klt --version`` string had different device coverage, and nothing
    short of a live extraction diff (or hand-inspecting ``provenance``) could
    tell them apart. ``klt deck info`` answers "what does *this* install's
    deck actually recognise, and is it even a released build" directly,
    with no input layout needed.

    ``name`` narrows to one deck (:class:`UnknownExtractionDeckError`,
    surfaced as :class:`DeckHistoryError`, for an unregistered name); omitted
    (the default) reports every registered deck
    (:func:`klayout_tools.decks.known_extraction_deck_names`).

    Returns a ``{"schema_version": 1, "decks": [...]}`` envelope; each entry
    is:

    - ``deck`` -- the deck name.
    - ``content_hash`` -- this install's ``sha256:``-prefixed deck module
      hash (the same computation and shape as
      ``provenance.deck.content_hash``), or ``None`` if the deck's source
      file can't be hashed.
    - ``device_classes`` -- the device-class roles this deck is structurally
      capable of recognising (``ExtractionDeck.device_classes``), e.g.
      whether ``diode_nd2ps_06v0``/``diode_pd2nw_06v0`` are wired up at all --
      independent of whether any given layout actually contains one.
    - ``released`` -- the same tri-state signal as
      ``provenance.deck.released`` (:func:`is_deck_hash_released`): ``True``
      when this exact content hash shipped in a tagged release, ``False``
      when the history table confirms it did not (an unreleased/dev
      checkout, or an uncommitted local deck edit), ``None`` when the answer
      can't be determined (hash or history table unavailable).
    - ``release`` -- when ``released`` is ``True``, the
      ``{git_tag, git_commit, package_version}`` of the (newest) matching
      release, the same information :func:`resolve_deck` would return for
      this hash; ``None`` otherwise.
    """
    # Imported lazily, not at module scope: `_provenance` itself imports
    # `is_deck_hash_released` from this module, so a module-level import here
    # would be a circular import (this module would be mid-initialization the
    # first time anything imports `_provenance` first).
    from .._provenance import sha256_file
    from . import (
        UnknownExtractionDeckError,
        deck_source_path,
        get_extraction_deck,
        known_extraction_deck_names,
    )

    names = [name] if name is not None else list(known_extraction_deck_names())

    decks: list[dict[str, Any]] = []
    for deck_name in names:
        try:
            deck = get_extraction_deck(deck_name)
        except UnknownExtractionDeckError as exc:
            raise DeckHistoryError(str(exc)) from exc

        digest = sha256_file(deck_source_path(deck_name))
        content_hash = f"sha256:{digest}" if digest is not None else None
        released = is_deck_hash_released(deck_name, content_hash)

        release: dict[str, Any] | None = None
        if released:
            try:
                match = resolve_deck(content_hash=content_hash, deck=deck_name)
            except DeckHistoryError:
                release = None
            else:
                release = {
                    "git_tag": match["git_tag"],
                    "git_commit": match["git_commit"],
                    "package_version": match["package_version"],
                }

        decks.append(
            {
                "deck": deck_name,
                "content_hash": content_hash,
                "device_classes": list(deck.device_classes),
                "released": released,
                "release": release,
            }
        )

    return {"schema_version": 1, "decks": decks}


def _not_found_message(
    *,
    content_hash: str | None = None,
    deck: str | None = None,
    version: str | None = None,
) -> str:
    entries = _load_history()["entries"]
    tags = sorted({str(e.get("git_tag")) for e in entries})
    known_range = f"{tags[0]}..{tags[-1]}" if tags else "<empty>"

    if content_hash is not None:
        scope = f" for deck '{deck}'" if deck is not None else ""
        return (
            f"no known release{scope} ships deck content hash {content_hash!r} "
            f"(not found in known deck history, which covers {known_range} -- "
            "the hash may predate the table's start, be from an unreleased "
            "build, or never have shipped)"
        )
    return (
        f"no known release ships deck {deck!r} at version {version!r} "
        f"(known deck history covers {known_range}; known decks: "
        f"{', '.join(known_deck_names())})"
    )
